gip-inclusion/le-marche

CHANGELOG.md, Dockerfile, config/runner.sh, config/settings.py, config/urls.py, poetry.lock, pyproject.toml
Ajout de la librairie [whitenoise](http://whitenoise.evans.io/en/stable/) pour fluidifier la publication des fichiers statiques sans mettre en place toute une plomberie pour faire fonctionner le tout aussi bien quand le débogage est engagé ou non.
=> Serve static files

config/asgi.py, config/settings/dev.py, config/settings/prod.py, config/urls.py, config/wsgi.py, manage.py, poetry.lock, pyproject.toml
Les 2 packets sont configurés pour être installés seulement en local/dev
https://django-debug-toolbar.readthedocs.io/en/latest/
- pour avoir d'avantage d'information sur les requêtes
- utile pour optimiser les requêtes (SQL)
https://django-extensions.readthedocs.io/en/latest/
- pas mal d'outils utiles : shell_plus, graph_models, ...
=> Ajout d'outils de développement (django-debug-toolbar, django-extensions)

README.md, config/dev/entrypoint.sh, docker-compose.yml
- Mise à jour docker-compose pour permettre l'exécution en local de tout l'environnement
- Le docker-compose ne reflétait pas encore les dernières modifications
- L'équipe intégration nécessite un environnement simple a instancier et stable
- Mise à jour des ports utilisés dans la documentation
- Utilisation cohérente des ports utilisés : ceux utilisés par UWSGI et ceux publiés par docker (port `8880`)
- Ajout des commandes nécessaires à la publication de pages statiques dans le script de démarrage
=> :whale: updated docker compose environment

config/settings/base.py, lemarche/static/itou_marche/base/_custom.scss, lemarche/templates/admin/base.html, lemarche/templates/includes/_header_env_notice.html, lemarche/templates/includes/_header_notice.html, lemarche/templates/includes/_trackers.html, lemarche/templates/layouts/_header.html, lemarche/utils/settings_context_processors.py
- Affiche un bandeau en haut lorsque l'application est lancée en dev, staging ou review_app
- Idem dans l'interface admin
Pour bien différencier les environnements, et éviter de faire de fausses manip en prod
=> Afficher un bandeau pour différencier les environnements

CHANGELOG.md, lemarche/api/networks/serializers.py, lemarche/api/siaes/filters.py, lemarche/api/siaes/serializers.py, lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py, lemarche/api/urls.py, lemarche/siaes/models.py, lemarche/templates/api/home.html
- filtrer les structures par réseau
- ajouter des champs supplémentaires dans la réponse
- quelques améliorations
=> API : filtrer les structures par réseau

lemarche/siaes/admin.py, lemarche/siaes/models.py, lemarche/siaes/tests.py
Sur le modèle `Siae`, on a rajouté certains champs `*_count` pour éviter trop de requêtes join à certains endroits de l'application, et avoir cette information dans Metabase.
Mais certains de ces champs l(les M2M) n'étaient pas mis à jour lors du `save()` d'une instance.
Réparé à l'aide des signals `m2m_changed`
=> Fix : mise à jour des champs count en temps réel

lemarche/templates/pages/contact.html, lemarche/templates/pages/contact_form_email_body.txt, lemarche/templates/pages/contact_form_receipt_email_body.txt, lemarche/www/pages/forms.py, lemarche/www/pages/tasks.py, lemarche/www/pages/views.py
- texte d'introduction pour orienter les demandes "emplois" vers l'outil d'assistance
- ajouter d'un champ "type d'utilisateur"
- envoyer un email de confirmation aux utilisateurs qui ont indiqué "SIAE" comme type d'utilisateur
=> Améliorations sur le formulaire de contact

config/settings/test.py, lemarche/siaes/models.py, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py, lemarche/www/siaes/views.py
lorsque je fais une recherche par ville , les résultats s'affichent en fonction de la distance avec le centre ville. 
En tant qu'acheteur je souhaite voir les esi qui ont les informations les plus complètes en premier 
- [lien de test local](http://127.0.0.1:8000/prestataires/?sectors=apiculture&sectors=boulangerie-patisserie-confiseries-118&sectors=confiturerie&sectors=fromagerie&sectors=location-vente-de-materiels-de-restauration&sectors=paniers-plateaux-repas&sectors=producteurs-fournisseurs&sectors=restaurants-cantines&sectors=traiteur&sectors=autre-63&perimeter=marseille-13&perimeter_name=Marseille+%2813%29&presta_type=&networks=)
- [lien de test …
=> Moteur de recherche : améliorer l'ordre d'apparition des ESI

config/settings/base.py, lemarche/siaes/management/commands/update_api_qpv_fields.py
Une exception `Read Timeout` est déclenchée dans l'environnement de production car un trop grand nombre d'insertions d'un seul coup (4700).
Mise en place d'une limitation pour le nombre d'update.
=> Fix du script de mise à jours des champs QPV

lemarche/static/itou_marche/components/_multiselect.scss, lemarche/static/itou_marche/layouts/_pages.scss, lemarche/templates/admin/base.html
- répare le lien vers un asset du thème dans notre css
- ne pas afficher le bandeau d'env en prod sur l'admin
=> Quelques petits fix

config/settings/base.py, lemarche/templates/api/home.html, lemarche/utils/settings_context_processors.py
Après publication de l'API sur api.gouv.fr [ici](https://api.gouv.fr/les-api/api-structures-inclusion), on en profite pour mettre à jour la version de l'API
- passage à la version 1.0
- enlève le message temporaire
=> Bump de l'API à la v1

lemarche/static/itou_marche/components/_forms.scss, lemarche/templates/dashboard/siae_edit_info_contact.html, lemarche/templates/dashboard/siae_edit_other.html, lemarche/templates/dashboard/siae_edit_presta.html, lemarche/templates/layouts/base.html, lemarche/www/dashboard/views.py
Images
- répare le fait que les images "réalisations" n'étaient pas envoyées dans le bon bucket (avant : `client_reference_logo` ; maintenant : `siae_image`)
- légère clarification du code JS de dropzone
Autre
- répare l'alignement des radio buttons
- évite d'afficher les messages d'alerte/success en double
=> Améliore l'ajout d'images sur le formulaire structure

lemarche/perimeters/management/commands/import_communes.py, lemarche/perimeters/management/commands/import_departements.py, lemarche/perimeters/management/commands/import_regions.py, lemarche/perimeters/models.py, lemarche/perimeters/tests.py, lemarche/www/siaes/tests.py
Homogénéise la génération des slugs des périmètres Région : rajoute `-region` en suffix à chacuns
Ca générait des conflits lors des lancements des recettes jetables (entre les quelques régions & départements qui ont le même nom)
=> Répare la génération de slug des périmètres Région

clevercloud/review-app-after-success.sh
Avant : les périmètres étaient importés avec des management commands. Cela prenait plusieurs minutes car il y a 35000 communes
Maintenant : les périmètres ont été exportés sous format sql, et sont importés d'un seul coup
=> Accélère l'import des périmètres sur les recettes jetables

lemarche/static/itou_marche/layouts/_pages.scss, lemarche/templates/dashboard/profile_favorite_list_detail.html, lemarche/templates/pages/valoriser-achats.html, lemarche/templates/siaes/search_results.html, lemarche/www/siaes/views.py
suite de https://github.com/betagouv/itou-marche/pull/176
- télécharger directement la liste des structures sur la page "Valoriser ses achats"
- proposer les 2 options : XLS & CSV
- rediriger vers la page de connexion si l'utilisateur n'est pas connecté (en attendant la modale)
- améliorer les id de ces boutons pour le tracking
- utiliser le même icon partout
Sur la page "Valoriser vos achats", l'utilisateur était redirigé vers la page de recherches, ce qui engendrait de la friction (clics supplémentaires).
=> Télécharger directement la liste des structures sur la page "Valoriser vos achats"

lemarche/templates/siaes/detail.html, lemarche/www/auth/views.py, lemarche/www/siaes/tests.py
Un utilisateur doit maintenant être connecté pour afficher les coordonnées d'une structure.
Pour pousser les utilisateurs anonymes à s'inscrire/se connecter.
=> Forcer la connexion pour afficher les coordonnées

clevercloud/cron.json
L'export tournait tous les lundi à minuit. Mais il doit tourner *tous les jours* à minuit.
Suite de https://github.com/betagouv/itou-marche/pull/176
=> CRON : fix sur l'export de toutes les structures

config/settings/_sentry.py
On ne s'en sert pas, elles sont "dropped" de toute façon
=> Sentry : ne plus capturer les détails des transactions

lemarche/fixtures/django/07_networks.json, lemarche/templates/pages/partenaires.html, lemarche/templates/siaes/detail.html
- Afficher le nom du réseau par défaut (et son enseigne entre parenthèses lorsqu'elle est présente)
- Renommer FEI en "Fédération des Entreprises d'Insertion" sur la page Partenaires
=> Meilleur affichage des réseaux

lemarche/templates/siaes/_card_search_result.html, lemarche/templates/siaes/detail.html, lemarche/utils/templatetags/m2m_list_display.py, lemarche/utils/templatetags/siae_sectors_display.py
Si une recherche inclut le filtre sur les secteurs d'activité, alors pour chaque fiche structure retournée on n'affiche que les secteurs d'activités effectivement recherchés (et pas tous les secteurs de la structure)
Meilleure lisibilité des résultats et des fiches structures.
=> Recherche : afficher seulement les secteurs d'activités recherchés des structures

lemarche/templates/dashboard/home.html, lemarche/templates/layouts/_header.html, lemarche/www/auth/tests.py
- renomme 'Mon espace' en 'Tableau de bord'
- renomme 'Mon compte' en 'Mon espace'
Pour être plus proche de l'UX des emplois
=> Renomme 'Mon espace' en 'Tableau de bord'

lemarche/templates/siaes/detail.html, lemarche/utils/templatetags/siae_sectors_display.py, lemarche/utils/templatetags/tests.py
Pour les ETTI avec beaucoup de secteurs d'activité, on affiche déjà "Multisectoriel" sur leur fiche.
L'idée est d'afficher aussi cette information dans la page de résultats.
J'en ai profité pour rajouter des tests sur le templatetag.
=> Afficher aussi Multisectoriel dans les résultats de recherche

lemarche/siaes/models.py, lemarche/static/itou_marche/components/_forms.scss, lemarche/templates/dashboard/profile_favorite_list.html, lemarche/templates/dashboard/siae_edit_info_contact.html, lemarche/templates/dashboard/siae_search_adopt_confirm.html, lemarche/templates/dashboard/siae_search_by_siret.html
- faire en sorte que le formulaire de recherche prenne moins de place
- indiquer plus clairement le nombre de résultats trouvés
- helper pour afficher la source des données en fonction du type de la structure (ca commencait à être trop long pour le faire dans le frontend)
=> Meilleure lisibilité du formulaire de recherche par siret

lemarche/templates/siaes/search_results.html, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py
Bug qui empêchait l'utilisateur d'enlever sa recherche par périmètre (le formulaire était vide, mais ca continuait tout de même à filtrer)
- amélioré la logique
- ajouté des tests
=> Fix : l'utilisateur ne pouvait pas enlever sa recherche par périmètre 

config/settings/base.py
gestion du cas où on a pas le CC_WORKER, qui fait que les tâches ne sont plus exécuté.
Cas déjà produit en prod par la magie de clevercloud.
=> Taches asynchrones :  gestion du cas où on a pas le CC_WORKER

lemarche/siaes/management/commands/sync_c1_c4.py
On ne synchronisait ni la Raison sociale (`name`) ni l'Enseigne (`brand`) des structures.
- pour la Raison sociale, c'est touchy, ca provient de l'ASP, et le `slug` a été généré à partir de lui
- mais l'Enseigne est flexible, vide dans la moitié des cas. C'est elle qu'on affiche si le champ est rempli
=> Synchroniser le champ Enseigne depuis le C1

lemarche/utils/apis/api_entreprise.py
Une des valeurs reçu par l'API Entreprise est "Unité non employeuse".
On remplace par "Non renseigné" pour être plus clair.
=> API Entreprise: renomme une valeur reçu pour le nombre d'employés

lemarche/siaes/admin.py, lemarche/www/siaes/forms.py
QPV
- avant : Quartiers prioritaire de la ville
- maintenant : Quartier prioritaire de la politique de la ville
En profiter pour passer ZRR au singulier aussi.
Mise à jour de l'admin aussi
=> Renommer le terme QPV

lemarche/www/dashboard/mixins.py, lemarche/www/dashboard/tests.py, lemarche/www/dashboard/views.py
On utilisait plusieurs mixins sur certains vues du Dashboard, mais elles ne se comportaient pas comme souhaité.
En fait il n'est pas possible de stacker plusieurs mixins sur une même vue (comme pourrait le faire express.js en Node). En particulier, on souhaitait souvent avoir 2 vérifications : 
- est-ce que l'utilisateur est connecté ou pas ? `LoginRequiredMixin` (si non, redirigé vers la page de login + paramètre `next=?`
- est-ce que l'utilisateur a le droit d'accéder à cette page ou pas ? (si non, redirigé en général vers son tableau de bord `/profil/`)
Du coup la solution est de basculer le comportement de `LoginRequiredMixin` directement dans les mixins d'authorizations
=> Espace utilisateur : meilleure gestion des authorizations

lemarche/siaes/factories.py, lemarche/siaes/models.py, lemarche/siaes/tasks.py, lemarche/siaes/tests.py
Maintenant que les admins peuvent modifier d'avantage certaines structures (dans l'admin), il faut que les coordonnées GPS puissent se mettre à jour en temps réel.
Chaque fois que le champ `address` change, on appelle une tâche qui va (ré)générer le champ `coords` de la structure
=> Automatiser la maj des Coords lorsque l'adresse d'une structure change

lemarche/templates/dashboard/home.html, lemarche/templates/dashboard/siae_edit_base.html
- Dans la recherche et la fiche structure, on utilise `name_display` pour afficher l'Enseigne (plutôt que la Raison sociale) si elle est renseignée
- Ce travail permet de faire la même chose dans le Tableau de bord de l'utilisateur
=> Afficher l'Enseigne plutôt que la Raison sociale quand elle est disponible

lemarche/templates/siaes/detail.html
On n'a pas besoin de mettre `nofollow` sur nos liens externes.
Au contraire, l'enlever améliore le SEO (search ranking) de ces liens là !
=> Enlever "nofollow" sur nos liens externes

lemarche/templates/layouts/_header.html, lemarche/templates/layouts/base.html
Le bouton "Newsletter achat" dans le header doit apparaitre seulement aux utilisateurs non connectés.
Une fois créé un compte, ils sont maintenant automatiquement inscrits à la liste (cf https://github.com/betagouv/itou-marche/pull/255), donc plus besoin d'afficher le bouton.
=> Cacher le bouton "Newsletter" dans le header si l'utilisateur est connecté

lemarche/tenders/admin.py, lemarche/www/tenders/tasks.py, lemarche/www/tenders/views.py
Admin
- passer quelques champs en readonly
- passer quelques champs en autocomplete pour accélérer le chargement de la page
- ajouter un fieldset pour espacer un peu la page
Fix temporaire des envois
- huey n'arrive pas à faire de jointures/récupération d'infos, donc j'ai désactivé le `task()` + l'envoi d'emails : on les lancera manuellement en ligne de commande en attendant
- fix sur l'email_subject
- fix sur une variable manquante
=> Dépot de besoins 7/X : améliorations dans l'admin + fix temporaire des envois

config/settings/base.py, lemarche/templates/includes/_tracker_tarteaucitron.html, lemarche/utils/settings_context_processors.py
- création d'un Tag Manager container sur Matomo
- ajout du script dans le Frontend
- pas possible de le rajouter à tarteaucitron ? pas dispo. cf https://github.com/AmauriC/tarteaucitron.js > issue 471
=> Stats : ajout du Matomo Tag Manager

lemarche/static/itou_marche/components/_collapse.scss, lemarche/static/itou_marche/itou_marche.scss, lemarche/static/itou_marche/sections/_siae.scss, lemarche/templates/siaes/detail.html, lemarche/templates/tenders/_detail_contact.html, lemarche/templates/tenders/detail.html, lemarche/templates/tenders/list.html, lemarche/templates/tenders/list_item.html, lemarche/tenders/admin.py, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/urls.py, lemarche/www/tenders/views.py
Suite de https://github.com/betagouv/itou-marche/pull/268
Sur les dépôt de besoin, cacher les coordonnées derrière un bouton. Une fois cliqué, le bouton disparaitra au prochain affichage du dépot de besoin.
Avoir des stats d'affichage
=> Dépôt de besoins : stat sur le clic des coordonnées

lemarche/templates/auth/signup_welcome_email_body.txt, lemarche/www/auth/tasks.py, lemarche/www/auth/views.py
A chaque inscription, on envoit un e-mail de bienvenue. Mais il est moche + il fait doublon.
On a mis en place des envois d'e-mails automatisés avec Mailjet (dont un e-mail de bienvenue post-inscription)
=> Supprimer l'envoi de l'e-mail de bienvenue

lemarche/templates/includes/_tracker_itou.html, lemarche/templates/layouts/base.html, lemarche/utils/settings_context_processors.py, lemarche/utils/tracker.py, lemarche/www/pages/urls.py, lemarche/www/pages/views.py
- ne plus envoyer `server_context` & `client_context`
- envoyer les payload du Frontend au Backend (au lieu de les envoyer directement à `TRACKER_HOST`)
- enrichir la whitelist
=> Stats : cleanup

.github/workflows/linting_testing.yml, docker/dev/postgres/Dockerfile, lemarche/siaes/tests.py, lemarche/www/siaes/tests.py
Suite à la PR https://github.com/betagouv/itou-marche/pull/295 (upgrade de Postgres à la version 14), certains tests ne marchent plus. Tentative de réparer en indiquant une version différente dans la config.
=> PostgreSQL 14 : réparer le CI

lemarche/templates/tenders/create.html, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Eviter l'affichage de dépôt de besoin brouillon.
Eviter les fausse joies pour les SIAES.
=> Limiter l'affichage des dépôts de besoins aux ESI

lemarche/utils/tracker.py, lemarche/www/siaes/views.py
Suite de https://github.com/betagouv/itou-marche/pull/300
Stocker, lorsque c'est pertinent (page avec pagination), le nombre de structures trouvées dans un champ "results_count".
Ca nous permettrait de répondre aux questions : 
- combien de résultats cette recherche a-t-elle renvoyée ?
=> Stats : envoyer le 'results_count'

lemarche/api/siaes/filters.py, lemarche/api/siaes/serializers.py, lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py
- Avoir l'info "is_active" dans la liste des Siae
- Pouvoir filter par le champ "is_active"
Retour d'un utilisateur de l'API
=> API : amélioration sur Siae.is_active

lemarche/templates/tenders/_detail_contact.html, lemarche/tenders/models.py
Fix de l'affichage des infos de contacts des dépôts de besoins en fonction de ce que les acheteurs ont sélectionnés.
=> Fix de l'affichage des infos de contacts des dépôts de besoins

lemarche/templates/tenders/_list_item_siae.html, lemarche/templates/tenders/detail.html, lemarche/www/tenders/views.py
Dépôt de besoin : modifier l’intitulé sourcing côté ESI, "sourcing" => "Consultation en vue d’un achat"
Il reste inchangé pour les acheteurs.
=> Dépôt de besoin : modifier l’intitulé sourcing côté ESI

lemarche/templates/layouts/_footer.html, lemarche/templates/tenders/_detail_contact.html, lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/templates/tenders/detail.html
Dépôt de besoin : 
- wording "affichage des coordonnées" pour les vendeurs
- afficher les sauts de ligne de la description
- cacher date d'intervention si vide
- badge : cacher le type de besoin à l'auteur. afficher si "en cours de validation"
=> Dépôt de besoins : fixes

lemarche/templates/siaes/detail.html
On a modifié la couleur du bouton "Afficher les coordonnées" (sur les fiches structures), il doit être vert pour tout les utilisateurs : 
- connectés (déjà fait ici : https://github.com/betagouv/itou-marche/pull/276)
- anonymes (modifs de cette PR)
=> Bouton afficher les coordonnées doit être vert

lemarche/siaes/management/commands/sync_c1_c4.py
Modification de la synchro avec le C1
Lancer aussi un script pour les structures en base qui ont un `contact_email` vide mais un `admin_email` de rempli (sauf celles qui ont un `user_count__gte=1`
=> Synchro C1 : mettre admin_email par défaut pour contact_email

lemarche/templates/pages/home.html, lemarche/www/pages/views.py
Suite de https://github.com/betagouv/itou-marche/pull/330
Car le caching complet de la home provoquait des erreurs : le header ne changeait pas, même si l'utilisateur était connecté (affichait quand même "Connexion" & "Inscription")
Tentative de fix avec le template tag `{% cache %}` (doc [ici](https://docs.djangoproject.com/fr/4.0/topics/cache/#template-fragment-caching)), mais ca relance quand même les requêtes DB de la view, donc inutile..
=> Enlève le caching sur la Home

.gitignore, scripts/import_partners_tender.py
Ajout d'un script pour importer les partenaires qui recevrons les dépôts de besoins.
1- Importer le fichier csv du métier
2- Lancer la commande `./manage.py runscript import_partners_tender`
Attention pour une région donné on set tout les périmètres (region, departements, communes...) pour faire le matching avec les dépôts de besoins qui serait à l'intérieur des périmètres souhaité par les partenaires.
=> Ajout d'un script pour importer les partenaires qui recevrons les dépôts de besoins 

lemarche/static/itou_marche/sections/_siae.scss, lemarche/templates/siaes/detail.html
Limiter le nbr de références client visible sur une fiche commerciale.
Voir ticket Notion https://www.notion.so/Limiter-le-nbr-de-r-f-rences-client-sur-une-fiche-commerciale-dde62465a31b42be8ddf75566ef6b1a9
Parfois les ESI affichent des dizaines de ref client ce qui alourdit la lisibilité de leur fiche commerciale.
Limité à 6 et ajouter la possibilité d’ouvrir comme un collapse afin de toutes les consulter.
=> Ajout d'une zone pliante pour l'affichage des références clients

lemarche/utils/apis/api_mailjet.py, lemarche/utils/apis/api_slack.py
Lors de l'utilisation du Webhook Slack, la réponse est sous la forme de plaintext `ok`, et non d'un JSON : https://api.slack.com/messaging/webhooks#handling_errors
=> Répare les erreurs générées par l'envoi d'un message Slack

lemarche/templates/pages/home.html
Enlevé une ressource pour que le bouton CTA apparaisse en 6e position (2 lignes au lieu de 3)
=> Page d'accueil : monter le bouton "découvrir toutes nos ressources"

lemarche/templates/siaes/_card_search_result.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/utils/export.py, lemarche/www/siaes/forms.py, lemarche/www/siaes/views.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Permettre à l'acheteur de télécharger la liste des structures intéressées par son besoin
- on réutilise la fonctionnalité d'export (déjà utilisé dans la recherche & les listes de favoris)
- différence notable : on souhaite exporter d'avantage de champs (les infos de contact de chaque structure)
=> Dépôt de besoin : téléchargement de la liste des structures intéressées

lemarche/siaes/models.py, lemarche/static/js/perimeters_autocomplete_fields.js, lemarche/templates/layouts/base.html, lemarche/templates/siaes/search_results.html, lemarche/templates/tenders/create_step_general.html, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py, lemarche/www/siaes/views.py
Permettre aux utilisateurs de rechercher dans plusieurs périmètres.
Donner plus de flexibilité et de précision aux utilisateurs dans leurs recherches.
Par l'utilisation d'un "ou", structures dans "Paris" ou "Marseille".
=> Permettre aux utilisateurs de rechercher dans plusieurs périmètres

lemarche/templates/siaes/search_results.html, lemarche/templates/tenders/create_base.html, lemarche/templates/tenders/create_step_confirmation.html, lemarche/templates/tenders/create_step_contact.html, lemarche/templates/tenders/create_step_description.html, lemarche/templates/tenders/create_step_general.html, lemarche/users/admin.py, lemarche/www/auth/forms.py, lemarche/www/tenders/views.py
Homogénéiser le wording pour la publication de besoins
=> Dépôt de besoin : remplacer "déposer" par "publier"

lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py
Change de l'ordre de base des structures renvoyées par la recherche
L'ordre par défaut actuel est "l'aléatoire", mais ca provoque des bugs (structures qui réapparaissent d'une page à une autre)
=> Recherche : ordonner par date de dernière mise à jour

lemarche/templates/tenders/detail_card.html
Avant : Afficher les coordonnées
Après : Je souhaite répondre à ce besoin
Pour avoir des mises en relations plus qualitatives
=> Dépôt de besoin : renommer le bouton CTA pour les structures

lemarche/templates/auth/_login_or_signup_siae_tender_modal.html, lemarche/templates/tenders/detail.html, lemarche/templates/tenders/detail_card.html, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Pour les utilisateurs anonymes (potentiellement des structures ayant reçu le besoin par e-mail)
- leur donner accès à la page détail (sans devoir passer par la page de connexion)
- le bouton "Afficher les coordonnées" ouvre une nouvelle modale freemium (orienté structure intéressée)
=> Dépôt de besoin : afficher une modale freemium pour les utilisateurs non inscrits

lemarche/siaes/models.py, lemarche/static/js/kind_multiselect_field.js, lemarche/static/js/network_multiselect_field.js, lemarche/static/js/perimeter_autocomplete_field.js, lemarche/static/js/presta_type_multiselect_field.js, lemarche/static/js/territory_multiselect_field.js, lemarche/templates/layouts/base.html, lemarche/templates/siaes/search_results.html, lemarche/templates/tenders/create_step_general.html, lemarche/www/dashboard/forms.py, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py
Recherche "full text" basique sur les champs `name`, `brand` & `siret`
- les champs `name` & `brand` utilisent un ~`SearchVector`~ `TrigramSimilarity`
- le champ `siret` est traité séparemment (strip + icontains)
Améliorations possibles (pour une v1.5 ou v2)
- si `SearchVector`, utiliser `config="french_unaccent"` pour ne pas être sensible aux accents
- créer un nouveau champ `search_vector_unaccented` dans le modèle `Siae`, pour faire la recherche sur ce champ directement, et ne pas avoir à générer le search vector à chaque requête. Ce champ devra être mis à jour à chaque fois les champs correspondants de l'instance sont changés (post_save)
- voir comment combiner `TrigramSimiliarity` (pour les champs avec des noms propres ?) et `SearchVector` (pour les champs qui contiennent du …
=> Recherche par nom, enseigne et siret

config/settings/base.py, lemarche/www/tenders/tasks.py
Fix de l'erreur d'envoi d'email des dépôts de besoin à J+30
Problème d'encodage.
=> Fix de l'erreur d'envoi d'email des dépôts de besoin à J+30

lemarche/siaes/admin.py, lemarche/tenders/admin.py, lemarche/users/admin.py
Petites améliorations sur certains champs des modèles `User`, `Siae` & `Tender`
- renommer les champs count pour plus de clareté
- mettre en readonly certains champs qui ne l'étaient pas
=> Admin : améliorations sur les champs count & readonly

lemarche/www/tenders/forms.py, lemarche/www/tenders/views.py
Rendre le champ `Tender.amount` obligatoire dans certains cas
suite de https://github.com/betagouv/itou-marche/pull/422
=> Dépôt de besoin : rendre le champ 'amount' obligatoire (si 'appel d'offre')

config/settings/base.py, lemarche/templates/pages/home.html, lemarche/templates/pages/home_sections/_tenders_studies_case.html, lemarche/templates/siaes/search_results.html, lemarche/templates/tenders/create_base.html, lemarche/templates/tenders/create_step_confirmation.html, lemarche/www/auth/tasks.py, lemarche/www/tenders/forms.py, lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Il faut actuellement être connecté pour pouvoir accéder au formulaire de dépôt de besoin.
Cette PR ouvre les portes à tout le monde.
=> Dépôt de besoin : rendre le formulaire accessible aux utilisateurs anonymes

lemarche/templates/tenders/create_step_contact.html, lemarche/templates/tenders/detail.html, lemarche/www/tenders/forms.py, lemarche/www/tenders/views.py
Suite de #426 
Lors d'un dépôt de besoin, on a besoin de champs particuliers : 
- `User.company_name` est toujours nécessaire (anonyme ou pas)
- `Tender.contact_email` n'est pas obligatoire si l'utilisateur est connecté
=> Dépôt de besoin : améliorations suite à l'accès aux utilisateurs anonymes

lemarche/fixtures/django/12_favorite_lists.json, lemarche/fixtures/django/13_favorite_list_items.json, lemarche/users/admin.py, lemarche/users/models.py, lemarche/users/tests.py
Dans l'admin, sur la liste des utilisateurs, avoir le `tender_count` par utilisateur (comme on a le `siae_count` actuellement)
=> Admin : pour chaque utilisateur, afficher le nombre et lien vers leur dépôt de besoin

lemarche/www/pages/views.py, lemarche/www/tenders/views.py
Gérer un cas particulier où `contact_company_name` n'est pas nécessairement présent
Et dans le cas des dépôts de besoins via le contournement CSRF, gérer la création d'utilisateurs anonymes
=> Dépôt de besoin : fix de certaines erreurs

lemarche/utils/tracker.py
Erreur d'envoi des données vers le tracking
`user.id` est vide si user is anonymous
=> Tracker : fix du contenu envoyé

lemarche/templates/siaes/search_results.html
Encart dans les résultats de recherche, qui s'affiche : 
- entre la 5e et la 6e structure retournée
- seulement sur la première page de résultats
Pour inciter au dépôt de besoin
=> Recherche : afficher un encart pour inciter au dépôt de besoin

lemarche/templates/tenders/_contact_click_confirm_modal.html, lemarche/templates/tenders/detail.html, lemarche/templates/tenders/detail_card.html, lemarche/www/siaes/forms.py, lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Permettre à une structure de confirmer son intérêt pour un besoin, à travers une modale.
v2 de https://github.com/betagouv/itou-marche/pull/447 (simplification et clarification)
Rajouter un peu de friction pour augmenter le nombre de mises en relation "pertinentes".
=> Dépôt de besoin : rajouter une confirmation pour les structures intéressées par un besoin

lemarche/tenders/admin.py
Afficher le champ `Tender.source` dans l'admin
=> Admin : afficher le champ source des dépôts de besoins

lemarche/siaes/factories.py, lemarche/tenders/factories.py, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/dashboard/views.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Suite au hotfix : https://github.com/betagouv/itou-marche/commit/faf73ae9b70b2fe00d985c3885cce267da977601 / #382
- cleanup de `Tender.objects.filter_with_siaes()`
=> Dépôt de besoin : mieux filtrer les besoins affichés aux structures

lemarche/www/tenders/forms.py
Lorsqu'un utilisateur anonyme dépose un besoin, on demandait déjà l'email et l'entreprise en champ obligatoire.
On rajoute maintenant le téléphone (`contact_phone`)
=> Dépôt de besoin : rendre le champ "téléphone" obligatoire pour les utilisateurs anonymes

lemarche/siaes/models.py, lemarche/siaes/tests.py, lemarche/templates/siaes/_detail_partner_cta.html, lemarche/templates/siaes/detail.html
Sur la page détail d'une fiche, modification du CTA qui pointe vers les partenaires : 
- le mettre dans son propre template
- pointer vers un autre lien si la structure est une ESAT ou EA
=> Page détail : changer le CTA vers les partenaires

lemarche/perimeters/models.py, lemarche/siaes/models.py, lemarche/www/siaes/tests.py
Lorsqu'une recherche par ville est effectuée, on renvoye maintenant aussi toutes les structures dans le même département
=> Dépôt de besoin : ajustement sur la recherche par périmètre

lemarche/tenders/admin.py, lemarche/tenders/tests.py, lemarche/www/tenders/tasks.py
Cleanup pour bien séparer `send_tender_emails_to_siaes()` & `send_tender_emails_to_partners()`
=> Dépôt de besoin : séparer l'envoi d'emails aux Structures et aux Partenaires

lemarche/templates/tenders/create_notification_email_admin_body.txt, lemarche/www/tenders/tasks.py
voir titre
Pour pouvoir afficher le titre du besoin dans les emails
=> Dépôt de besoin : envoyer le TENDER_TITLE dans les variables des emails

lemarche/templates/siaes/search_results.html, lemarche/www/siaes/views.py
Afficher 20 ESI sur la carte suite à une recherche.
Pour répondre à la demande des utilisateurs, avoir plus de contenu sans recharge.
=> Afficher 20 ESI sur la carte suite à une recherche

lemarche/templates/tenders/detail_card.html
Permettre saut de ligne dans le champ “Contrainte technique”.
Pour plus de clarté.
=> Permettre saut de ligne dans le champ “Contrainte technique”

lemarche/tenders/models.py, lemarche/tenders/tests.py
Actuellement, on rajoute dans le slug l'entreprise de l'auteur du besoin, mais sans le "slugifier". Donc le champ est malformé si le nom de l'entreprise contient des espaces ou des apostrophes.
=> Dépôt de besoin : améliorer la génération du slug

lemarche/templates/dashboard/home_buyer.html
Changer de version d'icone de téléchargment de remix icon
Pour harmoniser avec le thème et répondre à cette demande UX
https://www.notion.so/Modifier-l-icon-download-2d03a2efc1164ee59f4191c4109badd6 
En remplacant la classe `ri-download-2-line` par `ri-download-line`
=> Remplacer l'icone de téléchargement

lemarche/utils/fields.py, lemarche/www/tenders/forms.py
Dans la dernière étape du dépôt de besoins, désélectionner par défaut la question “Utilité du Marché”.
=> Dépôt de besoins: Désélectionner par défaut la question “Utilité du Marché”

lemarche/sectors/models.py, lemarche/sectors/tests.py
On a récemment renommé les secteurs `Autre` en `Autre (nom du group parent)`, ce qui a "cassé" notre ordering.
(ces secteurs sont affichés dans les formulaires, mais aussi la liste des secteurs affichés par structure)
|Avant|Après|
|---|---|
|![Screenshot from 2022-11-14 15-56-38](https://user-images.githubusercontent.com/7147385/201692146-5075337c-813a-488c-9891-3d674ae19aa6.png)|![Screenshot from 2022-11-14 15-57-11](https://user-images.githubusercontent.com/7147385/201692149-96277c63-1b82-4745-ac6e-31477b98ce15.png)|
=> Améliorer l'affichage des secteurs d'activité

lemarche/users/factories.py, lemarche/www/dashboard/tests.py, lemarche/www/siaes/tests.py, lemarche/www/tenders/tests.py
Inspiré de https://github.com/betagouv/itou-communaute-django/pull/64
1. remplacer `self.client.login(user.email, user.password)` par `self.client.force_login(user)`
2. UserFactory : générer séparément + mettre en cache le password
Pour accélérer les tests
|Env|Avant|Après|
|---|---|---|
|Local|390s|350s|
|Github Action|||
=> Optimisation des tests

lemarche/static/js/perimeters_autocomplete_fields.js, lemarche/templates/siaes/search_results.html
Tout est dans le titre :)
Aussi : sur la page recherche, j'ai enlevé la margin supplémentaire qui était présente entre les 2 rows de filtre (pour gagner un peu de place et éviter au maximum le scroll)
Pour éviter qu'ils se chevauchent
|Avant|Après|
|---|---|
|![Screenshot from 2022-11-23 15-20-33](https://user-images.githubusercontent.com/7147385/203570968-0e7f0549-f92b-449a-92af-3c33fdaa95c4.png)|![Screenshot from 2022-11-23 15-17-45](https://user-images.githubusercontent.com/7147385/203571006-d3c6a4f8-3523-4285-9934-c34b7192530f.png)|
=> Ajout d'une petite margin-bottom sur les badge des périmètres

lemarche/utils/tracker.py, lemarche/www/siaes/views.py
Actuellement les téléchargements renvoie un results_count `None`, car le HttpResponse générées n'ont pas de context data
Fix en passant par la valeur dans les headers
=> Téléchargement x Tracker : fix sur le results_count

lemarche/templates/tenders/detail_card.html, lemarche/users/models.py
voir le titre
Les utilisateurs sans structures ne peuvent actuellement pas voir les coordonnées de l'acheteur. On leur indique ici que ces utilisateurs doivent d'abord se rattacher à leur structure.
=> Dépôt de besoin : afficher les coordonnées : indiquer un message aux utilisateurs sans structures

lemarche/siaes/management/commands/sync_c1_c4.py, lemarche/siaes/management/commands/sync_c2_c4.py, lemarche/tenders/models.py, lemarche/tenders/tests.py
Suite de https://github.com/betagouv/itou-marche/pull/547
- répare le calcul de `deadline_date_is_outdated` : True si deadline_date < today
- répare l'ordre de `order_by_deadline_date` : afficher en premier les besoins non-outdated et avec une deadline_date la plus proche de today
- ajoute des tests
=> Dépôt de besoin : fix sur le tri par deadline

lemarche/www/siaes/views.py
Fix provoqué par cette PR : https://github.com/betagouv/itou-marche/pull/531
Si il n'y a aucun filtre de sélectionné, on renvoie le fichier généré quotidiennement.
Mais un nouveau paramètre `download_source` manquait à la whitelist
=> Téléchargement : fix sur les cas où il faut servir le fichier généré directement

lemarche/templates/tenders/detail_card.html, lemarche/www/tenders/tests.py
Le champ "Contraintes techniques spécifiques" est facultatif.
Sur la page détail du besoin, on cache cette section si le champ est vide.
(mais on l'affiche dans tous les cas si on est dans le formulaire de création/édition)
=> Dépôt de besoin : afficher les contraintes spécifiques seulement si présentes

lemarche/templates/dashboard/home_buyer.html, lemarche/templates/dashboard/home_siae.html, lemarche/templates/tenders/_card_list_item.html, lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/templates/tenders/detail_card.html, lemarche/templates/tenders/list.html, lemarche/tenders/models.py, lemarche/www/dashboard/views.py, lemarche/www/tenders/tests.py
Suite de https://github.com/betagouv/itou-marche/pull/546
v2 de la PR https://github.com/betagouv/itou-marche/pull/471
Si `Tender.deadline_date` est dépassé, mettre un badge pour indiquer "Délai de réponse dépassé" (edit : renommé depuis à "Clôturé")
||Avant|Après|
|---|---|---|
|Tableau de bord|![Screenshot from 2022-12-07 13-06-59](https://user-images.githubusercontent.com/7147385/206175637-6da8e3d5-6365-4948-8b14-1cf36856bae9.png)|![Screenshot from 2022-12-07 13-06-41](https://user-images.githubusercontent.com/7147385/206175691-a0944b8e-f8d3-4ee1-bec9-5857e1a53388.png)|
|Tender list|![Screenshot from 2022-12-07 13-11-23](https://user-images.githubusercontent.com/7147385/206176244-34b83557-c31a-47d2-b4e1-546a5f712f35.png)|![Screenshot from 2022-12-07 …
=> Dépôt de besoin : indiquer si le besoin a une date de réponse dépassée (v2)

docker/dev/django/Dockerfile
Correction des erreurs d'installation poetry via docker
Depuis un moment il m'était impossible d'installer la version docker en local car j'avais de nombreuses erreurs a l'install. En cherchant je me suis rendu compte que mon poetry en local était en 1.2.2 alors que la version du dockerfile était en 1.1.1.
L'installation de poetry du dockerfile n'était pas prise en compte (surement à cause des `"` en ligne  38).
En retirant les `"` elle était bien prise en compte, mais la version 1.1.1 était trop vielle pour certaines dépendances, donc je suis passé à la 1.1.4 (version de rupture d'un truc apparemment)
Malgré ça l'installation se passait mal car poetry nécessitait une version python > 3.10, alors j'ai aussi mis a jour l'image de python du docker. Et maintenant, ça tourne crème 🎯
Par …
=> Mise a jour du dockerfile

lemarche/templates/tenders/_detail_contact.html, lemarche/templates/tenders/detail.html, lemarche/templates/tenders/detail_card.html, lemarche/tenders/factories.py, lemarche/www/tenders/tests.py
- afficher une infobulle pour inciter les structures intéressées à entre en contact avec l'acheteur
- modifier le wording de la section montant : "Budget du client" pour les utilisateurs autres que l'auteur
=> Dépôt de besoin : détail : infobulle pour les contact

lemarche/siaes/models.py, lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/templates/tenders/detail_card.html, lemarche/templates/tenders/list.html, lemarche/tenders/models.py, lemarche/utils/export.py, lemarche/www/tenders/tasks.py
Il y a parfois trop de secteurs d'activité à afficher, ce qui prend beaucoup de place.
Limiter l'affichage à 5 (comme c'est déjà le cas pour les secteurs d'une fiche structure)
--> modifié la méthode `sectors_list_string()` pour pouvoir prendre un paramètre `display_max` (default : 5)
avoir l'option d'afficher la liste complète avec un lien "Voir plus" ?
=> Dépôt de besoin : réduire l'affichage des secteurs d'activité

lemarche/templates/tenders/create_step_description.html
Ajout d'info bulles à l'étape de description de la création de dépôt de besoin.
Améliorer la compréhension des utilisateurs.
=> Ajout d'info bulles à l'étape de description de la création de dépôt de besoin

lemarche/templates/tenders/detail_card.html, lemarche/utils/settings_context_processors.py, lemarche/www/tenders/tests.py
Changer le wording pour le contact des  partenaire (“Contacter Sofiane ou Abdess”)
=> Supportix: Changer le wording pour le contact des  partenaire 

lemarche/api/perimeters/tests.py, lemarche/perimeters/tests.py, lemarche/templates/tenders/detail_card.html, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/siaes/tests.py, lemarche/www/tenders/tasks.py
Suite de https://github.com/betagouv/itou-marche/pull/567
Nouvelle propriété `location_display`
Pour simplifier/homogénéiser la logique d'affichage du champ `location`
=> Dépôt de besoin : homogénéiser l'affichage du champ 'location'

lemarche/templates/tenders/create_notification_email_admin_body.txt, lemarche/www/tenders/tasks.py
Ajout de nouveaux champs dans la notification de création d'un besoin : location, deadline_date, scale_marche_useless & status
=> Dépôt de besoin : améliorer la notification aux admin

lemarche/templates/layouts/_header.html, lemarche/templates/tenders/create_step_general.html, lemarche/www/tenders/forms.py
- renomme 'Sourcing' en 'Sourcing inversé'
- dans le header
- dans le formulaire de dépôt de besoin + help bubble
=> Dépôt de besoin : renommer 'Sourcing' en 'Sourcing inversé'

lemarche/templates/tenders/_detail_contact.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/templates/tenders/detail_card.html, lemarche/tenders/models.py, lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py
Modifications sur l'affichage du champ `Tender.external_link`
- dans le formulaire de dépôt de besoin : modifier le label en "Lien à partager" si ce n'est pas un Appel d'offres
- dans la page détail, modifier le texte à "Lien partagé" si ce n'est pas un Appel d'offres
=> Dépôt de besoin : affichage dynamique d'external_link

lemarche/templates/tenders/detail.html, lemarche/tenders/models.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Suite de la PR #598
Avant : on comptait seulement les `detail_display_date`
Après : on compte les `detail_display_date` ou `email_link_click_date`
=> Dépôt de besoin : élargir la stat du nombre de vues

lemarche/utils/apis/api_mailjet.py, lemarche/www/auth/tasks.py, lemarche/www/dashboard/tasks.py, lemarche/www/tenders/tasks.py
- éviter d'utiliser `EMAIL_SUBJECT_PREFIX` partout, et le rajoute à la source instead
- réparer quelques cas où `if recipient_list:` était manquant
=> Email : léger refactoring de EMAIL_SUBJECT_PREFIX

lemarche/tenders/factories.py, lemarche/www/dashboard/mixins.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Actuellement, si on a le bon lien, tout le monde peut accéder aux besoins en brouillon ou publiés (mais pas encore validés).
Restreindre l'accès des besoins non validés à : 
- leur auteur
- les utilisateurs "Admin"
Nouveau mixin `TenderAuthorOrAdminRequiredIfNotValidatedMixin`
=> Dépôt de besoin : restreindre l'accès aux besoins non validés

lemarche/templates/siaes/search_results.html
Clarifier les onglets, renommer en "Recherche par ..."
|Avant|Après|
|---|---|
|![Screenshot from 2023-01-12 17-28-13](https://user-images.githubusercontent.com/7147385/212124615-e27181a3-a959-45b8-a1c4-3a3e917ed2b1.png)|![Screenshot from 2023-01-12 17-25-58](https://user-images.githubusercontent.com/7147385/212124643-20452031-d833-4f50-8b49-d5d1d38dea95.png)|
=> Renommer les onglets sur la page de résultats

lemarche/www/tenders/urls.py
L'URL de base pour accéder au formulaire de dépôt de besoin est `/besoins/ajouter/`
Mais si l'utilisateur essayait `/besoins/ajouter` il y avait une erreur 500, car c'était le controlleur `TenderDetail` qui était appelé (la vue `tenders:detail`)
Réparé en rajoutant un redirect
=> Dépôt de besoin : fix des erreurs 500 sur l'URL d'ajout

lemarche/www/pages/views.py
Suite à la PR #597
`author` et non `user`
=> Dépôt de besoin : fix d'erreur lors de la création via CSRF

lemarche/templates/layouts/_footer.html, lemarche/templates/layouts/_header.html
Mise à jour des liens communauté 
De communaute.inclusion.beta.gouv.fr vers communaute-experimentation.inclusion.beta.gouv.fr
Préparation de la redirection/fermeture du site WP
Carte notion > https://www.notion.so/Rediriger-tous-les-sites-de-la-PDI-vers-la-nouvelle-interface-C3-f1ccd9f264814ff7bfc029af3aaa7192
=> Mise à jour de l'url communauté

lemarche/utils/apis/api_hubspot.py
Ajout de la propriété incrémental pour les dépôts de besoins dans hubspot.
Pour un meilleur suivi des dépôts de besoins.
=> Ajout de la propriété incrémental pour les dépôts de besoins dans hubspot 

lemarche/templates/tenders/detail.html, lemarche/templates/tenders/detail_card.html, lemarche/users/models.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
réorganisé un peu les template `tenders/detail.html` & `tenders/detail_card.html` 
- pour remonter les informations importantes (contact, CTA)
- pour alléger `detail_card` (qui est aussi utilisé à la dernière étape du dépôt de besoin)
|Etat|Avant|Après|
|---|---|---|
|Anonyme|bouton "Répondre à cette opportunité" dans le corps du besoin|bouton "Répondre à cette opportunité" à droite du besoin|
|Auteur du besoin|bouton "X structures intéressées" dans le corps du besoin|bouton "X structures intéressées" à droite du besoin|
|Structure connectée|bouton "Répondre à cette opportunité" dans le corps du besoin|bouton "Répondre à cette opportunité" à droite du besoin|
|Structure intéressée|section "Contactez le client dès maintenant" dans le corps du besoin|section "Contactez le client dès …
=> Dépôt de besoin : remonter les coordonnées de contact

lemarche/networks/admin.py
Dans Network > Admin : 
- nouveau champ `nb_siaes`
- mettre le `slug` en readonly pour éviter des modifs en cours de route
=> Réseaux (1/3) : afficher dans l'admin le nombre de structures rattachées

lemarche/fixtures/django/10_tenders.json, lemarche/fixtures/django/11_tender_siaes.json, lemarche/siaes/factories.py, lemarche/templates/dashboard/profile_network_detail.html, lemarche/templates/dashboard/profile_network_siae_tender_list.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/www/dashboard/tests.py, lemarche/www/dashboard/urls.py, lemarche/www/dashboard/views.py, lemarche/www/tenders/views.py
Suite de #629
- rendre les stats clickable
- nouvelle page pour voir la liste des demandes reçues / vues / intéressées par la structure
- utiliser htmx pour naviguer entre les différents onglets
=> Réseaux (3b/3) : voir la liste des besoins concernés par chaque structure du réseau

lemarche/siaes/models.py, lemarche/siaes/tests.py, lemarche/templates/dashboard/profile_network_detail.html, lemarche/www/dashboard/views.py
Suite de #633
Nouveau queryset `annotate_with_brand_or_name` pour définir en SQL le nom de la structure à afficher (et sur lequel ordonner) : `brand` ou `name` sinon
- on souhaite souvent afficher l'Enseigne (`brand`) par défaut avant la Raison sociale (`name`)
- viter d'avoir des structures qui apparaissent dans le "désordre"
=> Siae : définir en SQL le nom à afficher

lemarche/siaes/management/commands/sync_c1_c4.py
Le C1 a une nouvelle valeur possible pour `Siae.kind` : `RESERVED`
En creusant un peu, ca correspond à 1 seule structure, qui représente Pole Emploi, bref on n'en a pas besoin.
J'ai modifié la commande `sync_c1_c4` pour les ignorer
=> Répare la synchro du C1 avec le C4

lemarche/templates/pages/company-reference-calculator.html, lemarche/templates/pages/impact-calculator.html, lemarche/templates/siaes/search_results.html
Scroll à la liste de recherche suite à une calibration.
Améliorer l'expérience utilisateur de l'acheteur.
=> Scroll à la liste de recherche suite à une calibration

lemarche/templates/tenders/create_step_general.html
Ajout d'une aide pour le titre de dépôt de besoin à la création.
Pour optimiser l'envoi des dépôts de besoins.
=> Ajout d'une aide pour le titre de dépôt de besoin à la création

lemarche/tenders/admin.py, lemarche/tenders/models.py
- nouvelle méthode `Tender.set_validated()` pour centraliser l'action de "validation"
- ajouter un log au moment de la validation
- indiquer dans l'admin la date de validation (en plus de la section tout en bas)
=> Dépôt de besoin : logger lorsque le besoin est validé

lemarche/tenders/models.py, lemarche/www/dashboard/views.py
Lié à https://github.com/betagouv/itou-marche/pull/633
- il y avait un soucis dans `Tender.objects.filter_with_siaes()`, le modèle était ré-appelé
- optimizations dans `ProfileNetworkSiaeTenderListView`
la vue `ProfileNetworkSiaeTenderListView` était lente
=> Dépôt de besoin : optimisations sur certaines pages / requêtes

lemarche/siaes/models.py, lemarche/siaes/tests.py, lemarche/templates/dashboard/siae_edit_info.html, lemarche/www/dashboard/views.py
- Nouveau queryset `Siae.objects.with_content_filled_stats()` : qui calcule 2 nouveaux champs `content_filled_basic` & `content_filled_full`
- Dans SiaeEditInfoView, récupérer 3 structures "complètes" qui ont été récemment modifiées + les afficher dans un encart
Donner des exemples de structures complètes aux structures
=> Formulaire de modification d'un Siae : ajouter un encart pour s'inspirer des structures complètes

lemarche/templates/dashboard/profile_favorite_list_detail.html
Ajout d'un bouton pour inciter les utilisateurs à déposer un besoin dans la liste de favoris.
Inciter les utilisateurs qui ont des listes de favoris à créer leurs dépôts de besoins.
La version 1 est très basique, juste un bouton.
=> Ajout d'un bouton pour inciter les utilisateurs à déposer un besoin dans la liste de favoris

lemarche/siaes/admin.py, lemarche/templates/dashboard/_siae_tab_content.html, lemarche/templates/dashboard/profile_network_siae_list.html
Suite de #672
- dashboard SIAE : remonte le bouton "Compléter votre fiche"
- Tender admin : ajouter les colonnes "Besoins vues" et "Besoins intéressés" (et renommé "Besoins contactés" en "Besoins reçus")
=> Mise à jour supplémentaire de textes

lemarche/templates/includes/_tracker_tarteaucitron.html, lemarche/users/models.py, lemarche/users/tests.py
Similaire à #642
Suivi le tutoriel [Custom Dimensions](https://matomo.org/faq/reporting-tools/create-track-and-manage-custom-dimensions/) de Matomo pour rajouter les infos
- User kind (champ `kind`)
- User kind detail (nouvelle property `kind_detail_display`)
=> Stats : nouvelles Custom Dimension Matomo

lemarche/templates/tenders/create_step_description.html
Fix du bug du calcul de l'impact social à la création de dépôt de besoin, quand le montant est égale à 750k-1000Ke.
=> Fix du bug du calcul de l'impact social à la création de dépôt de besoin

lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/detail.html, lemarche/www/tenders/tests.py, lemarche/www/tenders/urls.py, lemarche/www/tenders/views.py
Dans la page Dépôt de besoin > Structures intéressées, j'ai renommé l'URL à `/prestataires`
- pour préparer aux modifications qui vont suivre (élargissement de cette pages aux structures concernées aussi - dans une 2e onglet)
- pour homogénéiser l'utilisateur de "prestataires"
=> Dépôt de besoin : renommer l'URL de la liste des structures intéressées

lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/detail.html, lemarche/www/tenders/tests.py
Suite de #680
- utiliser "prestataires" au lieu de "structures"
- Tender detail : continuer de ré-organiser / simplifier en mettant toutes les actions dans la sidebar
=> Dépôt de besoin : cleanup de l'affichage d'un besoin

lemarche/templates/tenders/detail.html
Mettre en avant le bouton CTA "Répondre à cette opportunité"
Une peu comme le bouton "Afficher les coordonnées"
=> Dépôt de besoin : mettre en vert le bouton "Répondre à cette opportunité"

lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/detail.html, lemarche/templates/tenders/list.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/tenders/models.py, lemarche/www/siaes/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/urls.py, lemarche/www/tenders/views.py
Pour un auteur de besoin, lui afficher les stats des prestataires ciblés (en plus des prestataires intéressés)
|Page|Image|
|---|---|
|Liste des besoins|![Screenshot from 2023-03-01 16-28-08](https://user-images.githubusercontent.com/7147385/222185217-757775b3-6d6c-431d-949d-f90251d63e2f.png)|
|Besoin > détail|![Screenshot from 2023-03-01 15-27-30](https://user-images.githubusercontent.com/7147385/222169005-1681bfd2-df59-42ec-a976-78885d934ccf.png)|
|Besoin > détail > liste des prestataires|![Screenshot from 2023-03-01 15-25-02](https://user-images.githubusercontent.com/7147385/222168528-1f229df5-f162-4d55-8b65-46f145e1f31e.png)|
=> Dépôt de besoin : séparer les prestataires ciblés & intéressés

lemarche/www/tenders/tasks.py
Envoyer aussi le mail de matching aux utilisateurs des structures concernés
Une majorité de structures ont le même `contact_email` que le champ `email` de leur utilisateur, donc on n'envoie que aux utilisateurs dont l'e-mail est différent
=> Dépôt de besoin : envoyer le mail aux utilisateurs des structures

lemarche/www/tenders/tasks.py, lemarche/www/tenders/urls.py
Suite aux changements de https://github.com/betagouv/itou-marche/pull/680
- finir de remplacer "structures intéressée" par "prestataire intéressé"
- typo dans l'url de redirection
=> Dépôt de besoin : fix de l'url généré après une mise en relation

lemarche/api/siaes/serializers.py
Dans les serializers du modèles Siae, renvoyer aussi le champ `logo_url`
Demande utilisateur
=> API : ajouter le champ Siae.logo_url

lemarche/www/auth/forms.py
Correction du poste qui n'était pas enregistré à l'inscription pour les acheteurs.
=> Correction du poste qui n'était pas enregistré à l'inscription pour les acheteurs

lemarche/api/tenders/serializers.py, lemarche/api/tenders/tests.py
Suite de #695 
- pouvoir créer des besoins avec les champs `location` (FK) et `sectors` (M2M)
=> API : déposer un besoin avec une localisation et des secteurs

lemarche/templates/siaes/_annuaire_entreprises_button.html, lemarche/templates/siaes/detail.html
- sur chaque fiche structure, ajout d'un bouton vers [L'annuaire des entreprises](https://annuaire-entreprises.data.gouv.fr/)
- nouveau template dédié au bouton, avec le `siret` comme paramètre
Pour fournir d'avantage d'informations légales aux utilisateurs
=> Fiche : nouveau bouton vers Annuaire Entreprises

lemarche/templates/dashboard/home_buyer.html, lemarche/templates/dashboard/profile_network_detail.html, lemarche/templates/dashboard/profile_network_siae_list.html, lemarche/templates/dashboard/profile_network_siae_tender_list.html, lemarche/www/dashboard/tests.py, lemarche/www/dashboard/urls.py, lemarche/www/dashboard/views.py
Suite de #629 
Réorganisé un peu le tableau de bord des partenaires rattachés à un réseau : 
- la page avec la liste des structures a maintenant l'url `reseaux/<str:slug>/prestataires/`
- l'url `reseaux/<str:slug>/` affiche maintenant un tableau de bord du réseau
- remplacé "structures" par "adhérents"
- pour clarifier le parcours utilisateur
- pour préparer l'arrivée d'une nouvelle page
(la section "opportunités commerciales" arrive dans la foulée)
=> Réseau : page d'accueil via son tableau de bord

lemarche/templates/api/home.html, lemarche/templates/includes/_header_notice_migration.html, lemarche/templates/layouts/_footer.html, lemarche/www/pages/urls.py
Suite à #706, il y avait des conflits entre Flatpages & Wagtail
C'est une solution temporaire, en attendant de basculer les pages sous Wagtail ?
=> Flatpages : expliciter les urls pour éviter les conflits avec Wagtail

lemarche/www/dashboard/views.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Dans l'affichage pour l'acheteur des structures intéressées par son besoin, on considère actuellement une structure intéressée comme ayant nécessairement été contactées.
Or il y a parfois des structures qui se montrent intéressées par un besoin dont elles n'ont pas été contactées.
Reste à faire : 
- rajouter une petite infobulle pour indiquer que la structure n'avait pas été ciblée ?
=> Dépôt de besoin : élargir la liste des structures intéressées

lemarche/static/itou_marche/components/_maparea.scss, lemarche/static/itou_marche/sections/_siae.scss, lemarche/templates/includes/_pagination.html, lemarche/templates/pages/company-reference-calculator.html, lemarche/templates/pages/impact-calculator.html, lemarche/templates/siaes/_card_search_result.html, lemarche/templates/siaes/_card_suggest_tender.html, lemarche/templates/siaes/detail.html, lemarche/templates/siaes/search_results.html
- mise à jour de l'ui de la page de résultat de recherche
- renommé "structures" en "prestataires"
Pour réponde a ce ticket https://www.notion.so/Page-recherche-C4-5998f004ef5c419c9c517023c856766d
Templating / DOM
|Avant|Après|
|---|---|
|![Screenshot from 2023-04-03 12-20-58](https://user-images.githubusercontent.com/7147385/229483403-a39aac07-6b29-4787-bab8-b9dee2d8cf96.png)|![Screenshot from 2023-04-03 12-21-25](https://user-images.githubusercontent.com/7147385/229483442-d2d0f4e4-49a8-48d9-a1eb-482e827f85e8.png)|
Je me suis permis en même temps de revoir l'ui de la partie `card_suggest_tender` mais si ça ne convient pas, je le vire.
=> Mise à jour de l'ui de la page de résultat de recherche

lemarche/tenders/admin.py
Dans l'admin des dépôts de besoins, utiliser CKEditorWidget pour les champs `TextField`
Ca s'applique à 2 champs : `description` & `constraints`
=> Dépôt de besoin : afficher un WYSIWYG pour les champs text

lemarche/templates/cms/streams/stats_website.html
Modification du nombre de personnes recrutées et MAJ du mois
Suppression de "6000".
Pour actualiser le chiffre
=> Home : maj du bandeau "impact"

lemarche/templates/dashboard/profile_network_detail.html, lemarche/templates/dashboard/profile_network_tender_list.html, lemarche/templates/tenders/_list_item_network.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/templates/tenders/detail_card.html, lemarche/templates/tenders/list.html, lemarche/tenders/models.py, lemarche/www/dashboard/tests.py, lemarche/www/dashboard/urls.py, lemarche/www/dashboard/views.py, lemarche/www/tenders/views.py
Nouvelle page listant les besoins reçus par les adhérents
- à l'url `/reseaux/<réseau-slug>/besoins`
- nouveau template `_list_item_network.html` pour un affichage spécifique des besoins pour les réseaux
- nouveau queryset `Tender.objects.with_network_siae_stats()` pour calcuer le nombre de structures d'un réseau ciblées par un besoin donné
=> Réseaux : page avec la liste des opportunités commerciales de ses adhérents

lemarche/templates/dashboard/profile_network_detail.html, lemarche/templates/dashboard/profile_network_siae_list.html, lemarche/templates/dashboard/profile_network_siae_tender_list.html, lemarche/templates/dashboard/profile_network_tender_siae_list.html, lemarche/templates/tenders/_list_item_network.html, lemarche/tenders/models.py, lemarche/www/dashboard/tests.py, lemarche/www/dashboard/urls.py, lemarche/www/dashboard/views.py
Suite de #709
Pour une opportunité donnée : 
- afficher la liste des adhérents ~~ciblés~~ notifiés
- afficher la liste des adhérents intéressés
=> Réseaux : page détaillée avec la liste des adhérents notifiés par une opportunité donnée

lemarche/templates/tenders/_detail_contact_click_confirm_modal.html, lemarche/templates/tenders/create_step_description.html, lemarche/templates/tenders/detail.html, lemarche/tenders/models.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Le CTA actuel est "Répondre à cette opportunité"
- si c'est un appel d'offre, alors changer le texte à "Voir cet appel d'offre"
- sinon garder le texte actuel
=> Dépôt de besoin : changer le CTA en fonction du type de besoin

lemarche/templates/dashboard/siae_search_adopt_confirm.html, lemarche/users/models.py, lemarche/utils/emails.py, lemarche/utils/tests_emails.py
Nouvelle méthode `anonymize_email` qui permet d'anonymiser un email : 
- `prenom.nom@test.com` => `p*****.**m@test.com`
- utilisé dans le workflow de rattachement à une structure
=> Pouvoir anonymiser des emails

lemarche/templates/cms/article_list.html, lemarche/templates/cms/article_page.html, lemarche/templates/dashboard/profile_network_siae_tender_list.html, lemarche/templates/dashboard/profile_network_tender_detail.html, lemarche/templates/dashboard/profile_network_tender_siae_list.html, lemarche/templates/dashboard/siae_edit_base.html, lemarche/templates/dashboard/siae_users.html, lemarche/templates/favorites/dashboard_favorite_list_detail.html, lemarche/templates/pages/flatpage_template.html, lemarche/templates/siaes/detail.html, lemarche/templates/tenders/detail.html, lemarche/templates/tenders/list.html, lemarche/templates/tenders/siae_interested_list.html
Lorsque les breadcrumbs sont trop longs, ils sont truncated (défini en dure, ou automatiquement).
Ajout de balises `title` pour éviter au maximum une perte d'information.
=> Accessibilité : ajout des title sur les breadcrumbs

config/settings/base.py, lemarche/templates/tenders/_detail_contact.html, lemarche/templates/tenders/detail.html, lemarche/tenders/models.py, lemarche/utils/settings_context_processors.py, lemarche/www/tenders/tests.py
Inciter les structures à contact Sofiane en mettant son e-mail dans les coordonnées de contact.
- afficher seulement si le moyen de réponse du besoin n'est pas exclusivement "lien externe"
- afficher seulement dans l'encart de contact en haut (pas dans le corps du besoin)
=> Dépôt de besoin : afficher dans certains cas l'email de Sofiane dans les coordonnées de contact

lemarche/siaes/admin.py, lemarche/static/itou_marche/admin.css, lemarche/tenders/admin.py
On a certains champs des modèles `Siae` et `Tender` qui utilisent `CheckboxSelectMultiple`.
Or coté admin le widget par défaut est `SelectMultiple`.
Utilisation de `CheckboxSelectMultiple` pour améliorer le rendu.
Améliorer l'UI des champs à choix multiples.
|Avant|Après|
|---|---|
|![image](https://user-images.githubusercontent.com/7147385/234875521-55d7ebe8-a28a-432a-a9e0-f58c7874a5c3.png)|![image](https://user-images.githubusercontent.com/7147385/234875047-d9d3d3ae-53f2-4943-8fdb-f95975e4bdd0.png)|
=> Admin : améliorer le rendu des CheckboxSelectMultiple

lemarche/api/tenders/serializers.py, lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py, lemarche/www/pages/views.py, lemarche/www/tenders/utils.py, lemarche/www/tenders/views.py
Création d'un utilisateur dans l'appel d'api pour la création du dépôt de besoin .
Pour être iso avec l'interface.
=> Création d'un utilisateur dans l'appel d'api pour la création du dépôt de besoin 

lemarche/www/pages/views.py, lemarche/www/tenders/forms.py, lemarche/www/tenders/utils.py, lemarche/www/tenders/views.py
Suite de #742
Léger cleanup / refactoring du formulaire de dépôt de besoin, avant l'ajout du nouveau champ "questions"
- bougé `create_tender_from_dict()` dans `tenders/utils.py`
- renommé `set_or_create_user` en `get_or_create_user` + bougé dans `tenders/utils.py`
- renommé `AddTenderStepGeneralForm` en `TenderCreateStepGeneralForm` (idem pour les autres steps)
=> Dépôt de besoin : cleanup du formulaire

lemarche/fixtures/django/11_tender_questions.json, lemarche/fixtures/tests.py, lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/create_step_general.html, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/tenders/tests.py
Suite à #742
- afficher les questions dans la page détail des besoins
- nouvelle méthode `Tender.questions_list`
- ajout de tests, fixtures
|Auteur|Prestataire / anonyme|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/de818f62-149d-4f44-b9de-f26da5c2bbc7)|![Screenshot from 2023-05-11 23-28-58](https://github.com/betagouv/itou-marche/assets/7147385/6e83ddee-979a-4d41-93bc-fd1e8c41ca7e)|
=> Dépôt de besoin : afficher les questions dans la page détail d'un besoin

lemarche/www/auth/tests.py, lemarche/www/auth/views.py
Lié à #127
Lorsqu'un acheteur s'inscrit sur la plateforme, le rediriger vers le moteur de recherche.
(il est actuellement redirigé vers la page d'accueil)
=> Inscription : rediriger les acheteurs vers le moteur de recherche

lemarche/static/itou_marche/sections/_siae.scss, lemarche/templates/siaes/_detail_cta.html, lemarche/templates/siaes/_detail_partner_cta.html, lemarche/templates/siaes/detail.html, lemarche/www/siaes/views.py
Clarifier le message.
Homogénéiser le CTA avec celui du dépot de besoin (cf #734)
Reste à faire (autre PR) : 
- déplacer la carte à gauche (dans la fiche de la structure)
- rendre la sidebar sticky (reste en place même en scrollant)
||Avant|Après|
|---|---|---|
|Utilisateur anonyme|![Screenshot from 2023-05-25 10-02-38](https://github.com/betagouv/itou-marche/assets/7147385/cb42ac9a-42ac-4bbd-b240-a9dd78c1dffe)|![Screenshot from 2023-05-25 10-01-56](https://github.com/betagouv/itou-marche/assets/7147385/c53ae013-acd2-485c-832a-7141c644728f)|
=> Fiche structure : modification du CTA

lemarche/templates/tenders/create_base.html, lemarche/templates/tenders/create_step_survey.html
Renommer le bouton d'action de la dernière étape du dépôt de besoin.
Pour donner l'impression à l'utilisateur que le formulaire est moins long.
=> Renommer le bouton d'action de la dernière étape du dépôt de besoin

lemarche/templates/tenders/create_notification_email_admin_body.txt, lemarche/www/tenders/tasks.py
Ajouter le champ "source" dans l'e-mail de notification reçu par les admin après la création d'un besoin.
Cette info est aussi envoyée sur Slack.
=> Dépôt de besoin : ajouter le champ 'source' dans l'e-mail de notification

lemarche/templates/siaes/_card_tender.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/utils/tracker.py, lemarche/www/dashboard/views.py, lemarche/www/siaes/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
L'auteur d'un besoin peut déjà accéder à la liste des prestataires concernés & intéressés.
On ajoute ici une barre de filtre pour lui permettre de réduire sa cible.
Pour l'instant : filtre par "type de structure" & "territoire spécifique".
=> Dépôt de besoin : filtre sur les prestataires concernés & intéressés

lemarche/tenders/admin.py, lemarche/www/pages/views.py, lemarche/www/tenders/views.py
Création d'un hubspot deal à la validation (côté admin) du dépôt de besoin.
Faire gagner du temps au bizdevs.
Création du "deal" à la validation côté admin.
=> Création d'un hubspot deal à la validation (côté admin) du dépôt de besoin

lemarche/templates/tenders/create_step_confirmation.html, lemarche/www/pages/views.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Dépôt de besoin : Fix du bouton sauvegardé en brouillon
La `value` du bouton "sauvegarder comme brouillon" n'était pas assigné.
=> Dépôt de besoin : Fix du bouton sauvegardé en brouillon

lemarche/siaes/management/commands/export_all_siae_to_file.py, lemarche/templates/tenders/siae_interested_list.html, lemarche/www/pages/forms.py, lemarche/www/pages/views.py, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py, lemarche/www/siaes/views.py, lemarche/www/tenders/views.py
Répare 2 bugs : 
- cas où il y avait 0 structures concernées ou intéressées, cela affichait *toutes* les structures
- l'onglet "concerné" était toujours sélectionné (même en allant sur "intéressés"
- renommé `SiaeSearchForm` en `SiaeFilterForm`
- supprimé `TenderSiaeFilterForm` pour utiliser `SiaeFilterForm` à la place
=> Dépôt de besoin : bugfix sur la liste des prestataires concernés & intéressés

lemarche/siaes/models.py, lemarche/templates/siaes/detail.html
Structures : Afficher le nombre d'ETP du C2 si nombre d'ETP pas renseigné.
Exploiter les données du C2 et inciter les structures à mettre à jours leurs données.
Création d'une property dans le modèle `Siae`.
=> Structures : Afficher le nombre d'ETP du C2 si nombre d'ETP pas renseigné 

lemarche/www/tenders/views.py
Lorsqu'un un utilisateur dépose un besoin, la dernière étape du formulaire affiche une localisation vide.
Réparé en définissant un `location_display` custom (comme les autres champs actuels)
=> Dépôt de besoin : formulaire : répare l'affichage de la localisation sur l'aperçu

lemarche/templates/auth/login.html, lemarche/www/auth/tests.py, lemarche/www/auth/views.py
Lors d'un dépôt de besoin anonyme, on créé un compte à l'utilisateur, mais il doit passer par une étape de réinitialisation de son mot de passe.
Si il tente de se connecter sans passer par l'e-mail reçu, il voit un message d'information l'invitant à le réinitialiser.
Ce message était obsolète (ajouté ici https://github.com/betagouv/itou-marche/commit/503ed0271996d0f5f4bc429d6267a2fd569480b8 en 2021)
||Image|
|---|---|
|Avant|![image](https://github.com/betagouv/itou-marche/assets/7147385/068a7c5d-bae5-4499-8318-fb40ed01e81a) |
|Après|![image](https://github.com/betagouv/itou-marche/assets/7147385/72d864c2-a757-4335-94a9-9ca9837261b4)|
=> Connexion : améliorer le message pour les nouveaux utilisateurs sans mot de passe

lemarche/tenders/admin.py, lemarche/tenders/models.py
Dépôt de besoin: fix de l'écrasement des SiaeTenders par l'admin.
`Clear=True` placé dans une méthode `set` du querymanager.
Fix du clear et une condition qui permet de ne plus calculer quand le dépôt de besoin est validé.
=> Dépôt de besoin: fix de l'écrasement des SiaeTenders par l'admin

lemarche/tenders/admin.py, lemarche/tenders/tests.py, lemarche/utils/admin/admin_site.py
Obligé de sauvegarder deux fois un dépôt de besoin pour mettre à jour le nombre de structures.
La sauvegarde de modèle django  se fait en trois étapes (pour simplifier) : 
1. `save_form()`
2. `save_model()`
3. `save_related()`
et l'enregistrement de champs many2many se fait dans `save_related`, d'où l'obligation de sauvegarde de deux fois.
=> Dépôt de besoins : Obligé de sauvegarder deux fois un dépôt de besoin pour mettre à jour le nombre de structures

docker/dev/django/Dockerfile, install-packages.sh
Ajout du driver gecko dans l'environnement Docker
Pour que les tests puissent s'exécuter dans le conteneur.
- installation du paquet Debian `firefox-esr`
- téléchargement du binaire du driver gecko
=> Ajout du driver gecko dans l'image Docker pour les tests selenium

lemarche/siaes/models.py, lemarche/stats/management/commands/export_user_download_list.py, lemarche/stats/management/commands/export_user_search_list.py, lemarche/tenders/admin.py, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/users/admin.py, lemarche/users/models.py, lemarche/users/tests.py
Certains querysets de modèles utilisaient des `annotate` mais il arrivait que les chiffres étaient doublonnés...
- ~Tender : ajout de `distinct=True` lorsqu'ils étaient absents : `with_siae_stats()` & `with_network_stats()`~
- ~Siae : ajout de `distinct=True` lorsqu'ils étaient absents : `with_tender_stats()`~
- User : ajout de nouveaux querysets : `with_siae_stats()`, `with_tender_stats()` & `with_favorite_list_stats()`
- Tender : ne pas utiliser `with_question_stats` avec `with_siae_stats`, ca provoque des doublons : modification dans l'admin
=> Améliorations des requêtes "annotate"

lemarche/fixtures/django/01_siaes.json, lemarche/siaes/models.py, lemarche/siaes/tests.py, lemarche/templates/siaes/search_results.html, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py
Ajout du filtre "Effectifs"
Pour permettre aux acheteurs de limiter les résultats de recherche selon les effectifs des prestataires 
En regardant les champs dans l'ordre : `employees_insertion_count`, `c2_etp_count`, `employees_permanent_count` et `api_entreprise_employees`.
=> Recherche : filtre avancé sur l'effectif

lemarche/templates/tenders/siae_interested_list.html, lemarche/www/tenders/tests.py
Ajout d'un filtre sur l'effectif dans la liste des prestataires ciblés et intéressés
Pour permettre aux acheteurs de filtrer les prestataires intéressés par leur dépôt de besoin. 
Activation du filtre "Effectif" déjà présent dans la recherche des prestataires.
=> Filtre sur l'effectif des prestataires ciblés et intéressés

lemarche/templates/tenders/siae_interested_list.html, lemarche/www/tenders/tests.py
Ajout d'un filtre sur le chiffre d'affaires dans la liste des prestataires ciblés et intéressés
Pour permettre aux acheteurs de filtrer les prestataires intéressés par leur dépôt de besoin.
Activation du filtre "Chiffre d'affaires" déjà présent dans la recherche des prestataires.
=> Filtre sur le chiffre d'affaires des prestataires ciblés et intéressés

lemarche/fixtures/django/20_cms.json, lemarche/templates/cms/article_list.html, lemarche/templates/cms/article_page.html, lemarche/templates/cms/home_page.html, lemarche/templates/layouts/base.html, scripts/create_wagtail_homepage.py
Répare l'affichage des `title` des pages wagtail.
title = le nom des onglets du navigateur, et ce que les moteurs de recherche utilisent pour 
J'en ai profité pour homogénéiser avec https://inclusion.beta.gouv.fr & https://beta.gouv.fr : en utilisant `—`
|Avant|Après|
|---|---|
|Page d'accueil \| - Le marché de l'inclusion|Page d'accueil — Le marché de l'inclusion (v1)<br />Accueil — Le marché de l'inclusion (v2)|
=> Wagtail : répare l'affichage des title

config/settings/base.py, lemarche/static/itou_marche/components/_multiselect.scss, lemarche/templates/siaes/search_results.html, lemarche/templates/siaes/widgets/location_widget.html, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py, lemarche/www/siaes/views.py, lemarche/www/siaes/widgets.py
Activer les filtres avancées uniquement quand l'utilisateur est connecté.
Pour inciter les utilisateurs à se connecter et/ou à s'inscrire. 
- Création d'un customWidget pour gérer le filtre de location et le rendre disable plus facilement.
- Management d'une liste de champs à disable
Reste à faire :
=> Activer les filtres avancées uniquement quand l'utilisateur est connecté

.github/workflows/linting_testing.yml, config/settings/test.py
- Désactivation du système de cache au niveau de l'ORM durant l'exécution des tests
- Parallélisation des tests dans la CI
- Pour éviter les erreurs aléatoires lors des tests notamment lors du comptage de structures.
- Pour réduire le temps d'exécution des tests
- Ajout du backend de cache factice dans le fichier de settings de test.
- Ajout du paramètre `parallel` dans l'action Github
=> Désactivation du cache lors des tests et parallélisation des tests dans la CI

lemarche/templates/layouts/base.html
Suppression du chargement du script javascript pour la popup Mailjet, pour laquel le lien a déjà été supprimé #725 
Pour éviter un chargement inutile d'autant plus que le script est désormais introuvable (404)
Suppression de la balise `<script>`.
=> Suppression du chargement du désormais introuvable script js Mailjet

lemarche/companies/management/commands/set_company_users.py
Grâce à #817, on a maintenant un champ pour indiquer les noms de domaines attendus pour chaque entreprise.
On peut maintenant rattacher les utilisateurs en fonction du nom de domaine de leur e-mail.
=> Entreprise : script pour rattacher les utilisateurs en fonction de leur e-mail

lemarche/templates/dashboard/_ressource_card.html, lemarche/templates/dashboard/home_buyer.html, lemarche/templates/dashboard/home_siae.html
Répare l'affichage des URLs wagtail (dans les tableaux de bord)
J'en ai profité pour refactorer un peu : spécifier les variables en dehors du templace `_ressource_card.html`
=> Tableau de bord : répare les URLs des ressources

lemarche/notes/tests.py, lemarche/siaes/admin.py, lemarche/siaes/models.py
similaire à #845
Côté structures dans l'admin, et grâce au nouveau modèle Note, permettre à un admin de pouvoir indiquer 1 ou plusieurs notes.
=> Structures : pouvoir indiquer des notes dans l'admin

lemarche/notes/tests.py, lemarche/users/admin.py, lemarche/users/models.py
similaire à #845
Côté utilisateurs dans l'admin, et grâce au nouveau modèle Note, permettre à un admin de pouvoir indiquer 1 ou plusieurs notes.
=> Utilisateurs : pouvoir indiquer des notes dans l'admin

config/settings/base.py, lemarche/notes/admin.py, lemarche/siaes/admin.py, lemarche/tenders/admin.py, lemarche/users/admin.py
Utiliser le widget proposé par CKEditor.
Ajout d'une config spécifique aux champs "note"
- pour pouvoir customiser le formattage de la note
- pour ne pas perdre le formattage des notes que l'on importera depuis Hubspot
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/c8a35c62-bfab-45a4-9ab7-0a5d02abe0b6)|![image](https://github.com/betagouv/itou-marche/assets/7147385/ef9ac522-6913-4df9-b635-3c13e47eafc8)|
=> Note : utiliser CKEditor dans l'admin

lemarche/conversations/admin.py, lemarche/static/js/filter_data_message.js, lemarche/utils/fields.py
Affichage de manière lisible des message des conversations.
En manipulant data dans  l'admin en python et JS.
_TODO dans le future : rendre le js plus générique pour mieux adapter dans d'autres cas_
=> Affichage de manière lisible des message des conversations

lemarche/api/emails/views.py, lemarche/utils/emails.py, lemarche/www/conversations/tasks.py
Utilise https://docs.djangoproject.com/en/4.2/topics/email/#send-mail
Permet de résoudre les problèmes d'envois lorsque le body n'est pas du HTML
=> Conversations : utiliser send_mail au lieu de EmailMultiAlternatives

lemarche/conversations/admin.py, lemarche/conversations/models.py, lemarche/conversations/tests.py
- mettre le uuid à gauche du titre
- afficher le nombre de réponses
- chercher par sender_email
- filtre par répondu ou pas
- queryset, tests
||Image|
|---|---|
|Avant|![image](https://github.com/betagouv/itou-marche/assets/7147385/92dc946d-03f9-4417-ab51-664842aad76d)|
|Après|![image](https://github.com/betagouv/itou-marche/assets/7147385/d2fd1788-96e1-4914-a1fb-409fcd9ba783)|
=> Conversations : améliorer l'affichage admin

config/urls.py, lemarche/templates/dashboard/home_buyer.html, lemarche/templates/networks/dashboard_network_detail.html, lemarche/templates/networks/dashboard_network_siae_list.html, lemarche/templates/networks/dashboard_network_siae_tender_list.html, lemarche/templates/networks/dashboard_network_tender_detail.html, lemarche/templates/networks/dashboard_network_tender_list.html, lemarche/templates/networks/dashboard_network_tender_siae_list.html, lemarche/templates/tenders/_list_item_network.html, lemarche/www/dashboard/tests.py, lemarche/www/dashboard/urls.py, lemarche/www/dashboard/views.py, lemarche/www/dashboard_networks/urls.py, lemarche/www/dashboard_networks/views.py
Similaire à #720
Réduire la taille et la complexité du dossier `www/dashboard`, en mettant la logique des réseaux ailleurs
- nouveau dossier `www/dashboard_networks`
- nouveau dossier `templates/networks`
- renommer `ProfileNetwork` en `DashboardNetwork`
=> Refactoring : séparer Dashboard & Networks

lemarche/conversations/models.py, lemarche/siaes/admin.py
Affichage des conversations d'une structure dans l'admin.
=> [ADMIN] Affichage des conversations d'une structure

lemarche/utils/mtcaptcha.py
Modification de la façon de logguer les retours de l'API MTCaptcha.
Les erreurs liées à une mauvaise saisie sont inutilement remontées.
Test sur les code d'erreur de retour de l'API avant de logguer
=> MTCaptcha : tracer l'erreur uniquement si l'utilisateur n'est pas en cause

lemarche/siaes/tests.py
Des tests sur les périmètres géographiques échouent aléatoirement.
Je pense que la SIAEFactory  sans région est générée avec une région au hasard et que celle-ci peut-être "Guadeloupe".
Je pense que ça peut même arriver sur la ville, mais il y a quand même beaucoup moins de chance que ça tombe sur Grenoble.
En définissant une magnifique région pour la `SIAEFactory` qui n'en a pas.
=> Correction du flacky test sur les périmètres géographiques

lemarche/utils/templatetags/siae_sectors_display.py, lemarche/www/siaes/tests.py
Suppression des requêtes supplémentaires pour aller chercher les secteurs des partenaires.
Le nombre de requêtes augmente en lien avec le nombre de résultats affichés.
Modification de la façon d'afficher les secteurs. Le `.values()`  force l'exécution d'une requête au lieu de tirer parti du `prefetch` `sectors` qui est déjà fait sur le modèle `Siae`.
=> Suppression des requêtes N+1 sur la recherche de partenaires

lemarche/siaes/tests.py
Suite de https://github.com/betagouv/itou-marche/pull/869
Des tests sur le périmètre Guadeloupe sautent encore.
Parce que les `FactorySiae`  où le département et le code postal ne sont pas définis peuvent se retrouver dans un périmètre testé (par exemple si le code postal généré est 38000 ou le département est 29).
En définissant des valeurs géographiques cohérentes entre elles.
=> Correction du flacky test sur les périmètres géographiques - Deuxième round

scripts/generate_python_dependencies.sh
Dans mon environment la commande `poetry update` prend beaucoup de temps.
Et c'est une action à effectuer de temps en temps, mais pas nécessairement à chaque ajout / maj de nos dépendances ?
J'ai rendu son lancement optionnel en demandant à l'utilisateur ce qu'il souhaite faire :)
=> Script de maj des dépendances : rendre poetry update optionnel

lemarche/www/dashboard/urls.py, lemarche/www/dashboard/views.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/urls.py, lemarche/www/tenders/views.py
4 views étaient nommées sans le `View` à la fin
- `TenderDetailContactClickStat`
- `SiaeUserRequestConfirm`, `SiaeUserRequestCancel` & `SiaeUserDelete`
=> Refactoring : renommer certaines views

lemarche/templates/layouts/_header.html, lemarche/templates/layouts/_header_nav_primary_items.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/users/models.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Ajout d'un lien au menu d'entête pour accéder directement à la liste des "opportunités". 
À côté du lien, un badge indique le nombre d'opportunités non consultées par un utilisateur de la structure.
Un badge "Nouveau" est aussi ajouté aux items de la liste qui n'ont pas encore été consulté.
Pour fidéliser les acheteurs en augmentant le nombre de réponses aux dépôts de besoin.
En utilisant le champs date de consultation déjà présent sur la table de relation (`SiaeTender`) entre besoin et structure.
=> Ajout d'un lien avec le nombre de demandes reçues à lire

lemarche/tenders/admin.py, lemarche/tenders/models.py, lemarche/tenders/tests.py
Nouveau filtre coté admin, pour trouver les besoins dont aucun montant n'est renseigné (montant renseigné par l'acheteur et montant renseigné par un admin)
=> Dépôt de besoin : Admin : filtre "montant renseigné ?"

lemarche/www/conversations/tasks.py, lemarche/www/conversations/tests.py
Affichage du nom de l'entreprise de l'acheteur dans la signature du premier e-mail au lieu du nom de la structure
=> [Inbound parsing] Affichage du nom de l'entreprise dans la signature du premier e-mail

lemarche/utils/mtcaptcha.py
Filtrer les erreurs liés à un mauvais token saisi.
Il n'est pas intéressant de suivre ces erreurs.
Corriger le test car `fail_codes` est en fait une liste.
=> MTCaptcha : tracer l'erreur uniquement si l'utilisateur n'est pas en cause - Round 2

lemarche/siaes/models.py, lemarche/siaes/tests.py, lemarche/templates/dashboard/siae_edit_info.html, lemarche/templates/siaes/_detail_partner_cta.html, lemarche/templates/siaes/_useful_infos_siae.html, lemarche/templates/siaes/_useful_infos_siae_v2.html
Pour les ESAT/EA/EATT, on ne parle pas de salariés en insertion, mais de travailleurs en situation de handicap
Modifications à 2 endroits
- sur la fiche des structures concernées
- sur le formulaire de modification de sa structure
||Image|
|---|---|
|Fiche structure (EATT)|![image](https://github.com/betagouv/itou-marche/assets/7147385/7b0e6800-7a56-46d0-afd3-3b0720f21adb)|
|Formulaire de modification (EATT)|![image](https://github.com/betagouv/itou-marche/assets/7147385/3bb23b02-927c-4d66-8d50-876f6a934f66)|
=> Fiche structure : changer le label des salariés en insertion pour les ESAT/EA

lemarche/templates/auth/_login_or_signup_siae_tender_modal.html, lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/_detail_contact.html, lemarche/templates/tenders/_detail_contact_click_confirm_modal.html, lemarche/templates/tenders/_detail_cta.html, lemarche/templates/tenders/detail.html, lemarche/utils/mixins.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Permettre aux utilisateurs anonyme de cliquer sur "Accéder aux coordonnées", grâce au `siae_id` dans l'url
- envoyer le paramètre `siae_id` dans les e-mails de mise en relation
- pouvoir cliquer sur "Accéder aux coordonnées" si le paramètre `siae_id` est fourni
- nouveau mixin `LoginRequiredOrSiaeIdParamMixin`
=> Dépôt de besoin : permettre à certains utilisateurs anonyme de se mettre en relation

lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/create_base.html, lemarche/templates/tenders/create_step_confirmation.html
Plusieurs modifications sur la dernière étape du formulaire de dépôt de besoin, pour réduire le taux d'abandon : 
- Dupliquer le CTA "Publier et diffuser" en haut
- Ajouter un message explicatif sur après (tableau de bord)
- Remplacer "C'est tout bon" par "Vous y êtes presque"
- Card header du besoin en rouge 'marché' pour éviter le bleu et confondre avec le CTA
|Avant|Après|
|---|---|
|![Screenshot from 2023-09-14 15-34-47](https://github.com/betagouv/itou-marche/assets/7147385/625a7e45-7822-4e38-bf7f-aaec71c59c80)|![Screenshot from 2023-09-14 15-34-15](https://github.com/betagouv/itou-marche/assets/7147385/19d7e08b-761b-4837-bc5a-25d22c3f1e69)|
=> Dépôt de besoin : réduire le taux d'abandon à la dernière étape (aperçu)

lemarche/www/siaes/views.py
On ne souhaite plus ajouter les acheteurs à des listes Mailjet en fonction de leur recherche.
Cela avait été ajouté dans les PR #316, #658, #675
=> Recherche : enlever les inscriptions des acheteurs aux listes Mailjet

lemarche/templates/tenders/detail.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/www/tenders/views.py
ajout d'une vue pour voir les structures qui ont vu le DB dans le dashboard acheteur
| Avant | Après |
|--------|--------|
| <img width="1368" alt="image" src="https://github.com/betagouv/itou-marche/assets/12339682/e4b91a4b-dc03-4560-bed1-2a581fa4bc3b"> | <img width="1368" alt="image" src="https://github.com/betagouv/itou-marche/assets/12339682/a60eff2d-aa32-4dc7-858e-e0789887f9dc"> |
| <img width="1368" alt="image" src="https://github.com/betagouv/itou-marche/assets/12339682/6e227d08-1f57-4baa-b089-79011e177cc6"> | <img width="1368" alt="image" src="https://github.com/betagouv/itou-marche/assets/12339682/f5aa4fae-3ac5-47d5-b99b-cfa6a8fe6c2c"> |
=> [Dépôt de besoin - dashboard acheteur] ajout d'une vue pour voir les structures qui ont vu le DB

lemarche/templates/layouts/base.html, lemarche/templates/tenders/_detail_cocontracting_click_confirm.html, lemarche/templates/tenders/_detail_cocontracting_click_error.html, lemarche/templates/tenders/_detail_cta_cocontracting.html, lemarche/templates/tenders/cocontracting_notification_email_admin_body.txt, lemarche/templates/tenders/detail.html, lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/urls.py, lemarche/www/tenders/views.py
Ajout d'un encart pour les réponses en co-traitance.
Pour inciter et organiser la co-traitance.
Avec un bouton "¨Être mis en relation" qui notifie l'équipe de la plateforme.
=> [Aperçu du besoin] Ajout du bouton "Répondre en co-traitance"

lemarche/static/itou_marche/sections/_siae.scss, lemarche/templates/siaes/_annuaire_entreprises_button.html, lemarche/templates/siaes/_card_detail.html, lemarche/templates/siaes/_card_suggest_tender.html, lemarche/templates/siaes/_detail_admin_extra_info.html, lemarche/templates/siaes/_detail_partner_cta.html, lemarche/templates/siaes/_useful_infos_siae_v2.html, lemarche/templates/siaes/detail.html
Les admin ont accès à certaines informations.
Mais c'est source de confusion, car ils pensent que ces informations sont disponibles à tous les utilisateurs, alors que cela n'est pas le cas.
- basculé ces info dans un "alert" dédié (à droite)
- rajouté un lien vers la fiche coté admin
- j'en ai profité pour homogénéiser les titres & padding de la page détails..
||Image|
|---|---|
|Avant|![image](https://github.com/betagouv/itou-marche/assets/7147385/0000bf6b-efda-4eed-b7b8-b7816083c2a8)|
|Après|![image](https://github.com/betagouv/itou-marche/assets/7147385/1b5a7274-a9da-43c9-8f36-bb51abd7b147)|
=> [Fiche structure] Faire un encart dédié aux informations admin

lemarche/templates/tenders/create_step_contact.html, lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/utils.py, lemarche/www/tenders/views.py, pyproject.toml
Suppression des champs liés au contact (prénom, nom, e-mail, téléphone) quand l'utilisateur est connecté
Pour rendre le formulaire plus simple à remplir.
Les champs sont automatiquement renseignés avec les informations du contact authentifié.
Étape de contact pour un utilisateur non connecté
Étape de contact pour un utilisateur connecté
=> [Dépôt de besoin] Simplification du formulaire en supprimant les informations de contact pour les utilisateurs connectés

lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Lorsque l'acheteur répond au sondage, on met à jour certains champs, mais il faudrait aussi mettre à jour `siae_transactioned`. (c'est fait manuellement pour l'instant)
=> [Dépôt de besoin] Sondage J+30 : mettre à jour siae_transactioned

config/settings/base.py, lemarche/templates/tenders/_detail_contact.html, lemarche/utils/settings_context_processors.py
Avec l'arrivée des besoins en provenance d'APProch, on souhaite rajouter un message spécifique pour les prestataires.
edit : quid si le besoin a un `contact_full_name` et un `contact_company_name` ?
=> [Dépôt de besoin] Rajouter un message pour les besoins en provenance d'APProch

lemarche/templates/tenders/detail.html, lemarche/tenders/admin.py, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/tenders/tests.py
Sur le modèle `Tender`, il y a une property `siae_detail_display_date_count_all`.
Mais il y avait une incohérence dans l'affichage du détail du besoin.
- renommé la property en `siae_email_link_click_date_or_detail_display_date_count`
- rajouté la stat `siae_email_link_click_or_detail_display_count` dans le calcul de la queryset `with_siae_stats()`
=> [Dépôt de besoin] Ajouter une stat du nombre de structures qui ont cliqué OU vu

config/settings/base.py, lemarche/static/itou_marche/base/_custom.scss, lemarche/templates/tenders/create_step_general.html, lemarche/www/tenders/forms.py
Pouvoir mettre en forme la description sur la première étape du dépôt de besoin.
Pour éviter d'avoir des descriptions difficiles à lire sur lesquelles les modérateurs doivent passer du temps à remettre en forme.
Ajout d'un WYSIWYG sur la description
=> [Dépot de besoin] Possibilité de mettre en forme la description

config/settings/prod.py
Le champs description ne s'affiche pas à cause des règles "CSRF" :
=> [Dépôt de besoin] Déblocages des dépendances de CKEditor

lemarche/siaes/models.py, lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/_list_item_network.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/tenders/models.py
Dans l'aperçu d'un besoin, on affiche actuellement les secteurs d'activités, en les limitant à 5.
On souhaite baisser cette limite à 3 pour que cela prenne un peu moins de place.
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/25afa35e-3a05-4bc9-b193-e05619735d6a)|![image](https://github.com/betagouv/itou-marche/assets/7147385/b952b130-1b14-4fb9-bb05-5ce643fc5594)|
=> [Dépôt de besoin] Afficher seulement 3 secteurs d'activité max

lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/_list_item_network.html, lemarche/templates/tenders/_list_item_siae.html
Suite de #942
Afficher maintenant l'entreprise en premier, la localisation en deuxième (déjà le cas), et les secteurs en troisième.
J'ai effectué ces changements : 
- dans l'aperçu du besoin
- mais aussi dans les listes affichées aux structures et aux réseaux
|Page|Avant|Après|
|---|---|---|
|Besoin|![image](https://github.com/betagouv/itou-marche/assets/7147385/388fa9aa-c55d-4bc4-a9ac-059f7ab7b0b0)|![image](https://github.com/betagouv/itou-marche/assets/7147385/2e16cf4e-5d08-4562-89f1-03997d5e1405)|
|Réseau > opportunités commerciales reçues par mes adhérents|![image](https://github.com/betagouv/itou-marche/assets/7147385/d007d24d-cb7b-43fb-9fa3-8f5945ec8408)|![Screenshot from 2023-10-11 11-42-32](https://github.com/betagouv/itou-marche/assets/7147385/b9e1b039-790b-441c-bdd0-9f5cd81a7c36) …
=> [Dépôt de besoin] Inverser l'affichage des secteurs et de l'entreprise

lemarche/siaes/models.py, lemarche/siaes/tests.py, lemarche/templates/siaes/_card_detail.html, lemarche/users/models.py
Mise à jours de la date de dernière activité des structures.
Pour avoir des dates plus récentes sur l'activité des structures.
| Avant | Après |
|--------|--------|
| <img width="793" alt="image" src="https://github.com/betagouv/itou-marche/assets/12339682/3d4d31c6-d03e-4cce-9ef5-a755e5d9f35b"> | <img width="793" alt="image" src="https://github.com/betagouv/itou-marche/assets/12339682/e7612717-28a4-4da1-b441-b0d89e92cefb"> |
=> Mise à jours de la date de dernière activité des structures 

lemarche/api/tenders/serializers.py, lemarche/www/tenders/utils.py
Fix du bug du nom de l'entreprise à l'ajout d'un dépôt de besoin via l'API.
Dans l'ancien modèle on ne spécifiait pas le nom de l'entreprise dans le dépôt de besoin, du coup on utilisait un `pop` pour extraire la valeur de `contact_company_name`.
Utiliser un `get` à la place.
=> Fix du nom de l'entreprise d'un dépôt de besoin

lemarche/siaes/management/commands/sync_c1_c4.py, lemarche/siaes/management/commands/sync_c2_c4.py, lemarche/stats/models.py, lemarche/tenders/admin.py, lemarche/tenders/models.py
Il restait quelques endroits où l'on utilisait des dates sans TZ.
Cela provoque des warning dans nos logs
```
RuntimeWarning: DateTimeField Tracker.date_created received a naive datetime (2023-07-25 08:59:46.973584) while time zone support is active.
RuntimeWarning: DateTimeField Tender.validated_at received a naive datetime (2023-10-23 09:09:50.640033) while time zone support is active.
```
=> Refactoring : remplacer datetime par timezone

config/settings/base.py, lemarche/labels/admin.py, lemarche/labels/models.py, lemarche/templates/labels/admin_change_form.html
Dans l'admin, pour le modèle `Label`, permettre aux administrateurs d'uploader un logo. On utilise le même fonctionnement que pour les utilisateurs (s3 + dropzone). Dès que l'upload est effectué, le champ "Lien vers le logo" est rempli, et il suffit d'enregistrer pour sauvegarder.
J'ai aussi rajouté une colonne dans la vue "liste", pour indiquer si le label a un logo ou pas.
|Page|Image|
|---|---|
|Admin : détail|![image](https://github.com/betagouv/itou-marche/assets/7147385/f3403fa3-5bd7-4f61-973c-20a9fe81e9ea)|
|Admin : liste|![image](https://github.com/betagouv/itou-marche/assets/7147385/96e1fe2e-7d0e-4fad-8666-6c01d2948dae)|
=> Label : pouvoir uploader un label dans l'admin

lemarche/static/itou_marche/admin.css
Bizarrement, sur mobile il y a une perte d'alignement des champs "checkbox".
Similaire à #736
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/603d84d6-9c99-4b6d-88a4-a611ae4f7798)|![image](https://github.com/betagouv/itou-marche/assets/7147385/5513dc19-d3e8-46ed-999c-75fbe49acfd1)|
=> Admin : améliore le rendu des checkbox sur mobile

lemarche/tenders/admin.py
Dans l'admin coté `Tender`, on avait 2 queryset chained : `Tender.objects.with_siae_stats().with_question_stats()`
Or cela provoque des doublons, et donc fausse les chiffres affichés aux admins...
J'ai enlevé le `with_question_stats()` vu qu'il n'est pas primordial, ni utilisé dans la vue liste, et facilement remplacable dans la vue détail par `tender.questions.count()`
Problème connu : https://code.djangoproject.com/ticket/10060
=> [Dépôt de besoin] Admin : réparer les stats des structures

lemarche/utils/tracker.py
Suppression du message de log
Le message sans intérêt pollue les logs
=> Suppression du message de log sur l'enregistrement du traqueur

lemarche/www/pages/views.py
Dépôt de besoins : Fix des listes de questions avec l'erreur csrf.
=> Dépôt de besoins : Fix des listes de questions avec l'erreur csrf

lemarche/utils/export.py
Suite de #955
Dans l'export csv / excel des structures, on rajoute la property `kind_parent`
=> Export : ajouter la property Siae.kind_parent

lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/tenders/tasks.py
Dans certains mails transactionnels, indiquer le montant du besoin : 
- nouvelle property `amount_display` + ajout de tests
- passer cette info via la variable `TENDER_AMOUNT`
Modifier les templates d'e-mails correspondants pour faire apparaître le montant
=> [Dépôt de besoin] Dans les e-mails aux prestataires, envoyer aussi le montant

lemarche/www/dashboard_siaes/views.py
A la fin d'un rattachement, on propose à l'utilisateur de contacter le support si il y a un soucis.
Mais ce n'était pas le bon lien..
=> [Structures] Rattachement : répare le lien vers les contact à la fin du workflow

lemarche/siaes/models.py, lemarche/www/siaes/forms.py, lemarche/www/siaes/views.py, lemarche/www/tenders/views.py
Fix du bug de téléchargement des structures qui ont vu des dépôts de besoins.
Avant il n'y avait que deux status pris en charge les all et les "Interested", la gestion des "viewed" n'était pas pris en charge.
Gestion du statut "VIEWED" et factorisation de code pour le téléchargement et la vue d'affichage.
=> Fix du bug de téléchargement des structures qui ont vu des dépôts de besoins

lemarche/siaes/models.py, lemarche/www/tenders/tests.py
Fix du bug de périmètre et France entière.
Quand des périmètres sont sélectionnés dans le back-office avec l'option France entière qui est sélectionné, l'option France entière n'était pas prise en compte.
Ajout d'une nouvelle condition
Ajouter des tests pour détecter le soucis en amont.
=> [Dépôt de besoin] Fix du bug de périmètre et France entière

lemarche/templates/auth/signup.html, lemarche/www/auth/forms.py, lemarche/www/auth/tests.py
Suite de #983 
Rajout du champ `buyer_kind_detail` dans le formulaire d'inscription.
Affiché seulement aux acheteurs
=> [Utilisateurs] Inscription : demander aux acheteurs leur type d'organisation

lemarche/templates/dashboard/siae_search_adopt_confirm.html, lemarche/www/dashboard_siaes/views.py
Demande de rattachement lorsqu'un utilisateur est déjà rattaché, rajouter le message de contacter le support si cette personne ne fait plus partie de la structure.
La mention de contacter le support était trop loin dans le workflow, c'est mieux de la mettre avant de faire l'action de demande de rattachement.
=> [Structures] Rattachement : déplacer la mention de contacter le support

config/settings/base.py, env.default.sh, lemarche/siaes/management/commands/sync_c1_c4.py, lemarche/utils/apis/api_emplois_inclusion.py
Ne plus se connecter directement à leur base de données, mais passer via leur API.
- PR coté emplois : https://github.com/gip-inclusion/les-emplois/pull/3322
- documentation du nouvel endpoint (qui reprend les champs que nous récupérions) : https://emplois.inclusion.beta.gouv.fr/api/v1/redoc/#tag/marche
J'en ai profité pour créer un fichier `api_emplois_inclusion.py` :)
=> [Structures] Réparer la synchro avec les emplois

clevercloud/cron.json, clevercloud/siaes_sync_with_emplois_inclusion.sh, lemarche/siaes/management/commands/sync_with_emplois_inclusion.py
Suite de #993
- remplacé au maximum "C1" par "Les emplois"
- le nouveau script s'appelle `sync_with_emplois_inclusion`
=> [Tech] Renommer le script de synchro avec le C1

lemarche/siaes/admin.py, lemarche/siaes/management/commands/update_siae_count_fields.py, lemarche/siaes/models.py, lemarche/tenders/admin.py, lemarche/tenders/management/commands/update_tender_count_fields.py, lemarche/tenders/models.py, lemarche/users/admin.py, lemarche/users/models.py
J'ai essayé de centraliser la liste des champs en lecture seule, à la manière de ce que l'on fait déjà pour le modèle `Siae`
- Siae : en rajoutant d'autres champs readonly
- Tender : en répliquant cette logique
- User : idem
=> [Tech] Léger refactoring des champs en lecture seule dans l'admin

lemarche/tenders/admin.py
Suite de #999
Cette PR a introduit un nouveau champ `distance_location` et quelques mini règles pour que le ciblage se passe bien.
J'ai rajouté ces règles dans le clean du formulaire admin, pour renvoyer des `ValidationError` si jamais elle n'étaient pas respectées
=> [Dépôt de besoin] Admin : ajout de validation sur les règles de ciblage par km

lemarche/templates/tenders/create_base.html
Inversement de l'ordre des boutons dans le DOM. Lors d'un appuie sur la touche "Entrée" dans un champs texte, le formulaire est envoyé comme le premier bouton de type "submit" trouvé.
Dans notre cas, il s'agissait du bouton "Étape précédente", et sans sauvegarde..
=> [Dépôt de besoin] Inversement de l'ordre des boutons pour gérer l'appui de la touche Entrée

lemarche/siaes/management/commands/sync_c2_c4.py, lemarche/siaes/management/commands/sync_with_emplois_inclusion.py, lemarche/siaes/management/commands/update_siae_super_badge_field.py
Dans la PR #1012 on a changé le canal par défaut pour les notifications Slack, vers #tech-notifications
Mais certains résultats de commandes sont intéressants à avoir dans #support
=> [Tech] Envoyer certaines notifications Slack vers le canal #support

lemarche/api/tenders/serializers.py
Permettre de renseigner le montant exact sur l'api.
Faire gagner du temps aux bizdevs dans la conciergerie des DDB.
Ajouter le champs montant exact dans le Serializer des Tenders, et au niveau n8n ajout du champs `amount_exact` dans le call d'api.
=> Permettre de renseigner le montant exact sur l'api des dépôt de besoins

lemarche/api/tenders/serializers.py, lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py, lemarche/www/tenders/utils.py
Grâce à #1002 on a maintenant un type d'utilisateur "Particulier"
On souhaite donc labelliser correctement les nouveaux utilisateurs créés à partir des besoins Tally
- Particuliers
- Acheteurs > Association
- Acheteurs
Depuis Tally on reçoit 2 informations : `contact_kind` & `contact_buyer_kind_detail`
Il faut les mapper aux bons utilisateurs
Script à lancer pour labelliser les utilisateurs passés
```
from lemarche.users.models import User
User.objects.filter(company_name="Particulier").count()
User.objects.filter(company_name="Particulier").update(kind=User.KIND_INDIVIDUAL)
```
=> [Utilisateurs] Rattacher correctement les utilisateurs provenant de Tally

lemarche/www/auth/forms.py, lemarche/www/auth/tests.py
Répare un souci introduit par #987
La valeur "Grand groupe" était toujours sélectionnée par défaut, même pour les utilisateurs non-acheteurs (comme les particuliers)
=> [Utilisateurs] Inscription : évite la valeur par défaut pour buyer_kind_detail

clevercloud/cron.json, lemarche/tenders/management/commands/send_validated_tenders.py
Suite à #998
Les besoins n'étaient pas nécessairement envoyés aux horaires souhaités : 
- à 10h au lieu de 9hX
- car le serveur tourne à l'heure UTC (1h de moins)
- à 18h50 au lieu de 16h55 max : 
- UTC
- le cron tourne sur quasi toute l'heure de fin (incluse)
j'ai donc modifié `*/5 9-17 * * 1-5` en `*/5 8-15 * * 1-5`
=> [Dépôt de besoin] Répare les horaires du cron d'envoi des besoins validés

lemarche/templates/tenders/detail.html, lemarche/www/tenders/tasks.py
- changer le `from_email` des e-mails envoyés aux prestataires concernés (et aux partenaires)
- remplacer "Raphael" par "Pauline"
- changer l'e-mail affiché sur un des encarts de la page détail des besoins
=> Dépôt de besoins : envoyer les e-mails aux prestataires (et aux partenaires) à partir d'une autre adresse mail

lemarche/siaes/admin.py
Correction du formulaire d'édition des structures de l'admin.
Le formulaire d’édition des structures dans l'admin était tronqué lorsqu'on passait par le formulaire d'ajout d'une structure au préalable.
En forçant l'affectation des fieldsets d'édition dans ``get_fieldsets``.  Ainsi, en ajout, les fieldsets réduits sont bien pris en compte et en édition, tous les fieldsets sont bien configurés aussi, et peu importe l'ordre de navigation.
=> [Admin] Correction du formulaire d'édition des structures qui est parfois tronqué

lemarche/siaes/management/commands/sync_with_emplois_inclusion.py, lemarche/stats/management/commands/import_users_for_stats.py, lemarche/utils/apis/api_emplois_inclusion.py
Lorsqu'il y a une erreur de synchro, les détails sont mal remontés sur Slack.
J'ai aussi rajouté un petit sleep pour ne pas trop forcer l'API des emplois
Lié aux changements dans #993
=> fix(API): Réparer le script de synchro avec les emplois

lemarche/tenders/admin.py
Dépôt de besoins filtre par type du client (structures, partenaires, particuliers) dans l'admin.
Pour simplifier la vie des bizdevs.
Admin > Besoins
- ajout d'un filtre à droite
- ajout d'une colonne type d'acheteur
- ajout de l'info dans la page détail
=> feat(dépôt de besoins) : Admin : filtre par type du client

lemarche/cms/models.py, lemarche/tenders/tests.py
Correction d'une erreur de chargement des pages statiques dans l'admin Wagtail.
Le chargement du menu "Ressources" dans la sidebar et l'édition des pages statiques produisent une erreur 500.
Il semblerait que la modification du constructeur créé une boucle infinie. 
J'ai surchargé la méthode `get_template` plutôt que de modifier le constructeur.
=> [Wagtail] Correction du chargement des pages statiques

config/settings/base.py, lemarche/utils/apis/api_brevo.py
Lié à #1028
La configuration actuelle fonctionne mais ne permettait pas d'envoyer des e-mails transactionnels à la manière de Mailjet.
J'ai aussi modifié le DEFAULT_FROM_EMAIL & DEFAULT_FROM_NAME
=> Emails : finaliser la configuration d'envoi d'-mails transactionnels avec Brevo

lemarche/tenders/management/commands/send_validated_tenders.py, lemarche/tenders/migrations/0066_tender_limit_nb_siae_interested_and_more.py, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/utils/constants.py
Suite / fix de #1025
Le mode batch engendré un appel à la tâche `send_validated_tender(tender)`, qui (r)envoyait des e-mails à l'auteur du besoin ainsi qu'aux partenaires.
J'ai donc séparé entre 
- les nouveaux besoins à envoyer
- les besoins déjà envoyés qui sont à renvoyer en mode batch
=> Dépôt de besoin : Répare le trop grand nombre d'envoi d'e-mails en mode batch

lemarche/tenders/management/commands/send_validated_tenders.py, lemarche/www/tenders/tasks.py
Suite et fin de #1046
Lorsque j'ai séparé validation et envoi par batch, j'ai oublié de mettre à jour le champ `last_sent_at`
Ce qui provoquait l'envoi "batch" toutes les 5 minutes au lieu de tous les jours
=> Dépôt de besoin : fini de réparer l'envoi par batch

lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/_detail_cta.html, lemarche/templates/tenders/_detail_sidebar.html, lemarche/templates/tenders/_detail_success_contact.html, lemarche/templates/tenders/detail.html, lemarche/www/tenders/tests.py
Pour simplifier le template `tenders/detail.html` : 
- j'ai créé un nouveau sous-template `tenders/_detail_sidebar.html` pour y mettre la sidebar
- dans ce nouveau template, j'ai aussi tenté de réorganiser un peu la logique entre anonymous et non anonymous tenders
- ajout de tests sur les templates "response_is_anonymous"
=> Dépôt de besoin : Détail : Template dédié à la sidebar

lemarche/templates/tenders/_detail_sidebar.html
Lorsqu'un besoin est anonyme, il y a tout de même les boutons CTA pour permettre aux prestataires de se montrer intéressé (ou pas).
Mais il manquait un `siae_id` si l'utilisateur venait de son e-mail.
=> Dépôt de besoin : Détail : fix un bug sur les besoins anonymes

lemarche/templates/tenders/_detail_cta_not_interested.html, lemarche/templates/tenders/_detail_not_interested_click_confirm_modal.html, lemarche/templates/tenders/_detail_not_interested_click_error.html, lemarche/templates/tenders/detail.html, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Comportement similaire à celui déjà présent qui permet aux prestataires de montrer leur intérêt.
Mais cette fois-ci pour l'action 'pas intéressé' - Suite à #1038
Pour rajouter une étape de "confirmation"
Pour homogénéiser avec
=> Dépôt de besoin : Détail : basculer l'action 'pas intéressé' dans une modale

lemarche/templates/tenders/_detail_cocontracting_click_confirm.html, lemarche/templates/tenders/_detail_cta_cocontracting.html, lemarche/templates/tenders/_detail_cta_not_interested.html, lemarche/templates/tenders/_detail_sidebar.html, lemarche/tenders/models.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Similaire à #1050, mais cette fois-ci pour la co-traitance
Complexité : un prestataire peut à la fois montrer son intérêt pour le besoin + pour la co-traitance
=> Dépôt de besoin : Détail : cacher les CTA en fonction de l'intérêt en co-traitance du prestataire

lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py
Grâce à #1058
- on rempli le champ `partner_approch_id` si c'est un nouveau besoin
- ne ne recréé pas de besoin si l'id existe déjà
=> Dépôt de besoin x APProch : stocker l'ID lorsqu'un nouveau besoin est reçu via l'API

clevercloud/tenders_send_author_transactioned_question_emails.sh, lemarche/tenders/management/commands/send_author_transactioned_question_emails.py, lemarche/tenders/models.py, lemarche/www/tenders/tasks.py
Il existe déjà un e-mail automatique envoyé aux auteurs de besoins à J+7 pour savoir si ils ont transactionné.
Cette PR rajoute une option de relance + maj du cron
J'en ai profité pour cleaner un peu le fonctionnement actuel.
Pour recueillir d'avantage de réponses !
=> Dépôt de besoin : envoi sondage transaction : mise en place de relances

lemarche/tenders/models.py, lemarche/www/tenders/views.py
Conservation des coordonnées du contact dans les données d'étapes.
Afin de mieux comprendre les dépôts de besoin abandonnés.
En retirant le système de masquage des champs sensibles.
=> [Dépôt de besoin] Conserver les coordonnées dans les données d'étape.

lemarche/siaes/models.py, lemarche/templates/tenders/_detail_side_infos_author.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/www/siaes/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Actuellement, dans la page des prestataires intéressés, on ne fait pas le bon filtrage. On recalcule les prestataires qui "étaient initialement concernés", au lieu de filtrer en fonction de nos stats TenderSiae.
Du coup certains prestataires qui avaient ou qui s'étaient montrés intéressés, sans pour autant avoir été ciblés au début, n'apparaissaient pas dans les listes :exploding_head: 
J'ai rajouté des tests
=> Dépôt de besoin : prestataires intéressés : répare le filtrage

lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py
Suite de #1069
Lorsqu'un besoin existant est reçu, il existe un cas particulier où l'on souhaite tout de même le recréer : si le champ `kind a changé`.
Faire un "lien" avec le besoin précédent ?
=> Dépôt de besoin x APProch : si besoin existant, mais kind a changé, alors en re-créer un

config/settings/base.py, lemarche/api/emails/views.py, lemarche/siaes/models.py
- retiré l'endpoint "inbound parsing" de la doc
- ajout de type hint sur certaines propriétés (enlève 2 warnings)
- ajout d'enums (mais pas réussi à enlever le dernier warning)
```
Warning [SiaeViewSet > SiaeListSerializer]: unable to resolve type hint for function "kind_parent". Consider using a type hint or @extend_schema_field. Defaulting to string.
Warning [SiaeViewSet > SiaeDetailSerializer]: unable to resolve type hint for function "kind_parent". Consider using a type hint or @extend_schema_field. Defaulting to string.
Warning: enum naming encountered a non-optimally resolvable collision for fields named "kind". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "Kind61cEnum". add an entry to …
```
=> [API] Cleanup (retirer inbound parsing de la doc)

lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py, lemarche/api/urls.py
Autre demande d'API Entreprise (après la #955)
Avoir une URL pour récupérer les structures par siren (on avait déjà par siret)
- `/siae/siren/<siren>`
- siren = 9 caractères, siret = 13
=> feat(api) Pouvoir chercher les structures par SIREN

lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py, lemarche/api/utils.py
Suite de #1076
Dans l'endpoint API `/siae/kinds`, ajout de la clé `parent`
=> api(siae): ajoute le parent dans l'endpoint siae kinds

lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py
Suite à #1074 
Améliorations sur l'endpoint `/siae/siret/<siret>`
- renvoyer une liste dans tous les cas
- vérifications du format du siret
=> refactor(api): Mieux renvoyer les structures dans l'endpoint par siret

lemarche/api/tenders/serializers.py, lemarche/api/tenders/tests.py
Ajout de champs (optionnel) dans le but d'optimiser le travail des bizdevs : 
- `include_country_area` : Inclure les structures qui ont comme périmètre d'intervention 'France entière'
- `distance_location` : Distance en kilomètres autour du lieu d'intervention
optimiser le travail des bizdevs
=> Dépôts de besoins (API) : Ajout de champs dans le but d'optimiser le travail des bizdevs

lemarche/static/itou_marche/sections/_siae.scss, lemarche/static/js/utils.js, lemarche/templates/dashboard/_siae_tab_content.html, lemarche/templates/dashboard/home_siae.html, lemarche/templates/siaes/_card_detail.html, lemarche/templates/siaes/_card_search_result.html, lemarche/templates/siaes/_card_tender.html
[Affichage des Siaes] Ajout du badge visuel des super esi.
Mettre en avant les esi actives sur la plateforme.
Favoris : 
Détail des fiches : 
Liste dans le dépôt de besoins:
Dans la liste de recherches:
=> [Affichage des Siaes] Ajout du badge visuel des super esi

lemarche/static/itou_marche/base/_custom.scss, lemarche/static/itou_marche/base/_variables.scss, lemarche/static/itou_marche/itou_marche.scss, lemarche/static/itou_marche/sections/_tender.scss, lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/_list_item_detail_row.html, lemarche/templates/tenders/_list_item_siae.html, lemarche/www/tenders/tests.py
Refonte ergonomique de la liste des opportunités
Permettre aux ESI de différencier les types de demandes client par un code couleur afin de gagner en lisibilité.
- Le badge “Type de besoin” passe à gauche
- Le badge “Type de besoin” a une couleur associée
- La ligne en bas de la carte prend la couleur du “Type de besoin”
- La ligne en bas de la carte se réduit en épaisseur
- Le montant du besoin passe en gras
- Le montant du besoin = “Montant exact” si non “Fourchette” (Si l’acheteur le partage)
- Le tag “Nouveau” passe à droite de la carte
=> Refonte ergonomique de la liste des opportunités

lemarche/static/js/utils.js
Correction du click sur les cartes des structures.
Le click ne fonctionne plus après une recherche depuis la [PR1083](https://github.com/gip-inclusion/le-marche/pull/1083)
Correction en relançant l'initialisation des événements Javascript après le chargement des résultats par HTMX.
=> fix(search) : Correction du click sur les structures arpès une recherche par mot clé

.github/workflows/semantic-pr.yml
Suite à #1077
https://github.com/amannn/action-semantic-pull-request
Github Action pour vérifier que le nommage des PR respecte [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
=> ci: ajout d'une Github Action qui vérifie le nommage des PR (respect de la norme "conventional commits")

lemarche/tenders/admin.py, lemarche/tenders/models.py
Utiliser la fonctionnalité `collapse` des fieldset, pour cacher certaines sections de l'admin.
- sections concernées : APProch, Stats, Si importé, Dates
- j'ai aussi déplacé le champ "Bénéfices du marché" dans Stats
- et caché 2 stats "Structures cliquées" et "Structures vues" car demandé
Pour réduire la taille
|Avant|Après|
|---|---|
|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/21530793-cf29-4f1f-9754-da87b2faa29d)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/95af23c9-2605-406b-b655-7fc6bc9477bf)|
=> feat(tender): Admin : réduire la taille de la page grâce aux collapse

lemarche/static/js/utils.js, lemarche/templates/dashboard/home_siae.html
Fix du bug d'affichage des tabs pour compléter les données des siaes.
Mauvais selecteur de la fonction js qui active les onglets de modification des données des structures.
=> fix(dashboard_siae): fix du bug d'affichage des tabs pour compléter les données des siaes

lemarche/tenders/admin.py, lemarche/tenders/models.py
Admin :  Réorganisation des colonnes de la liste des dépôts de besoins
Pour la rendre plus lisible et plus facile à utiliser.
- Réduction du nombre de colonnes
- Réduction des entêtes de colonnes
**Avant**
**Après**
=> refactor(tender): Réorganisation des colonnes de la liste des dépôts de besoins dans l'admin

lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/tenders/utils.py
Nouveau utils `duplicate(tender)`
Ajout de test
Parfois demandé par un admin. En attendant de rajouter un bouton
=> feat(besoins): méthode pour dupliquer un besoin

lemarche/tenders/admin.py
Suite à #1091, on avait fait le ménage et gardé seulement `S. cliquées ou vues`. Or on a une limitation sur le lien qui mène à la liste effective de ces structures.
Du coup j'ai revert : 
- ré-ajouté `S. cliquées`
- ré-ajouté `S. vues`
- affiche `S. cliquées ou vues` sans lien
=> refactor(tender): Admin : ré-ajoute les stats du nombre de structures qui ont vues et qui ont cliquées

lemarche/siaes/models.py, lemarche/siaes/tasks.py, lemarche/templates/siaes/_detail_admin_extra_info.html, lemarche/templates/tenders/_detail_admin_extra_info.html, lemarche/tenders/models.py, lemarche/utils/export.py, lemarche/utils/urls.py, lemarche/www/tenders/tasks.py
- renommé `get_share_url_object` en `get_object_share_url`
- renommé `get_admin_url_object` en `get_object_admin_url`
- Tender : ajouté la property `get_admin_url` + utilisé dans un template
- Siae : ajouté la property `get_admin_url` + utilisé dans un template
=> refactor: améliore un peu la génération des URL absolute & admin

lemarche/templates/tenders/_list_item_siae.html, lemarche/users/models.py, lemarche/www/tenders/tests.py
Suppression de l'affichage du badge "Nouveau" sur les dépôts de besoins clôturés et ajustement du compteur d'entête.
Pour que le badge "Nouveau" soit cohérent et attire l’œil sur des besoins encore en cours.
=> fix(tender): Suppression de l'affichage du badge "Nouveau" sur les DDB clôturés

lemarche/templates/admin/includes/fieldset.html, lemarche/tenders/admin.py
Rediriger vers la section structures après la validation des DDB
| 1 | 2 |
|--------|--------|
| <img width="1124" alt="image" src="https://github.com/gip-inclusion/le-marche/assets/12339682/cef9888c-962f-43a5-835d-9761c909b68c"> | <img width="1124" alt="image" src="https://github.com/gip-inclusion/le-marche/assets/12339682/76906d09-83f2-4f3d-90f2-69062eb7fdf4"> |
=> feat(admin_tenders): Rediriger vers la section structures après la validation des DDB

lemarche/siaes/management/commands/sync_with_emplois_inclusion.py
On se rend compte que le champ `Siae.is_delisted` (utile pour cacher une structure active des résultats), est écrasé à chaque synchro avec les emplois.
Tentative de réparation : en l'enlevant complètement de la synchro avec les emplois
- is_active est géré par les emplois / ASP
- is_delisted est géré par le marché
- is_live reste un combo des 2
=> fix(SIAE): Evite que le champ is_delisted soit écrasé à chaque synchro avec les emplois

lemarche/siaes/models.py, lemarche/siaes/tests.py
On a déjà le queryset `is_live()` (active + pas délistée)
Mais il serait utile d'avoir cette info au niveau objet, par exemple pour #1106
J'ai ajouté un test
=> feat(SIAE): nouvelle property is_live

lemarche/tenders/admin.py, lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/tenders/utils.py
Suite à #1090 il y avait une coquille dans le filtre
- réparé dans l'admin
- bougé la méthode dans un nouveau `tenders/utils.py`
- ajouté des tests
=> fix(Admin): Besoins : répare le filtre par montant exact

lemarche/templates/tenders/list.html, lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Ajout d'un filtre par type de besoin sur la liste des opportunités
Pour permettre aux ESI de prioriser comme elles le souhaitent.
Une liste déroulante qui submit au changement.
La carte prévoyait de mettre des compteurs dans la liste déroulante pour indiquer le nombre de nouveaux, je pense que ça peut faire l'objet d'autre PR.
=> feat(Besoins): Ajout d'un filtre par type de besoin

lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/www/dashboard/views.py
Réordonner les DDB sur page dashboard des SIAEs.
Mettre en avant les derniers DDB publié.
=> feat(Dashboard SIAE): Réordonner les besoins (derniers publiés en premier)

lemarche/sectors/admin.py, lemarche/sectors/factories.py, lemarche/sectors/models.py, lemarche/sectors/tests.py
Mini ajout dans la page admin des secteurs : 
- on avait déjà le nombre de structures rattachés
- j'ai ajouté le nombre de besoins concernés
Demande admin d'avoir les top secteurs
=> feat(Admin): Secteurs : afficher le nombre de besoins concernés

lemarche/templates/tenders/detail.html, lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Actuellement, une structure contactée a l'information qu'elle peut décliner (pas intéressée) sur la page détail du besoin.
Avoir d'avantage de structures qui partagent leur non intérêt (et feedback) au lieu de devoir les relancer.
En cliquant sur NON, le popup s'affichera directement à l'utilisateur
- on rajoute un bouton dans cet e-mail
- le lien amène toujours vers la page détail du besoin, mais affiche directement le popup (grâce à un bout de JS + `not_interested=True` dans l'url)
- le workflow est ensuite identique au fonctionnement actuel
=> feat(Besoins): Permettre à une structure contactée de décliner dès l'e-mail

lemarche/companies/admin.py, lemarche/companies/models.py, lemarche/companies/tests.py
Dans le modèle `Company`, j'ai enrichi le queryset `with_user_stats`, pour avoir une nouvelle info `user_tender_count_annotated`
Et j'affiche ca dans l'admin :)
avoir aussi un champ `user_tender_count` pour avoir ce chiffre dans Metabase ?
=> feat(Besoins): Admin : Connaitre le nombre de besoins déposés par chaque entreprise

lemarche/templates/tenders/_card_list_item.html, lemarche/templates/tenders/_closed_badge.html, lemarche/templates/tenders/_detail_card.html, lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/_list_item_network.html, lemarche/www/tenders/tests.py
Améliorer le badge de clôture du DDB.
Apporter plus de visibilité aux utilisateurs.
En créant un composant réutilisable dans toute les templates.
Avant : 
Après :
=> refactor: Améliorer le badge de clôture du DDB 

config/settings/base.py, lemarche/templates/api/home.html
On a fait des modifications sur la présentation de notre API, le lien a changé coté api.gouv
Ancien lien : https://api.gouv.fr/les-api/api-structures-inclusion
Nouveau lien : https://api.gouv.fr/les-api/api-marche-inclusion
cf https://github.com/betagouv/api.gouv.fr/pull/1309
=> fix(API): mise à jour du lien vers api.gouv

lemarche/tenders/models.py, lemarche/tenders/tests.py, lemarche/users/models.py, lemarche/www/tenders/forms.py
Correction du nombre d'occurrence dans la liste déroulante et dans le compteur d'entête. 
Le distinct utilisé pour dédoublonner, dans le cas où l'utilisateur a plusieurs structures, produit uniquement des 1.
En déplaçant le queryset sur Tender.
=> fix(Besoins): Correction sur le nombre d'occurrences en status Nouveau sur le filtre par type

lemarche/siaes/admin.py, lemarche/tenders/admin.py, lemarche/users/models.py, lemarche/users/tests.py
Grâce à #1113 et le nouveau champ M2M `Tender.admins`, on souhaite maintenant filtrer la liste des besoins par les bizdev rattachés.
- un bizdev = un User avec `kind=ADMIN` & `position=Bizdev`
- possibilité aussi de filtrer sur les besoins sans admin
=> feat(Besoins): Admin : filtre de la liste par bizdev

lemarche/templates/tenders/_detail_card.html
Pour mettre le nom de l'entreprise en avant
=> feat(Besoins): Détail : afficher l'entreprise de l'acheteur en gras

lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Similaire à #922 & #1124, mais coté prestataire (vs coté auteur du besoin)
Suite à l'ajout des champs `TenderSiae.transactioned` & `TenderSiae.transactioned_source` dans la PR #1133
- on met à jour ces champs automatiquement à la réponse de la structure
- peu import si la réponse est Oui ou Non
=> feat(Besoins): Sondage transaction : mettre à jour le TenderSiae en fonction de la réponse

lemarche/cms/management/commands/populate_demo_images.py
Création d'une commande permettant de copier des images présentes dans le répertoire de code vers le système de fichier de Django. 
Afin de pouvoir utiliser les images dans les `fixtures`.
Exemple d'une fixture Wagtail Image utilisable après un `python manage.py populate_demo_images --images_demo=lemarche/fixtures/django/images/ --folder=original_images` : 
`[{
"model": "wagtailimages.image",
"pk": 1,
"fields": {
"collection": 1,
"title": "hp-logos-labels.min.09f76cdcd009",
"file": "original_images/hp-logos-labels.min.09f76cdcd009.png",
"width": 855,
"height": 677,
"created_at": "2024-03-22T09:32:26.912Z",
"uploaded_by_user": 1,
"focal_point_x": null,
"focal_point_y": null,
"focal_point_width": null,
"focal_point_height": null,
"file_size": 50853,
"file_hash": …
=> ci: Ajout d'une commande pour copier les images de démonstration

lemarche/static/js/utils.js, lemarche/templates/networks/dashboard_network_tender_list.html, lemarche/templates/tenders/_list_item_buyer.html, lemarche/templates/tenders/_list_item_network.html, lemarche/templates/tenders/list.html
Actuellement, sur la page "liste de besoins", il y a un "conflit" de liens, ce qui provoque l'ouverture d'un onglet supplémentaire.
J'ai baissé d'un niveau le lien global (vers le détail du besoin), pour pas qu'il entre en conflit avec les stats (prestataires intéressés etc)
=> fix(Besoins): répare l'ouverture au clic de 2 liens dfférents

lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Suite à #1143, lorsqu'on connait l'utilisateur, on le met à jour
Lors du clic dans l'e-mail envoyé aux structures (et aux utilisateurs de cette structure) : 
- si l'utilisateur est connecté, alors on rajoute l'info
- si l'utilisateur est anonyme, mais qu'on a son `user_id`, alors on rajoute l'info
=> feat(Besoins): mettre à jour l'utilisateur de la mise en relation

lemarche/templates/cms/streams/section_ecosystem.html, lemarche/templates/cms/streams/section_studies_cases_tenders_case.html, lemarche/templates/cms/streams/section_testimonials.html
L'image de la section écosystème est restée en statique :
Les alt des images de l'étude de cas était écrasé.
Et un fond gris qui n'est pas souhaitable.
=> fix: L'image de la section Ecosystème ne change pas

lemarche/siaes/models.py, lemarche/tenders/models.py, lemarche/utils/apis/api_elasticsearch.py
Le ciblage IA tient compte des types de structure sélectionnés dans l'admin du besoin.
Pour est cohérent avec le ciblage classique.
En ajoutant le type de structure aux metadatas des documents elasticsearch et en ajoutant le filtre.
Type de structure dans l'admin : 
⚠️ l'indexation doit être refaite après la mise en prod.
Je l'ai faite sur la recette jetable.
=> feat(Besoins): Filtre par type de structure dans le ciblage des structures par recherche sémantique

lemarche/static/itou_marche/base/_custom.scss, lemarche/templates/includes/_header_for_buyers.html, lemarche/templates/includes/_header_for_siaes.html, lemarche/templates/layouts/_header.html, lemarche/www/pages/tests.py, lemarche/www/siaes/tests.py
Ajout d'un bandeau avec lien (dépend de la PR #1156 )
Pour inciter les structures à visiter leur page d'accueil et les acheteurs la leur.
Bandeau affiché qu'aux utilisateurs non connecté et changeant si on est sur la page d'accueil structure.
Bandeau sur toutes les pages (si non connecté)
Bandeau sur la page d'accueil structure (si non connecté)
=> feat: Ajout d'un bandeau pour inciter les structures à visiter leur page d'accueil

clevercloud/tenders_send_siae_contacted_reminder_emails.sh, lemarche/tenders/management/commands/send_siae_contacted_reminder_emails.py, lemarche/tenders/management/commands/send_siae_interested_reminder_emails.py
Ne pas envoyer l'email de relance aux structures concernées, si elles ont indiqué "pas intéressées"
=> fix(Besoins): évite d'envoyer des mails de relance aux structures pas intéressées

clevercloud/tenders_send_siae_contacted_reminder_emails.sh, lemarche/tenders/management/commands/send_siae_contacted_reminder_emails.py, lemarche/tenders/management/commands/send_siae_interested_reminder_emails.py
Actuellement, on envoi 3 mails de relance aux structures concernées (contactées) mais qui n'ont pas encore vues le besoin.
Or il y a un soucis sur la gestion de ces envois avec le weekend, et un mauvais décalage des jours (plusieurs mails de relance sont envoyés en même temps).
J'ai désactivé les mails J+3 & J+4
Lié à https://github.com/gip-inclusion/le-marche/pull/1158
=> fix(Besoins): réduit le nombre de mails de relances envoyés aux structures concernées

lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Si `kind` = TENDER & `external_link` est rempli, alors `response_kind` doit contenir RESPONSE_KIND_EXTERNAL
Pour que le lien externe s'affiche bien aux structures
=> feat(Besoins): Formulaire : si un lien externe est fourni, alors forcer le choix de réponse

lemarche/companies/management/commands/create_companies.py, lemarche/utils/emails.py
A partir de la liste des acheteurs (en filtrant sur ceux qui ne sont pas encore rattachés à une entreprise + qui ont une adresse e-mail non-générique), on créé de nouvelles entreprises
- en utilisant le champ `User.company_name`
- en demandant confirmation à chaque fois
=> feat(Entreprises): commande interactive pour créer de nouvelles entreprises à partir des infos des acheteurs

lemarche/siaes/admin.py, lemarche/siaes/models.py
Dans l'admin, coté structures, afficher `tender_detail_contact_click_count_annotated_with_link`
=> refactor(Structure): Admin : afficher le nombre de besoins pas intéressés

lemarche/templates/tenders/admin_change_form.html, lemarche/tenders/models.py, lemarche/tenders/tests/test_models.py
En partie lié à #1175
Les admin peuvent décider de ré-envoyer des besoins, mais on ne vérifie pas la date de clôture.
Grâce à cette PR
- on désactive le bouton une fois la date de clôture dépassée
- on rappelle la date de clôture et de début des prestations
- on ajoute des tests sur ces 2 property
=> fix(Besoins): ne pas autoriser le ré-envoi si la date de clôture est dépassée

config/settings/base.py, lemarche/www/auth/tasks.py
Suite de #1018 & #1024
Premier utilisation de TemplateTransactional, sur le seul mail "auth" qui est géré par Mailjet.
=> feat(Emails): remplacer l'envoi de finalisation du compte par son TemplateTransactional

lemarche/crm/management/commands/crm_brevo_sync_contacts.py, lemarche/utils/apis/api_brevo.py
Les utilisateurs existent dans brevo, mais on a pas stocké les identifiants.
=> feat(crm): Management commande de Synchronisation des utilisateurs avec Brevo

lemarche/cms/models.py
Suppression de la limite du nombre de page de type HomePage et ajout d'une description du type.
Pour pouvoir créer des pages d'atterrissage à souhait.
=> feat: suppression de la limite du nombre de page d'accueil

lemarche/utils/apis/api_brevo.py, lemarche/utils/apis/api_mailjet.py
Dans la PR #1034 j'avais enlevé les valeurs par défaut de `from_email` & `from_name` pour `api_mailjet` et `api_brevo`
Or cela génère des erreurs coté Sentry
Je revert, car je ne sais pas quels sont les impacts exacts, et si les envois sont cassés depuis 1 semaine ???
Sachant que cela sera de toute façon supprimé par la fin de la migration vers TemplateTransactional (cf #1193)
=> fix(Emails): ajout de valeurs par défaut pour from_email & from_name

lemarche/utils/apis/api_brevo.py, lemarche/utils/apis/api_mailjet.py
Similaire à #1204
Dans la PR #1034 j'avais enlevé les valeurs par défaut de `subject` pour `api_mailjet` et `api_brevo`
Or cela génère des erreurs coté Sentry
Je revert, car je ne sais pas quels sont les impacts exacts, et si les envois sont cassés depuis 1 semaine ???
Sachant que cela sera de toute façon supprimé par la fin de la migration vers TemplateTransactional (cf #1193)
=> fix(Emails): ajout de valeur par défaut pour subject

lemarche/tenders/admin.py, lemarche/utils/apis/api_brevo.py
Nouvelle méthode `api_brevo.link_company_with_contact_list` pour pouvoir rattacher les utilisateurs à leur structure sur Brevo
Similaire à #1123 qui ajoutait `api_brevo.link_deal_with_list_contact`
=> feat(Brevo): méthode pour lier des Contacts (User) à une Company (Siae)

lemarche/utils/apis/api_brevo.py, lemarche/www/dashboard_siaes/tests.py, lemarche/www/dashboard_siaes/views.py
Grâce à #1209 on a une méthode pour rattacher des Contacts (Users) à une Company (Structure)
Grâce à #1210 on a tous les utilisateurs structures qui ont un "Brevo contact ID"
On peut donc rattacher les contact à leur company dans Brevo, au moment où le rattachement est effectif dans Django
=> feat(Brevo): lorsqu'un utilisateur se rattache à une structure, envoyer l'info à Brevo

lemarche/crm/management/commands/crm_brevo_sync_contacts.py, lemarche/utils/apis/api_brevo.py
Suite à #1123 & #1209
Lors des link/unlink, parfois le brevo_contact_id de l'utilisateur est None, cela provoque une erreur coté Brevo.
J'ai rajouté 1 ou 2 lignes de code pour mieux gérer ces cas là.
J'ai aussi amélioré la commande `crm_brevo_sync_contacts` pour forcer de passer les paramètres lors de son utilisation, et légerement refactoré le code
=> fix(Brevo): mieux gérer le rattachement des contact avec leur company / deal

config/settings/base.py, lemarche/templates/layouts/_footer.html, lemarche/templates/layouts/_header_nav_secondary_items.html, lemarche/utils/settings_context_processors.py
Changement du lien "Auditer vos achats" dans le menu d'entête et dans le pied de page
Pour tester la nouvelle page "Impact RSE"
En passant par une variable settings, d'une part pour éviter les requêtes, le lien étant sur toutes les pages. Mais également pour pouvoir le changer avec une variable d'environnement.
=> feat: Changer url de la page "Auditer vos achats"

lemarche/static/itou_marche/sections/_home.scss
Correction du flex
Pour avoir des blocs de la même hauteur, plus harmonieux visuellement
Ajout de la propriété `flex` aux items du carousel et à l'élément contenant.
Avant :
Après :
=> fix: Uniformisation de la hauteur des blocs du carousel

lemarche/utils/apis/api_hubspot.py
Suite à #1215 le format de `User.phone` a changé, et il doit être converti en string pour être envoyé à des API tierces
=> fix(Hubspot): Répare la création de contact (suite au changement de format du numéro de téléphone)

lemarche/siaes/models.py, lemarche/tenders/models.py, lemarche/users/models.py, lemarche/utils/apis/api_brevo.py, lemarche/utils/apis/api_hubspot.py, lemarche/utils/data.py, lemarche/utils/export.py, lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py
Suite à #1215, #1221 & #1224. Lié à #1232
il y a des erreurs quand on souhaite serializé le champ `PhoneNumberField`. J'ai rajouté une property pour chaque modèle concerné qui explicite la stringification
=> fix: Répare l'affichage des numéros de téléphone (suite au changement de format)

lemarche/siaes/admin.py, lemarche/tenders/admin.py, lemarche/users/admin.py
On a récemment créé des champs dédiés pour stocker les identifiants Brevo : 
- `Siae.brevo_company_id` : #1208
- `User.brevo_contact_id` : #1123
- `Tender.brevo_deal_id` : #1123
Mais ce champ n'était pas affiché dans l'admin.
J'en ai profité pour faire un peu de ménage (utiliser des collapse, déplacer les logs dans une section dédiée)
=> fix(Brevo): Admin : afficher les identifiants (contact_id, deal_id, company_id)

lemarche/crm/management/commands/crm_brevo_sync_contacts.py, lemarche/utils/apis/api_brevo.py
Dans #1178 on a créé la management command `crm_brevo_sync_contacts` qui permet d'ajouter des utilisateurs à des listes.
Grâce à #1215 on a maintenant un champ `User.phone` qui est propre et prêt à être envoyé à Brevo
J'ai donc amélioré la fonction `api_brevo.create_contact()` (qui gère par défaut la mise à jour) pour envoyer le téléphone de l'utilisateur
```
python manage.py crm_brevo_sync_contacts --kind-users=BUYER --brevo-list-id=10
python manage.py crm_brevo_sync_contacts --kind-users=SIAE --brevo-list-id=23
```
=> fix(Brevo): Mieux gérer la mises à jour des contacts Brevo (et envoyer le téléphone)

lemarche/siaes/management/commands/import_esat_from_csv.py, lemarche/utils/commands.py
Import des nouvelles ESATs et mise à jour des champs "Email", "Téléphone" et "Nombre de travailleurs"
Pour avoir des données sur les ESATs à jour autant que possible.
Management Command Django d'import depuis un fichier CSV, avec une option "dry-run" pour tester l'impact.
=> feat(SIAE): script d'import des ESATs du fichier csv Gesat/Handeco

lemarche/siaes/management/commands/import_new_sep.py
Import des nouvelles SEP et mise à jour des champs "Email", "Téléphone" pour celle qui n'ont pas encore d'utilisateur.
Les SEP sont désormais séparées par secteur d'activité pour avoir les informations de contact par secteur.
Pour avoir des données sur les SEP à jour autant que possible.
Management Command Django d'import depuis un fichier CSV, avec une option "dry-run" pour tester l'impact.
Il a deux fichiers csv correspondant aux SEP et aux SEP externe.
=> feat(SIAE): script d'import/mise à jour des SEP

lemarche/templates/siaes/_card_detail.html, lemarche/templates/siaes/_card_search_result.html, lemarche/www/siaes/tests.py
Quelques modifications d'affichage et de wording sur le fait que la structure ne soit pas encore inscrite sur le marché
- le message "bientôt inscrite sur le marché" s'affiche que pour les admins
- il s'affiche aussi sur la page détail
- renommé à "pas encore inscrite" 
- ajouté un test :) 
pour un utilisateur admin
|page|Avant|Après|
|---|---|---|
|Résultats de recherche|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/981ceb49-a399-4eca-a1f7-690727f1f401)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/859f295a-f329-4ceb-86ae-4e53d0c3f662)|
|Page détail (nouveau)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/b90d9c85-978d-49a4-a6e9-134497b1a7fe)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/71839e9a-83cf-4abf- …
=> fix(Structures): afficher seulement aux admins l'information que la structure n'est pas encore inscrite

lemarche/tenders/admin.py, lemarche/users/admin.py
Suite à #1134, l'autocomplete des utilisateurs ne filtrait pas sur les admins
Réparé en utilisant la bonne méthode : `get_search_results`
- https://stackoverflow.com/questions/48152908/how-to-filter-choices-in-django2s-autocomplete-fields
- https://forum.djangoproject.com/t/django-admin-autocomplete-field-search-customization/7455/8
=> fix(Besoins): Admin : filtre vraiment la liste des utilisateurs sur les bizdev

lemarche/tenders/models.py, lemarche/tenders/tests/test_models.py, lemarche/www/dashboard/views.py, lemarche/www/dashboard_networks/views.py, lemarche/www/tenders/views.py
Changement de l'ordre des dépôts de besoins pour afficher les plus récemment publiés en premier.
Les besoins clôturées doivent rester en bas de liste.
Pour rendre la consultation plus simple pour les structures et être plus cohérent avec les 3 besoins remontés sur le tableau de bord.
En changeant de Queryset et en supprimant celui sur les dates de clôture qui n'est donc plus utilisé.
=> feat(Besoins): Ordonner les besoins par date de publication

lemarche/api/perimeters/filters.py, lemarche/perimeters/models.py, lemarche/perimeters/tests.py
- bouger la logique du filtre "autocomplete" depuis l'API vers le modèle (Queryset)
Pour plus facilement le réutiliser
=> refactor(Périmètres): Bouger le filtre autocomplete de l'API vers le modèle

lemarche/perimeters/models.py, lemarche/perimeters/tests.py
Suite de #1264
Rajouté une option pour pouvoir aussi inclure l'`insee_code` dans le filtre sur les `post_code`
=> refactor(Périmètres): Pouvoir aussi filtrer les post_codes sur le insee_code

lemarche/siaes/models.py, lemarche/templates/dashboard/siae_edit_contact.html, lemarche/templates/dashboard/siae_edit_offer.html, lemarche/templates/dashboard/siae_edit_search.html, lemarche/utils/data.py, lemarche/utils/templatetags/array_choices_display.py
- éviter que le titre ne passe à la ligne
- refactoring du `choice_array_to_string`
||Image|
|---|---|
|Avant|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/c4e01da6-8820-4bdb-94ef-d6071e34b035)|
|Après|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/aaabf4b9-5adb-4750-8a45-b14d6acdeb50)|
=> refactor(Structures): quelques cleanup

lemarche/templates/tenders/_closed_badge.html
Peu importe le type de besoins, les badges sont de la même couleur une fois clôturés.
Plus lisible
Classe CSS existante
Avant : 
Après :
=> feat(Besoins): changement de couleur des badgets des besoins clôturés

config/settings/base.py, docker-compose.yml, lemarche/www/siaes/tests.py
Changement de la façon de stocker les sessions.
Le stockage de session dans le cookie (`signed_cookies`) semble être la source de multiples erreurs:
- erreur CSRF dans le dépôt de besoin
- erreur 502 Bad gateway dans le dépôt de besoin
- prévisualisation des pages Wagtail
- erreur CSRF dans la validation des besoins
Les limitations de `signed_cookies` sont désormais décrite [ici](https://docs.djangoproject.com/en/5.0/topics/http/sessions/#using-cookie-based-sessions).
En changeant le `SESSION_ENGINE` au profit de `cached_db`. Les écritures de sessions sont appliquées à la fois au cache et à la base de données et les lectures de sessions utilisent d’abord le cache.
L'activation du cache pour la session est soumis à la variable d'environnement `REDIS_CACHE_ENABLED`. Si elle n'est pas …
=> fix(Session): Stockage des sessions côté serveur

config/settings/prod.py
Ajout du nom de domaine de production aux domaines de confiance CSRF.
Pour débloquer la prévisualisation Wagtail en production
Avec la variable `CSRF_TRUSTED_ORIGINS`.
=> fix(wagtail): add csrf trusted origins to fix wagtail preview

lemarche/static/js/siae_geo_range_field.js, lemarche/templates/dashboard/siae_edit_activities.html, lemarche/templates/dashboard/siae_edit_activities_create.html, lemarche/templates/dashboard/siae_edit_search.html, lemarche/www/dashboard_siaes/forms.py, lemarche/www/dashboard_siaes/urls.py, lemarche/www/dashboard_siaes/views.py
v1 du formulaire de création, avec les champs
- sector_group & sectors (choix dynamique en fonction du group sélectionné)
- presta_type
- geo_range & geo_range_custom_distance (comme actuellement)
- gestion de la `location`
=> feat(Structures): SiaeActivity : formulaire pour créer une nouvelle activité

lemarche/utils/apis/api_brevo.py
Fix du nom et prénom dans la synchronisation des contacts avec Brevo.
+Ajout d'une méthode pour mettre à jour un contact Brevo pour rattraper le stock
=> fix: Fix du nom et prénom dans la synchronisation des contacts avec Brevo

lemarche/templates/dashboard/_siae_activity_card.html, lemarche/templates/dashboard/siae_edit_activities.html, lemarche/templates/dashboard/siae_edit_activities_create.html, lemarche/templates/siaes/_siae_activity_card.html, lemarche/templates/siaes/_siae_activity_content.html, lemarche/templates/siaes/detail.html
Dans la continuité de #1266, afficher les activités coté fiche structure.
J'ai réutilisé le template `_siae_activity_card.html` existant
=> feat(Structures): SiaeActivity : afficher les activités dans la fiche

lemarche/siaes/tasks.py, lemarche/www/dashboard_siaes/tasks.py, lemarche/www/tenders/tasks.py
Suite à https://github.com/gip-inclusion/le-marche/pull/1337
On n'a plus besoin de logger en JSON les metadatas des mails envoyés
=> refactor(Emails): enlève les logs en double suite à TemplateTransactionalSendLogs

lemarche/conversations/models.py
Suite à #1337
Répare un bug sur la création de logs suite à l'envoi de mails grâce à Template Transactional
- on suppose que c'est un problème d'asynchrone, huey n'a pas encore renvoyé la réponse, donc `result() = None`
- https://huey.readthedocs.io/en/latest/api.html#Huey.result
- `TypeError : 'NoneType' object is not callable`
=> fix(Emails): Template Transactional: remove result() call

lemarche/companies/management/commands/set_company_users.py, lemarche/users/models.py, lemarche/users/tests.py
Suite à #830
Il y avait un border case mal géré, on ne prenait pas toujours en compte l'intégralité du nom de domaine de l'e-mail de l'utilisateur
- ajouté un queryset `has_email_domain` sur le modèle `User`
- ajouté des tests
=> fix(Entreprises): ajuste le script de rattachement des utilisateurs en fonction de leur email (ajoute un @)

lemarche/conversations/models.py, lemarche/conversations/tests.py, lemarche/utils/data.py, lemarche/www/dashboard_siaes/tests.py
Suite à la création du modèle `TemplateTransactional` dans #1018
Ajout de validations à la sauvegarde du modèle, pour s'assurer qu'il n'y a pas d'emails actifs sans mailjet_id ou brevo_id (en fonction de la source)
=> refactor(Emails): ajout de tests de validation sur les TemplateTransactional

lemarche/conversations/admin.py, lemarche/siaes/admin.py
On les avait mis en readonly, mais ca empêchait leur suppression (en particulier dans le cas d'un CASCADE, où l'on souhaite supprimer un utilisateur)
=> fix(Admin): autoriser la suppression des SiaeUserRequest & TemplateTransactionalSendLog

lemarche/templates/includes/_widget_custom_multiselect.html, lemarche/templates/siaes/search_results.html
Gestion de l'état désactivé sur les champs multiselect.
Quand on n'est pas connecté, les champs de recherche avancée doivent être désactivés
En mettant un simple "select" avec "disabled" quand le champs est désactivé. 
Avant:
Après:
=> fix(Recherche): Les champs multiselect ne doivent pas s'activer lorsqu'ils sont désactivés

lemarche/static/js/siae_activity_delete.js, lemarche/templates/dashboard/_siae_activity_delete_modal.html, lemarche/templates/dashboard/siae_edit_activities.html, lemarche/templates/dashboard/siae_edit_activities_create.html, lemarche/templates/django/forms/widgets/multiple_input.html, lemarche/templates/siaes/_siae_activity_card.html, lemarche/www/dashboard_siaes/forms.py, lemarche/www/dashboard_siaes/views.py
Adaptation des écrans déjà créé au DSFR
Pour rendre ces écrans fonctionnels avec la migration DSFR.
En changeant le balisage HTML de la liste, de la modale de suppression, du formulaire et en adaptant le javascript.
J'ai également du surcharger le template multiple_input car celui du DSFR n'affichait pas les groupes (indispensable pour filtrer les activités selon le premier select).
Liste
Ajout
Modale de suppression
Pour voir l'onglet "Référencement 2", il faut être admin ou supprimer le if [ici](https://github.com/gip-inclusion/le-marche/blob/55ee22a2f7588164d8650c8c2049a0ac3414299c/lemarche/templates/dashboard/siae_edit_base.html#L93) 
Les tests arrivent dans la PR #1457
=> refactor(Activités des structures): Adaptation au DSFR des écrans d'édition des activités des structures

lemarche/templates/django/forms/widgets/checkbox_option.html
En voulant corriger l'affichage des cases à cocher dans l'admin, ça a perturbé l'affichage en front
Avant : 
Après :
=> fix: Correction de l'affichage des cases à cocher des secteurs d'activités

Makefile, lemarche/siaes/models.py, lemarche/templates/dashboard/siae_edit_activities_create.html, lemarche/tenders/tests/test_matching.py, lemarche/www/dashboard_siaes/forms.py, lemarche/www/tenders/tests.py
Ajout des méthodes de matching sur les activités.
Car les secteurs, le type de prestation et les périmètres associés vont désormais ếtre portés par l'activité. 
En créant le méthode `filter_with_tender` sur le queryset de `SiaeActivity` et en ajoutant une nouvelle méthode `filter_with_tender_through_activities` sur le queryset de `Siae`. Ainsi, l'existant va continuer de fonctionner et on pourra tester la reprise de stock en comparant les structures retournées par les deux méthodes de matching.
=> feat(Activités des structures): Déplacement du matching sur les activités

lemarche/tenders/admin.py, lemarche/utils/apis/api_brevo.py
- Réparation du montant qui n'était pas complété lors de la synchronisation avec Brevo
- Plus de synchronisation avec Brevo quand on envoi aux partenaires
- Envoi de l'erreur à l'utilisateur sur les prochaines erreurs de synchronisation
=> fix: Réparation du montant lors de la synchro avec Brevo

lemarche/siaes/management/commands/create_siae_activities.py, lemarche/siaes/tests/test_commands.py, lemarche/siaes/tests/test_models.py, lemarche/siaes/utils.py
Adaptation de la commande de reprise de stock pour le matching au niveau des activités.
Le modèle de données a évolué, notamment avec le changement sur le `geo_range` du modèle `SiaeActivity`.
Création des activités en fonction du `geo_range` de la SIAE, ajout des secteurs d'activités et ajout des périmètres pour les `geo_range` département et région.
Ajout de tests sur la management command.
L'héritage de `TransactionTestCase` plutôt que `TestCase` s'est avéré nécessaire pour éviter les interférences entre les tests.
=> fix(Activités des structures): Adaptation de la commande de reprise de stock pour créer les activités

lemarche/siaes/management/commands/create_siae_activities.py, lemarche/siaes/tests/test_commands.py
Ajustement des exceptions de la management command.
Des structures inactives ont des périmètres de définit en département sans département et pareil pour les régions.
Exception uniquement si  la structure est active.
=> fix(Activités des structures): Ajustement des exceptions de la commande de reprise de stock pour créer les activités

lemarche/static/itou_marche/itou_marche.scss, lemarche/static/js/perimeter_autocomplete_field.js, lemarche/templates/siaes/search_results.html
Les champs AutoCompleteAccessible n'était pas en mode DSFR.
+ retrait du badge "Nouveauté" et le badge beta est moins mis en valeur.
Modification html et css.
=> fix: fix dsfr des champs géré via AutoCompleteAccessible

lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py, lemarche/utils/apis/api_brevo.py, lemarche/utils/emails.py, lemarche/www/pages/views.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/utils.py, lemarche/www/tenders/views.py
Ajout de trois attributs lors de la création de contact dans la liste #10 (Acheteurs inscrits) de Brevo : 
- MONTANT_BESOIN_ACHETEUR
- TYPE_BESOIN_ACHETEUR
- TYPE_VERTICALE_ACHETEUR
Pour segmenter les envois d'email et ne pas multiplier les listes sur Brevo.
En ajoutant un argument `tender_id` dans la méthode `add_to_contact_list` définie dans emails.py. Cette dernière est appelée dans les trois méthodes de création de Tender (`done`, `perform_create` et `csrf_failure`) afin de récupérer l'id du tender qui permettra d'associer les informations du tender à l'utilisateur de type "acheteur".
- Il manque un test sur la méthode csrf_failure car il était compliqué de récupérer l'erreur csrf dans le test pour la traiter et permettre la création du tender.
- J'ai ajouté un User de type BUYER dans …
=> feat: Ajout d'attributs de contact pour les acheteurs inscrits

lemarche/siaes/management/commands/create_siae_activities.py, lemarche/siaes/models.py, lemarche/siaes/tests/test_commands.py, lemarche/tenders/tests/test_matching.py
Ajustement du matching au niveau des périmètres.
Ajustement de la commande pour reprendre les secteurs et les types de prestations même si il n'y a pas de périmètre associé
Pour permettre aussi la correspondance directement sur la ville/département/région de la structure.
Dans la commande : ajout de la création d'une activité de type "ZONES", mais sans périmètre
Sur la matching : ajout d'une condition pour tenter la correspondance directement sur la ville, le département ou  la région de la structure.
=> fix(Activités des structures): ajout de la correspondance directe sur la ville, le département ou la région de la structure

lemarche/static/itou_marche/itou_marche.scss, lemarche/templates/layouts/base.html, lemarche/templates/tenders/_closed_badge.html, lemarche/templates/tenders/_detail_card.html, lemarche/tenders/models.py
Fix de l'affichage des détails de dépôts de besoins.
Les champs descriptions sont édité depuis l'éditeur de texte ckeditor, donc l'output est déjà en html pas besoin de `linebreaks` dans les template django.
Profite de l'occasion pour réarranger un peu l'affichage.
+fix de la date de clôture du DDB.
**Avant**
**Après**
=> fix: Affichage du détail du dépôt de besoin

config/settings/base.py, config/urls.py, lemarche/templates/layouts/_footer.html, lemarche/templates/pages/plan_du_site.html, lemarche/www/pages/tests.py, lemarche/www/pages/urls.py, lemarche/www/pages/views.py
Ajout d'un fichier sitemap.xml et d'un lien 'Plan du site' dans le footer.
Pour améliorer le référencement naturel
- En utilisant une vue Sitemap de Wagtail pour récupérer les pages du cms
- En créant un fichier sitemaps.py pour définir des Sitemap custom afin de récupérer les FlatPage et les urls de l'app 'pages'
Le fichier sitemap.xml est accessible à la racine. Une vue SitemapView a été créée pour extraire les données de ce dernier et les afficher dans une page 'Plan du Site'.
sitemap.xml
plan-du-site
lien dans le footer
=> feat: Ajout d'un sitemap

lemarche/templates/dashboard/siae_edit_search.html, lemarche/www/dashboard_siaes/forms.py, lemarche/www/siaes/tests.py
Pour déployer la refonte des activités, il faut lancer la commande de reprise de stock et il ne faut pas de modification pendant ce temps et ce jusqu'à ce que le nouvel onglet soit publié.
Cette PR permettra donc de mettre en lecture seule cet onglet.
Pour qu'il n'y ait pas de modification le temps de lancer la commande de reprise de stock.
Ajout d'un message de warning, champs en disable et suppression du bouton submit.
J'en ai profité pour fixer le test sur les nombres de requêtes de la home qui passait à 13 quand on lançait les tests en parallèle. Grâce à une discussion avec @rsebille, il s'avère que la mise en cache et la séquence peuvent différer en parallèle. Un simple appel à la page en amont permet donc de corriger le problème.
=> chore(Activités des structures): Passage du formulaire "Votre référencement" en lecture seule

lemarche/templates/dashboard/siae_edit_base.html, lemarche/www/dashboard_siaes/tests.py, lemarche/www/dashboard_siaes/urls.py
Remplacement de l'onglet "Votre référencement"
Pour que les structures puissent modifier leurs activités avec le nouveau système.
Changement dans le template sans supprimer les anciennes pages pour le moment (au cas où).
Avant
Après
=> feat(Activités des structures): Remplacement de l'onglet "Votre référencement"

lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py
Modification de la recherche pour prendre les secteurs d'activités, les types de prestations et les périmètres des activités.
Pour s'adapter à la mise en place des activités des structures
Avec une `Subquery` pour bien faire la correspondance entre secteur/presta type/périmètre au niveau des activités.
Par exemple, si je cherche une structure pour mes espaces verts à Tours, il ne faut pas qu'une structure qui fait du textile à Tours et des espaces verts à Rennes remonte dans les résultats.
=> feat(Activités des structures): Adaptation de la recherche des Siaes

lemarche/siaes/models.py, lemarche/static/itou_marche/itou_marche.scss, lemarche/templates/siaes/_card_detail.html, lemarche/templates/siaes/_card_search_result.html, lemarche/templates/siaes/_siae_activity_card.html, lemarche/templates/siaes/_siae_activity_content.html, lemarche/templates/utils/templatetags/siae_sectors_display.html, lemarche/utils/templatetags/siae_sectors_display.py, lemarche/utils/tests_templatetags.py, lemarche/www/dashboard_favorites/tests.py, lemarche/www/dashboard_favorites/views.py, lemarche/www/siaes/forms.py, lemarche/www/siaes/tests.py, lemarche/www/siaes/views.py
Affichage des secteurs d'activité et types de prestation des activités sur les cartes des structures sur la recherche, sur la liste de favoris et sur la fiche structure
Pour tenir compte du système des activités des structures.
Avec un template tag pour gérer l'affichage des secteurs d'activités. Dans la recherche, les secteurs sélectionnés doivent s'afficher en premier avec un style différent.
Et avec des accordéons sur la fiche structure.
Avant
Après
Avant
Après
=> feat(Activités des structures): Adaptation de l'affichage des secteurs d'activités des structures

lemarche/siaes/models.py, lemarche/templates/siaes/_siae_activity_content.html
=> fix(Activités des structures): Correction de l'affichage des fiches structures sans type de prestation

lemarche/tenders/migrations/0094_add_templatetransactional_tender_author_commercial_partners.py, lemarche/www/dashboard_siaes/views.py, lemarche/www/tenders/tasks.py
Ajout d'un template de mail spécifique à destination des auteurs de besoin qui ont été pris en charge par un partenaire commercial. 
+ correction d'une petite faute d'orthographe
Pour éviter aux acheteurs de recevoir un mail indiquant 0 fournisseur trouvé et de recevoir un appel dans la foulée indiquant le contraire.
À la validation du besoin, le template n'est pas le même si le besoin a été marqué pour être envoyé aux partenaires commerciaux.
Le `TemplateTransactional` est créé par la migration, mais l'id devra être ajouté en production et passé en actif.
=> feat(Besoin): Ajout d'un template de mail transactionnel quand le besoin est suivi par un partenaire commercial

lemarche/siaes/management/commands/update_siae_count_fields.py, lemarche/siaes/models.py, lemarche/siaes/tests/test_commands.py, lemarche/siaes/tests/test_models.py, lemarche/templates/dashboard/siae_edit_base.html, lemarche/utils/export.py
Mise à jour du calcul du nombre de secteurs d'activités pour une structure
Avec la nouvelle gestion des activités, le calcul n'est plus bon et un message d'information invite à saisir des activités alors qu'il y en a déjà.
À noter que ça impacte également le taux de complétion de la fiche structure.
Remplacement du Signal pour une mise à jour dynamique à la modification.
Adaptation de la commande de mise à jour pour la mise à plat hebdomadaire des compteurs.
Ajout de tests
=> fix(Secteurs d'activités): Mise à jour du calcul du nombre de secteurs pour le déduire des activités associées

lemarche/crm/management/commands/crm_brevo_sync_companies.py, lemarche/crm/tests.py, lemarche/siaes/models.py, lemarche/utils/apis/api_brevo.py
Partie 2 de la synchro Brevo, donc suite de la [PR1468](https://github.com/gip-inclusion/le-marche/pull/1468)
Ajout d'attributs dans la liste des Structures dans Brevo.
Pour segmenter les envois d’email marketing, et ne pas multiplier les listes sur Brevo.
En ajoutant 3 attributs dans siae.extra_data :
- siae.completion_rate
- siae.tender_email_send_count_annotated (besoins reçus les 90 derniers jours)
- siae.tender_detail_contact_click_count_annotatedsiae.tender_detail_contact_click_count_annotated (nombre de fois qu'une structure est intéressée par un besoin ces 90 derniers jours)
> Ces deux derniers attributs ne sont pas directement ceux de Siae mais des champs annotés dans un queryset de SiaeQueryset
Enfin, le dictionnaire est initialisé et/ou mis à jour dans la commande …
=> feat: Ajout d'attributs dans Brevo pour les structures

lemarche/static/js/utils.js
Corriger le clic sur les dépôts de besoins pour les acheteurs
Parce qu'une erreur js empêche le javascript de géré le clic
En supprimant l'appel à une fonctionne qui n'existe plus.
=> fix(Liste des dépôts de besoin): Correction d'une erreur javascript pour éviter un bug sur la liste

Makefile, lemarche/cms/management/commands/create_content_pages.py, lemarche/cms/tests/test_commands.py
- Amélioration de la commande `create_content_pages`
- Amélioration des tests de cette commande
- Correction d'une faute de frappe dans Makefile
Pour que les pages créées soient des enfants directs de la page "Accueil" au lieu de la page "Welcome to your new Wagtail site !"
En modifiant le queryset qui ciblait la page Accueil pour s'assurer que le bon site est sélectionné.
Je pense qu'il y a une confusion dans les sites de Wagtail en local. Par défaut, Wagtail créé un site avec : 
- une root_page "Welcome to your new Wagtail site !"
- un hostname "localhost"
- le champ `is_default_site` à True
Or, dans la fixture '20_cms.json' (capture d'écran ci-dessous), vous pouvez voir  qu'un second site est créé avec : 
- une root_page d'un id 25 (qui correspond à la page "Accueil")
- un hostname …
=> fix: Amélioration de la commande 'create_content_pages'

lemarche/tenders/admin.py
Ajout du champ `contact_phone` dans la recherche de l'admin.
Pour que les admins puissent trouver un besoin à partir de son numéro de téléphone.
En ajoutant le champ `contact_phone` dans les search_fields.
tenders.admin.py
=> feat(Admin): Ajout de 'contact_phone' dans la recherche

lemarche/utils/apis/api_brevo.py
Fix de la synchro Brevo part 1 (gestion du cas où le Tender est None)
=> fix(Brevo): synchro des utilisateurs sans Tender

lemarche/utils/apis/api_brevo.py
AttributeError dans la méthode `create_contact` de api_brevo.py.
En retirant .body du dictionnaire `api_response` qui n'a qu'une clé : `id`
=> fix(Brevo): AttributeError in 'api_brevo.create_contact'

lemarche/siaes/management/commands/sync_with_emplois_inclusion.py
Les OPCS n'ont pas besoin d'être importer
Auparavant importé avec un type non reconnu, elles ne sont pas utilisées pour le moment.
Ajout du kind dans les kinds exclus
Ajustement du log d'erreur pour avoir une erreur générique avec les détails dans l'erreur.
=> fix(Import des emplois): exclusion du type OPCS de l'import

lemarche/api/perimeters/views.py
D'après ce [bug sur sentry](https://inclusion.sentry.io/issues/15061076/) les appels http de type `OPTIONS` aboutissent à des erreurs.
Contrairement aux autres urls de l'API, cette url ne respecte pas un format correct et limite arbitrairement les résultats sans pagination. Les autres verbes http n'ont pas été prévus quand cette modification a été effectuée, menant à des erreurs.
Seul le verbe `GET` est désormais autorisé. L'autre option était de rendre standard cette partie de l'API, mais il aurait fallu changer aussi le code coté client qui consomme cette url.
=> fix: Autoriser seulement les "GET" sur PerimeterAutocompleteViewSet

lemarche/www/pages/views.py
D'après ce [bug sur sentry](https://inclusion.sentry.io/issues/15069221/), il y a une erreur serveur lorsque la vérification csrf échoue lors de la soumission du formulaire de besoin d'achat.
L'intention de départ était sans doute d'entrer dans la condition lors de la dernière étape du formulaire, la condition a été corrigée en fonction.
Je n'ai absolument pas compris quel était le but de ce code, peut être qu'il n'est plus du tout pertinent.
=> fix: Condition invalide pour échapper le CSRF

config/settings/base.py, lemarche/api/emails/tests.py, lemarche/api/emails/views.py
En suivant cette [documentation](https://developers.brevo.com/docs/username-and-password-authentication) l'étape la plus facile pour commencer à sécuriser les webhooks de Brevo est de faire une whitelist de leurs ip.
L'API actuelle, via `InboundParsingEmailView` est totalement ouverte, il est donc théoriquement possible pour un attaquant d'usurper Brevo pour envoyer de nouvelles conversations, d'autant plus que le code est accessible à tous.
Comparer les ips entrantes à celles du réseau d'ip de Brevo
Il est maintenant necessaire pour la prod d'avoir `BREVO_IP_WHITELIST_RANGE` defini pour que les ips soient correctement whitelistées. Je ne sais pas ou documenter ca
=> feat: Inbound email whitelist brevo ips

lemarche/api/emails/serializers.py
Des erreurs sentry https://inclusion.sentry.io/issues/15209997/ , https://inclusion.sentry.io/issues/15209972/ https://inclusion.sentry.io/issues/15596789/ https://inclusion.sentry.io/issues/13943251/ https://inclusion.sentry.io/issues/13943251/
révèlent que certains payload envoyé à `InboundParsingEmailView` ne correspondent pas au `EmailItemSerializer` car certains champs manquent.
Malgré leur [documentation](https://developers.brevo.com/docs/inbound-parse-webhooks#parsed-email-payload) , certains champs du payload manquent alors qu'ils sont indiqués comme présent dans la doc, par exemple `SpamScore` et `Headers`  sont parfois absents alors qu'indiqué comme présents dans la doc. 
Régler le serializer pour accepter que certains champs manquent 
Dans certains issues …
=> fix: Erreurs de serialisation des inbound email

lemarche/siaes/models.py, lemarche/siaes/tests/test_models.py
Allègement de la contrainte de validation sur l'unicité du nom commercial
Pour éviter qu'il y ait une erreur de validation, même quand on ne fait pas de changement sur le nom commercial.
En conditionnant la validation de la contrainte.
=> fix(Structures): Correction sur le contrôle d'unicité du nom commercial

lemarche/conversations/models.py, lemarche/users/tests.py, lemarche/utils/apis/api_brevo.py, lemarche/utils/apis/api_mailjet.py
Retour sur la modification de la façon d'enregistrer les logs d'envoi des mails transactionnels fait lors de la PR #1607 .
La tâche d'envoi étant asynchrone, l'objet template_transactional n'est pas passé correctement et génère des erreurs `InterfaceError`.
Retour sur le code avant modification.
=> fix(Email): Retour sur l'enregistrement du log avant envoi

config/settings/base.py, lemarche/tenders/admin.py, lemarche/tenders/models.py, lemarche/tenders/tests/test_admin.py, lemarche/tenders/tests/test_models.py
Changement de conditions de synchronisation des DDB vers le crm brevo. Au lieu de synchroniser par rapport au montant, on synchronise juste si l'attribut `is_followed_by_us=True`
Certains cas sont compliqué à jugé sur le prix dans un premier temps.
=> fix: Changement de conditions de synchronisation des DDB vers le crm brevo

lemarche/api/datacube/tests.py, lemarche/siaes/factories.py, lemarche/siaes/tests/test_commands.py, lemarche/tenders/models.py, lemarche/tenders/tests/test_models.py, lemarche/www/auth/tests.py
Les tests échouaient parfois de manière inexpliquée sur la CI, comme ici: https://github.com/gip-inclusion/le-marche/actions/runs/12300147620/job/34327607329
Un autre test échoué est https://github.com/gip-inclusion/le-marche/actions/runs/12548544358/job/34987960701, cette fois à cause des factory avec du Fuzzing. La région était générée aléatoirement, matchant aléatoirement le périmètre créé dans le setup. Par ailleurs, la factory générait des données un peu absurde car le département Morbihan pouvait se trouver dans la région Occitanie sans problèmes.
Des tests interdépendants ont été trouvés en changeant l'ordre d’exécution avec `--shuffle` ou `--reverse`. Par exemple,
`pythonb test --reverse lemarche.tenders.tests.test_commands.TestSendAuthorListOfSuperSiaesEmails` échoue avec …
=> fix: Flacky test causé par un mot de passe aléatoire non valide

lemarche/conversations/models.py, lemarche/utils/apis/api_brevo.py, lemarche/utils/emails.py, lemarche/www/dashboard/forms.py, lemarche/www/dashboard/tests.py
Le choix concernant les mails "Communication Marketing" est poussé côté Brevo.
Pour que les emails des campagnes ne partent plus vers les utilisateurs qui ne le souhaitent plus.
Avec l'API Brevo et le champs `email_blacklisted`
Côté Brevo
À noter que la désinscription aux envois de mail faite côté Brevo (en bas des mails par exemple), n'est pas répercuté de notre côté. À voir si il faut faire un script de synchro ou juste aller chercher l'info avant d'afficher les formulaires.
=> feat(Email Notifications): Mise à jour côté Brevo du choix pour les communications Marketing

config/settings/base.py, config/settings/sentry.py, lemarche/utils/logging.py
Limitation des logs envoyés vers Sentry.
Parce que le logger Datadog génère de nombreux logs sur Sentry
On ignore le logger Datadog dans Sentry
J'en ai profité pour offusquer les tokens d'API dans les logs
=> chore(Log): Ajustement de la configuration des logs

lemarche/static/itou_marche/admin.css, lemarche/static/itou_marche/itou_marche.scss, lemarche/templates/includes/_header_env_notice.html, lemarche/templates/layouts/_header.html
Affichage du bandeau d'environnement au-dessus du header.
Il n'apparaissait plus depuis la migration DSFR.
En rajoutant un include de `_header_env_notice.html` dans `_header.html` qui avait été supprimé lors de la migration DSFR.
Avant
Après
- J'ai fix la margin-bottom dans le bandeau de l'admin : 
Avant
Après
=> fix: Affichage du bandeau d'environnement

lemarche/static/js/siae_user_modals.js, lemarche/templates/dashboard/siae_users.html, lemarche/templates/siaes/_siae_user_delete_modal.html, lemarche/templates/siaes/_siae_user_request_cancel_modal.html, lemarche/templates/siaes/_siae_user_request_confirm_modal.html
Correction d'une erreur Javascript qui empêche le rattachement ou la suppression des collaborateurs sur Chrome.
La méthode avec le "dataset" utilisée ne fonctionne que sur Firefox..
L'action des les modals n'est donc pas mise correctement quand l'erreur se produit. 
Création d'un composant Alpine ✨
Les boutons qui déclenchent les popups : 
La popup de confirmation:
La popop de refus:
La popup de suppression:
=> fix(Collaborateurs): Correction du rattachement des collaborateurs sur certains navigateurs

lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
[Issue sentry](https://inclusion.sentry.io/issues/14804431/)
Créer un tender, puis avec son slug ex http://localhost:8000/besoins/ggfdg-admin?siae_id=448gfdg
Paramètres get mal parsés
Erreur 404 si les paramètres GET ne correspondent à aucun véritable id
=> fix: wrong GET ids

lemarche/siaes/management/base_update_api.py, lemarche/siaes/management/commands/update_api_qpv_fields.py, lemarche/siaes/management/commands/update_api_zrr_fields.py
Au départ c'était pour investiguer un bug sentry:  https://inclusion.sentry.io/issues/13810452/?project=4508410616348752&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=2 
avant une éventuelle correction il fallait factoriser le code
Le code était dupliqué entre les 2 commandes
Factoriser le code. L'issue sentry est probablement lié à un paramétrage de `batch_size`, mais pas directement lié au code
=> feat: factorisation d'un copié-collé

lemarche/templates/auth/signup.html, lemarche/www/auth/forms.py
Sur la page d'inscription, en sélectionnant le type acheteur, le widget de choix de secteur d'activité ne s'affichait pas correctement
Pas de widget défini dans le formulaire
=> fix: multiple select widget not displaying correctly

lemarche/api/siaes/serializers.py, lemarche/api/siaes/views.py, lemarche/siaes/models.py
Erreur 500 dans l'api SIAE
L'annotation n'était pas correcte et ne revoyait pas de liste d'instance
Correction de l'attribut `source` dans le champs drf
=> fix: bug sur les secteurs dans l'API des SIAE

lemarche/www/auth/forms.py
Ajout d'un label pour le champ type d'utilisateur dans le formulaire d'inscription.
Un astérisque se baladait tout seul dans le formulaire.
Avant
Après
=> fix: Ajout d'un label pour le type d'utilisateur

lemarche/utils/mtcaptcha.py
Ajout de 'token-duplicate-cal' dans la liste d'erreurs à ignorer
Pour éviter cette erreur sur Sentry.
=> chore: Ajout de 'token-duplicate-cal' dans la liste d'erreurs à ignorer

lemarche/static/itou_marche/components/_dropdown_menu.scss, lemarche/static/itou_marche/itou_marche.scss, lemarche/static/js/dropdown_menu.js, lemarche/templates/dashboard/profile_edit.html, lemarche/templates/favorites/dashboard_favorite_list_detail.html, lemarche/templates/includes/_dropdown_menu.html, lemarche/templates/layouts/_header_nav_primary_items.html, lemarche/templates/layouts/base.html, lemarche/templates/siaes/detail.html, lemarche/templates/tenders/create_step_general.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/www/auth/tests.py, lemarche/www/dashboard/tests.py, lemarche/www/tenders/tests.py
Ajout d'un menu déroulant "Mon espace" et intégration du lien "Notifications" dans ce menu pour les acheteurs et les structures.
Pour organiser le header et être en accord avec la doc dsfr qui recommande 3 liens maximum dans le header.
3 fichiers principaux pour gérer le dropdown : 
- _dropdown_menu.html
- _dropdown_menu.scss
-  dropdown_menu.js
Le JS a été simplifié.
Acheteurs
Structures (l'icône du bouton Déconnexion est maintenant alignée avec les autres)
Autres utilisateurs
- J'ai supprimé tous les imports à AlpineJS pour en garder un dans base.html.
=> feat: Menu déroulant "Mon espace" dans le header

lemarche/templates/auth/signup.html, lemarche/templates/cms/home_page.html, lemarche/templates/dashboard/siae_edit_activities.html, lemarche/templates/dashboard/siae_users.html, lemarche/templates/pages/impact-calculator.html, lemarche/templates/siaes/search_results.html, lemarche/templates/tenders/create_step_detail.html
Bug d'interaction avec les questions des acheteurs et les widgets de selections, comportement erratiques
AlpineJs était importé en double dans certaines pages depuis le merge de cette PR https://github.com/gip-inclusion/le-marche/pull/1662/files#diff-0d77d56646096fea4401f180e76f3bf09831f56706fc9d3e6b80a722915d95f7R68
Suppression des imports spécifiques au pages maintenant que l'import est global
=> fix: doubles imports alpineJs

config/settings/base.py, lemarche/api/authentication.py, lemarche/api/emails/views.py, lemarche/api/networks/tests.py, lemarche/api/perimeters/tests.py, lemarche/api/perimeters/views.py, lemarche/api/sectors/tests.py, lemarche/api/siaes/serializers.py, lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py, lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py, lemarche/api/tests.py, lemarche/templates/api/home.html
Ne plus autoriser les utilisateur à accéder librement à l'API
Les utilisateurs se connectent trop en anonyme, on ne peut pas faire de stats dessus
- Exiger l'authentification sur chaque appel à l'API
- Modifier la documentation en conséquence
=> feat: Authentification obligatoire sur l'API

lemarche/api/siaes/serializers.py, lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py, lemarche/siaes/models.py
Les siaes étaient dupliqués dans la liste de l'API, et leur fiche de détail n'était plus accessible
Une mauvaise annotation en était la cause
=> fix: duplication des siae dans l'API

lemarche/api/siaes/tests.py, lemarche/api/siaes/views.py
Lorsque du texte était passé à l'API au lieu d'un id, cela générait une erreur 500.
Arguments pas parsés correctement
Retour aux méthodes de base de l'API qui prenait en charge les arguments, les optimisations étant déjà effectuées au niveau du queryset.
=> fix: Prise en charge des ids malformés dans l'API des siae

lemarche/www/auth/tests.py, lemarche/www/auth/views.py
L'onboarding avec rendez vous était désactivé tous les Vendredi, finalement ce n'est pas la peine, la fonctionnalité sera permanente.
Rollback des changements
=> chore: Remove the behavior that cuts onboarding on Friday

config/settings/base.py, lemarche/siaes/management/commands/update_api_entreprise_fields.py, lemarche/siaes/tests/test_commands.py, lemarche/utils/apis/api_recherche_entreprises.py
Mise à jour des champs "api_entreprise_*" avec l'API de Recherche Entreprise
API Entreprise a été mise à jour et nous n'avons pas les accès à la nouvelle version. La PR #1599 ne peut donc pas être mise en production.
L'API Recherche Entreprise est quant à elle ouverte. 
Appel en GET à l'API de Recherche Entreprise
L'ajout de `from sentry_sdk.crons import monitor` permettra de suivre la bonne exécution de la tache planifiée.
Prochaine étape :
- mettre à jour aussi les données anciennes, pas uniquement que les structures pour lesquelles le champs n'a jamais été renseigné.
- gérer le quota d'appel à l'API
=> chore(API Entreprise): Mise à jour des données via l'API Recherche Entreprise

lemarche/users/validators.py, lemarche/www/auth/forms.py, lemarche/www/auth/tests.py, lemarche/www/tenders/forms.py
Des acheteurs s'inscrivaient avec le mails perso, problèmes pour les contacter
Validation de l'extension des mails et rejet si appartenant a des fournisseurs liés généralement aux particuliers
=> feat: Interdiction des mails personnels pour l'inscription des acheteurs

lemarche/tenders/migrations/0098_update_rejected.py
Une migration pour mettre à jour le statut des anciens tenders qui avant la PR https://github.com/gip-inclusion/le-marche/pull/1596 étaient préfixés par "HS" pour les tagger comme hors sujet
=> chore: Migrer les DDB préfixées par HS en statut "rejeté"

lemarche/siaes/models.py, lemarche/templates/dashboard/siae_users.html, lemarche/www/dashboard_siaes/views.py
Seul le dernier gestionnaire était contacté pour approuver une demande de rattachement à une structure.
Désormais, tous les gestionnaires recevront le mail et pourront approuver ou non la demande.
=> chore: Envoyer le mail de rattachement à tous les gestionnaires

lemarche/templates/tenders/admin_change_form.html, lemarche/tenders/admin.py
Désactiver les boutons "Valider" si aucune structure concernée
Pour éviter les validations inutiles par erreur.
En utilisant le nombre de structures concernées.
Suppression de la section concernant l'ancien matching IA.
=> feat(Admin): Désactivation du bouton "Valider" si aucune SIAE ne correspond

lemarche/siaes/management/commands/data/mapping_api_entreprise_forme_juridique.csv, lemarche/siaes/management/commands/update_api_entreprise_fields.py
Ajout de la forme légale 5658 "SA coopérative de production (SCOP) à directoire" ajouter le 1er septembre 2022 -> https://www.insee.fr/fr/information/2028129
La commande `update_api_entreprise_fields` échoue car le code de la forme juridique 5658 n'est pas reconnu.
Ajout dans le fichier de correspondance.
Ajout d'un avertissement quand la commande est lancée sans le "wet-run".
=> chore(API Entreprise): Ajout de la forme juridique "SCOP à directoire"

lemarche/siaes/management/commands/sync_with_emplois_inclusion.py, lemarche/siaes/tests/test_commands.py
Ajout d'info dans l'erreur de duplication de nom commercial durant la synchro avec le C1
Pour mieux comprendre les cas en erreur et savoir si il s'agit de mis à jour ou de création.
En ajoutant le dict complet dans le log.
=> chore(Sync C1): Ajout d'info dans le log pour mieux comprendre les erreurs de duplication de nom commercial

config/settings/base.py
Ajout de la configuration du "bearer token" dans la configuration de drf-spectacular.
Pour permettre aux usagers de tester directement en ligne avec leur jeton d'API.
Configuration SPECTACULAR_SETTINGS.
=> feat(API Swagger): Possibilité d'ajouter son token dans Swagger 

.github/auto_assign.yml
Mise à jour de la liste des auto assign Github
L'autoassign semble ne plus fonctionner
Mise à jour de auto_assign.yml
=> chore: Mise à jour de la liste des auto assign Github

content_manager/management/commands/create_demo_pages.py, lemarche/companies/factories.py, lemarche/conversations/factories.py, lemarche/cpv/factories.py, lemarche/favorites/factories.py, lemarche/labels/factories.py, lemarche/networks/factories.py, lemarche/notes/factories.py, lemarche/perimeters/factories.py, lemarche/sectors/factories.py, lemarche/siaes/factories.py, lemarche/siaes/tests/test_commands.py, lemarche/tenders/factories.py, lemarche/tenders/tests/test_matching.py, lemarche/tenders/tests/test_models.py, lemarche/users/factories.py
Les tests aléatoires ont provoqués beaucoup de flacky tests difficiles à résoudre, sans apporter d'avantages particuliers. Le fuzzy testing peut être utilise pour détecter de nouveau cas à tester, mais pas adapté aux tests unitaires.
Dernier cas détecté dans `CompanyQuerysetTest`, la factory `CompanyFactory` était instancié deux fois, et, très rarement, le nom aléatoire choisit était le même, levant une erreur d'intégrité.
Plutôt que de devoir gérer au fil de l'eau des flacky tests difficiles à remonter, supprimer toute notion d'aléatoire dans les tests pour qu'ils soient reproductibles.
=> chore: Suppression du fuzzy testing

lemarche/tenders/admin.py
Les champs "S cliquées", "S Vues" et "S Cliquées ou Vues" n'étaient pas utilisés par les admins, ils ont donc été supprimés pour ne pas surcharger la page.
=> chore: Suppression de compteurs de structures dans admin de besoins

lemarche/siaes/management/commands/data/mapping_api_entreprise_forme_juridique.csv
Ajout d'une forme légale.
Parce qu'elle manque lors la mise à jour des champs de l'API Recherche Entreprise (commande `update_api_entreprise_fields`)
Ajout uniquement de celle manquante car beaucoup de formes juridiques ne seront jamais utilisées dans notre contexte et je ne suis pas sûr de savoir toutes les classer en SA, SCOP etc..
=> chore(API Entreprise): Ajout de la forme juridique "Ordre professionnel ou assimilé"

lemarche/tenders/management/commands/update_tender_count_fields.py, lemarche/tenders/models.py, lemarche/tenders/tests/test_commands.py
La mise à jour des compteurs ne se fait désormais que pour les besoins non clôturés et clôturés récemment (moins de 30 jours).
Des indisponibilités nocturnes laissent à penser que cette tâche est trop lourde.
Restriction des besoins à mettre à jour.
J'ai mis un délai de 30 jours pour garder une marge, notamment lorsque le cron passe le lendemain de la clôture.
=> chore: Mise à jour des compteurs uniquement des besoins en cours ou expiré il y a moins d'un mois

lemarche/templates/tenders/create_step_confirmation.html
Pour certaines personnes, sur le formulaire de DDB au moment de cliquer sur "Publier et diffuser" une erreur CSRF se déclenchait. Après examen, le payload POST contenait seulement `{"message":""}`, sans aucun rapport avec le formulaire, et donc sans le token CSRF.
Une histoire de cache ?
Du code javascript, non documenté et d'une utilité pour le moins mystérieuse a été supprimé, sans suppression apparente de fonctionnalité. Les tests réalisés sans ce code ne donnent pas sur des erreurs CSRF.
=> fix: CSRF error des DDB

lemarche/www/tenders/forms.py, lemarche/www/tenders/views.py
Les paramètres GET passés à la vue `TenderDetailView` générait des traces d'erreurs coté serveur. 
Création d'un formulaire non rendu utilisé pour parser correctement les arguments, et faire correspondre l'instance du modèle avec la clef primaire.
=> fix: Correction bug des paramètres GET de la vue détail de DDB

lemarche/templates/tenders/_detail_contact_click_confirm_modal.html, lemarche/templates/tenders/_detail_cta.html, lemarche/tenders/admin.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Quand un utilisateur répondait aux questions, il pouvait faire un retour en arrière avec le navigateur et essayer de soumettre une deuxième fois, déclenchant une erreur 500 à cause d'une contrainte d'intégrité.
Une transaction et mise en place pour annuler toutes les questions en cas d'erreur, et une redirection avec un message d'erreur est effectuée au lieu de l'erreur 500.
=> fix: Erreur du formulaire de réponse aux questions

lemarche/api/inclusive_potential/constants.py, lemarche/api/inclusive_potential/serializers.py, lemarche/api/inclusive_potential/tests.py, lemarche/api/inclusive_potential/views.py
Ajout de calcul de la dépendance économique à partir du budget de l'acheteur et de la moyenne des chiffres d'affaires des structures concernées.
Le chiffre d'affaire d'un fournisseur est un critère pour les acheteurs privés et est une contrainte pour les marchés publics.
En divisant le budget par le chiffre d'affaire moyen.
=> feat(API): ajout de la notion de dépendance économique à l'évaluation du potentiel inclusif

lemarche/cms/tests/test_commands.py, lemarche/crm/management/commands/crm_brevo_sync_companies.py, lemarche/crm/tests.py, lemarche/siaes/tests/test_commands.py, lemarche/tenders/tests/test_commands.py, lemarche/utils/tests_commands.py
Les commandes django produisent beaucoup d'écriture en sortie standard, cette PR à pour but de les masquer lors des tests.
Il faut aussi supprimer les vieux prints qui trainent, qui sont mélangés avec les logs, les `stdout`...
Cela pollue la lecture des tests, rend plus difficile leur lecture
Rediriger la sortie vers `StringIO()`
=> chore: Masquer les sorties des commandes lors des tests

lemarche/api/inclusive_potential/constants.py, lemarche/api/inclusive_potential/tests.py, lemarche/api/inclusive_potential/utils.py, lemarche/api/inclusive_potential/views.py
Ajout du nombre moyen d'employé en insertion et permanent.
Pour étoffer le potentiel inclusif de chiffre d'ETP (Équivalent temps plein).
Nombre d’ETP insertion de l’ensemble des fournisseurs potentiels / nombre de fournisseurs potentiels
Avec prise en compte de `C2 ETP` pour les SIAE (EI,ETTI,AI et ACI) et `Employees Insertion` pour les EA/EA et EATT
J'en ai profité pour séparer les calculs de la vue.
=> feat(API Potentiel inclusif): Ajout du nombre d'employés moyen

lemarche/siaes/admin.py
Suppression du lien
Erreur depuis la PR #1714 :
`Level: Error
Reverse for 'sector_sector_changelist' not found. 'sector_sector_changelist' is not a valid view function or pattern name.`
Suppression du lien qui mène nulle part.
=> fix(admin): Suppression du lien défaillant sur le compteur de secteur

lemarche/tenders/models.py, lemarche/www/tenders/tests.py
Mise à jour de la date des transactions pour toutes les réponses
Certains changements d'état ne mettent pas à jour la date.
Mettre à jour pour tout changement, même si le champ est `None` ou `False`.
=> fix(Dépôt de besoin): Mise à jour de la date des transactions pour toutes les réponses

lemarche/www/pages/views.py
Ce logger n'est plus utile car l'erreur à été corrigée
=> chore: Suppression du logger de CSRF

lemarche/tenders/models.py, lemarche/tenders/tests/test_models.py, lemarche/users/models.py, lemarche/www/tenders/forms.py
Certains comptes avec beaucoup de besoins mettaient très longtemps à charger (~30 sec)
Les modèles des besoins comportent trop de colonnes, certaines assez lourdes. Des requètes `count()` prenaient en compte toutes les colonnes du modèle.
Effectuer les requêtes count seulement en sélectionnant les colonnes id.
=> fix: Chargement des comptes structures très lents

lemarche/api/tenders/tests.py, lemarche/api/tenders/views.py, lemarche/fixtures/django/22_tender_instructions.json
Pour l'api l'instruction n'était pas dans la bonne catégorie. Approch crée des sourcings (`PROJ`) et des appels d'offres (`TENDER`).
Un bloc avec une exception à été créé pour éviter de bloquer la création des tenders via l'api s'il n'y a pas la bonne "notice"
=> fix: Bug d'instruction de DDB manquant pour l'API

lemarche/www/auth/forms.py
La validation des emails dupliqués faisait qu'ils n'était plus présent dans `cleaned_data`
=> fix: L'inscription avec une adresse déjà enregistrée causait un bug

config/settings/base.py
Suppression du formatage automatique des nombres.
Le formatage des nombres avec des espaces (introduit dans la PR #1742 ) génère des erreurs dans les URL composées dans les templates.
Suppression du formatage global pour éviter tout effet de bord.
=> fix: Correction de l'affichage des coordonnées sur un dépôt de besoin

lemarche/www/dashboard/tests.py
Correction des tests sur la vue
La "locale" utilisée n'est pas la même dans les tests, donc même si les nombres apparaissent bien sur la page avec le navigateur, les tests ne passaient plus.
En utilisant le contexte plutôt que le rendu de la réponse.
=> fix: Correction des tests sur le formatage des nombres sur la page de visualisation de la part d'achats inclusifs

lemarche/www/dashboard_favorites/tests.py, lemarche/www/dashboard_favorites/views.py
Un lookup de prefetch n'avait pas été mis à jour, et ce n'etait pas detecté par les tests actuels qui ont été mis à jour en conséquence.
=> fix: Bug sur l'affichage de la liste des favoris

lemarche/fixtures/django/23_purchases.json
Ajout de données fictives d'achats.
Pour avoir des données et visualiser pleinement la page "Ma part d'achat inclusif" sur staging et sur nos environnements de développement.
Avec des fixtures
=> feat: Ajout de données factices pour les démos de la page "Ma part d'achat inclusif"

lemarche/siaes/models.py, lemarche/templates/tenders/siae_interested_list.html, lemarche/utils/export.py, lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Un popup permet à l'acheteur de sélectionner quelles colonnes il souhaite exporter, et sous quel format de fichier.
Les colonnes à sélectionner sont affichées sous forme de tags, et le formulaire de filtrage est aussi actif pour filtrer les données téléchargées.
Naturellement, le formulaires avec `action="get"` ne prennent pas en compte les paramêtres get fournis dans l'url. Un script a été créer pour récupérer ces champs de filtrations et les copier en hidden input dans le formulaire de téléchargement.
Des conflits de javascript sont présents au niveau des tags, il ne m'a pas été possible de désactiver le js du dsfr au niveau des tags bien qu'il ne soit pas nécessaire à leur fonctionnement.
Au final cela marche dans notre cas car l'information est bien propagée du tag vers le champs …
=> feat: Sélection des colonnes exportables

lemarche/templates/siaes/search_results.html
Correction du champs autocomplete localisation qui ne s'affiche plus.
Les ids ont été changé depuis #1687 .
Remplacement par les nouveaux ids .
=> fix(Recherche): Correction du champs localisation

.github/workflows/release-please.yml
Mise à jour de la github action
Le projet a été migré : https://github.com/google-github-actions/release-please-action/tree/v4/?tab=readme-ov-file#migration
et les derniers job ont échoué :
=> chore(CI): Mise à jour du dépôt Please Release

lemarche/templates/403.html, lemarche/templates/403_csrf.html, lemarche/templates/404.html, lemarche/templates/429.html, lemarche/www/pages/urls.py
Ajout d'un template pour l'erreur 429 (Too Many Requests).
Probablement des tentatives de DDOS insignifiantes, mais génère des erreurs à cause du template.
Ajout d'un template.
Fixe au passage l'affichage des pictogrammes :
=> fix: Ajout du template pour les erreurs 429

lemarche/siaes/models.py, lemarche/templates/tenders/_detail_admin_extra_info.html, lemarche/templates/tenders/_detail_side_infos_author.html, lemarche/tenders/models.py, lemarche/utils/urls.py, lemarche/www/tenders/tasks.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Ajout d'une variable pour le template de mail contenant le lien direct vers le téléchargement direct de l'export xls.
Pour améliorer la visibilité et la compréhension par les acheteurs des retours des fournisseurs inclusifs intéressés par leur projet d’achat.
Génération d'un lien direct en utilisant les paramètres du formulaire SiaeSelectFieldsForm et en l'ajoutant aux templates de mail envoyé à l'auteur d'un dépôt de besoin (lors de la validation et quand des structures montrent leur intérêt).
Suppression du filtre sur la date d'envoi de mail qui créait un décalage depuis que l'envoi par lot est en place. On pouvait envoyer : "64 structures concernées" dans le mail alors que dans l'interface de suivi, il y avait qu'un lot (10 structures par défaut)  d'afficher dans les "structures …
=> feat(Dépôt de besoin): Envoi d'un lien direct vers l'export xls des structures

lemarche/siaes/models.py, lemarche/templates/siaes/_card_tender.html, lemarche/www/tenders/forms.py, lemarche/www/tenders/tests.py, lemarche/www/tenders/urls.py, lemarche/www/tenders/views.py
Le modèle Tender dispose des champs `location` (qui contient un périmètre, utilisé par le formulaire de dépôt de besoin), un champ `is_country_area`, utilisé par le formulaire, mais aussi `perimeters` et `distance_location`, qui sont utilisés seulement par l'API.
=> feat(Tenders): Afficher les fournisseurs locaux

lemarche/siaes/models.py, lemarche/templates/siaes/_annuaire_entreprises_button.html, lemarche/templates/siaes/_useful_infos.html
Un lien sous forme de bouton est affiché pour rediriger vers https://annuaire-entreprises.data.gouv.fr/donnees-financieres/ directement avec le bon SIREN.
Le bouton est affiché seulement pour les structures de types entreprises, pas les associations.
=> feat: Bouton santé financière des structures

lemarche/companies/admin.py
Suppression de la possibilité d'ajouter des "correspondances" dans l'admin, seule la commande doit pouvoir le faire.
=> fix(admin): Suppression de la possibilité d'ajouter dans l'admin des correspondances entre les références clients et les entreprises

lemarche/utils/remove_beta_redirect_middleware.py, lemarche/utils/tests/tests_remove_beta_redirect_middleware.py
L'accueil de l'API n'est plus mis en forme depuis le changement de domaine.
La page en elle-même n'est pas redirigé, mais les css et js, si.
Redirection de l'accueil API comme les autres pages, https://lemarche.inclusion.beta.gouv.fr/api/ > https://lemarche.inclusion.gouv.fr/api/ 
Cassée : 
Normale :
=> fix(API): correction de la mise en forme de l'accueil API

lemarche/www/dashboard_siaes/views.py
Une erreur 500, transparent pour l'utilisateur, était déclenchée quand on cliquait sur "Ajouter une activité", au moment ou le dropdown était sur sa valeur par défaut "Selectionnez un secteur"
=> fix: Bug non bloquant sur la selection des activités d'un structure

lemarche/templates/tenders/siae_interested_list.html, lemarche/www/tenders/forms.py
Certains champs sont préselectionnés pour l'export des fournisseurs
**Champs pré-sélectionnés par défaut**
- ✅ Raison sociale
- ✅ SIRET
- ✅ Réponses aux questions
- ✅ Coordonnées de contact : Prénom, Nom, Email, Téléphone
=> feat: Préselection de champs pour l'export de fournisseurs

lemarche/siaes/models.py, lemarche/templates/siaes/_card_tender.html, lemarche/templates/tenders/siae_interested_list.html, lemarche/www/tenders/tests.py, lemarche/www/tenders/views.py
Un nouvel onglet qui liste les fournisseurs ayant explicitement indiqué leur désintérêt pour le projet d’achat.
On affiche la raison du désintérêt dans le détail de la carte
=> feat: Onglet "Pas intéressé" pour les projets d'achats acheteurs
