- README.md
- env.default.sh
- quelques petites modifications de style
- quelques ajouts de configuration
> Mise à jour du README

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
Ajout du déploiement automatique vers clever cloud
> :octopus: github actions implementation

- README.md
- config/urls.py
- lemarche/api/urls.py
- lemarche/templates/frontend/home/home.html
- préfixe de l'API avec `/api`
- enlève le `s` à siaes
> API : préfixe /api

- .github/pull_request_template.md
- CHANGELOG.md
https://github.com/betagouv/itou/blob/master/.github/pull_request_template.md
> Ajout d'un template de PR

- lemarche/www/siae/forms.py
Toujours mettre les secteurs d'activité "Autre" en dernier
> Formulaire de recherche : toujours mettre les secteurs Autre à la fin

- lemarche/static/itou_marche/itou_marche.scss
- lemarche/static/itou_marche/sections/_hp.scss
- lemarche/templates/auth/logged_out.html
- lemarche/templates/auth/login.html
- lemarche/templates/auth/password_reset.html
- lemarche/templates/auth/password_reset_complete.html
- lemarche/templates/auth/password_reset_confirm.html
- lemarche/templates/auth/password_reset_sent.html
- lemarche/templates/auth/signup.html
- lemarche/templates/pages/contact.html
- lemarche/www/auth/forms.py
- lemarche/www/pages/forms.py
Mise en forme des pages contact, login/logout, reset password et signup au format du theme itou 
Pour les yeux
> Update static pages

- config/settings/base.py
- config/settings/dev.py
- docker/dev/entrypoint.sh
- lemarche/templates/api/home.html
- lemarche/templates/auth/login.html
- lemarche/templates/auth/signup.html
- lemarche/templates/layouts/_footer.html
- lemarche/templates/layouts/_header.html
- lemarche/templates/layouts/base.html
- lemarche/templates/siae/search_results.html
- lemarche/www/pages/views.py
- lemarche/www/siae/views.py
- poetry.lock
- pyproject.toml
- requirements/dev.txt
- sous docker, faire en sorte que les modifs SCSS soient répercutées tout de suite
- améliorations des views et des templates
> Fix pour le Docker (SCSS)

- lemarche/templates/layouts/_footer.html
- lemarche/templates/layouts/_header.html
- lemarche/templates/layouts/base.html
- lemarche/templates/pages/home.html
Mise a jour du contenu de la hp et ajout d'un bouton newlstter / mailjet dans le menu
Pour etre iso avec cocorico
> update wording & add item nl to nav

- lemarche/static/itou_marche/sections/_inclusion.scss
- lemarche/templates/pages/cest-quoi-linclusion.html
Update page inclusion
Fixer quelques bricoles dans le css
> update page inclusion

- lemarche/templates/layouts/base.html
Ajout du script tarte au citron et check du rendu css
Parcque c'est utile
> add tac script & check css

- lemarche/templates/dashboard/profile_edit.html
- lemarche/templates/dashboard/siae_adopt_confirm.html
- lemarche/templates/dashboard/siae_edit_base.html
- lemarche/templates/dashboard/siae_edit_info_contact.html
- lemarche/templates/dashboard/siae_edit_offer.html
- lemarche/templates/dashboard/siae_edit_other.html
- lemarche/templates/dashboard/siae_edit_presta.html
- lemarche/templates/dashboard/siae_search_by_siret.html
- lemarche/www/dashboard/forms.py
- lemarche/www/dashboard/views.py
Améliorations des pages de formulaires de modifications de sa structure (suite aux premiers tests de l'équipe)
> Dashboard utilisateur : bug fix et retours

- lemarche/templates/auth/signup_welcome_email_body.txt
- lemarche/www/auth/tasks.py
- lemarche/www/auth/views.py
- lemarche/www/pages/views.py
- envoi d'un email post-inscription
- afficher un message sur la home post-inscription à la newsletter
> Emails post-inscription

- lemarche/templates/layouts/_header.html
- lemarche/templates/layouts/_newsletter_button.html
- mise à jour du contenu du burger (interface mobile)
- bougé le bouton newsletter dans son propre template
- cleanup
> Cleanup du header

- lemarche/templates/403.html
- lemarche/templates/404.html
- lemarche/templates/500.html
- lemarche/www/pages/urls.py
> Templates des pages d'erreurs

- clevercloud/review-app-after-success.sh
- config/settings/base.py
- lemarche/api/networks/views.py
- lemarche/api/perimeters/filters.py
- lemarche/api/perimeters/serializers.py
- lemarche/api/perimeters/tests.py
- lemarche/api/perimeters/views.py
- lemarche/api/sectors/views.py
- lemarche/api/siaes/views.py
- lemarche/api/urls.py
- lemarche/static/js/perimeter_autocomplete_field.js
- lemarche/templates/api/home.html
- lemarche/utils/tests.py
- lemarche/utils/tracker.py
- Pouvoir chercher une ville par son code postal
- Marche aussi pour le département
- Créé un endpoint API dédié
> Recherche géographique par code postal

- lemarche/fixtures/django/06_networks.json
- lemarche/fixtures/django/07_siae_networks.json
- lemarche/fixtures/tests.py
- lemarche/networks/factories.py
- lemarche/networks/models.py
- lemarche/perimeters/factories.py
- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
- lemarche/www/siaes/views.py
- rajoute le filtre par réseau dans la recherche
-
> Recherche par réseau

- lemarche/static/itou_marche/components/_multiselect.scss
- lemarche/static/itou_marche/sections/_siae.scss
- lemarche/static/js/kind_multiselect_field.js
- lemarche/static/js/sector_multiselect_field.js
- lemarche/templates/layouts/base.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
Actuellement la recherche par type de structure est un select.
On le passe ici en multiselect (comme avant dans Cocorico)
> Recherche multiple par type de structure

- lemarche/siaes/models.py
- lemarche/templates/auth/login.html
- lemarche/templates/auth/signup.html
- lemarche/templates/dashboard/home.html
- lemarche/templates/dashboard/profile_edit.html
- lemarche/templates/dashboard/siae_edit_info_contact.html
- lemarche/templates/dashboard/siae_search_adopt_confirm.html
- lemarche/templates/dashboard/siae_search_by_siret.html
- lemarche/templates/layouts/base.html
- lemarche/templates/pages/home.html
- lemarche/www/auth/forms.py
- lemarche/www/auth/tests.py
- lemarche/www/auth/views.py
- lemarche/www/dashboard/forms.py
Inscription
- Mettre le champ email en lowercase pour éviter les erreurs
- Laisser connecté la personne
- Rediriger directement vers son profil si SIAE
Connexion
- Afficher un message différencié si l'utilisateur a un mot de passe vide (provenant de la migration)
> Améliorer les étapes d'inscription

- lemarche/templates/siaes/search_results.html
- lemarche/utils/export.py
- lemarche/www/siaes/views.py
- poetry.lock
- pyproject.toml
- requirements/dev.txt
- requirements/staging.txt
- Ajout d'une option XLS au bouton "Télécharger la liste"
Le format CSV n'est pas bien maitrisé par les utilisateurs.
Avant / Après
> Option pour télécharger les Siae au format Excel

- lemarche/static/itou_marche/base/_custom.scss
- lemarche/templates/pages/stats.html
- évite que le header cache le bloc de texte avec balise
- répare le meta title de la page statistiques
> Répare quelques soucis d'affichage

- config/settings/dev.py
Ajout d'un setting pour pouvoir faire tourner l'application sous windows.
> Ajout de settings pour les utilisateurs windows

- Makefile
- scripts/deploy_prod.sh
Ajout d'un script pour le déploiement pour éviter les erreurs de procédure.
> Ajoute d'un script pour le déploiement

- lemarche/api/siaes/views.py
- lemarche/siaes/models.py
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
- lemarche/www/siaes/views.py
- Utiliser les count au lieu de jointures pour l'annotation
- Généraliser les prefetch_related pour diminuer le nombre de requêtes SQL
> Optimizations sur la recherche

- lemarche/templates/includes/_tracker_itou.html
- lemarche/templates/includes/_user_type_modal.html
- lemarche/templates/pages/decouvrir-inclusion.html
- lemarche/templates/pages/partenaires.html
- lemarche/templates/siaes/search_results.html
- Bouge la modal dans son propre template
- Afficher la modale sur les template des pages Partenaires & Découvrir l'insertion
Pour mieux qualifier nos utilisateurs anonymes
> Améliorations sur la modale "type d'utilisateur"

- lemarche/favorites/admin.py
- lemarche/networks/admin.py
- lemarche/perimeters/admin.py
- lemarche/sectors/admin.py
- lemarche/siaes/admin.py
- lemarche/users/admin.py
- lemarche/users/models.py
- lemarche/users/tests.py
Rajoute des filtres, des liens, de la recherche, etc 
(voir les commits)
> Améliorations dans l'admin

- lemarche/perimeters/management/commands/README.md
- lemarche/siaes/management/commands/update_counts.py
Documentation de scripts qui peuvent être utiles
Les commiter dans le code, au lieu de les avoir documentés ailleurs
> Ajout de scripts dans le code

- clevercloud/cron.json
- clevercloud/siaes_export_all_siae_to_file.sh
- config/settings/base.py
- lemarche/siaes/management/commands/export_all_siae_to_file.py
- lemarche/utils/export.py
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/views.py
Accélérer le téléchargement du fichier de toutes les structures.
Lorsqu'un utilisateur souhaite télécharger toute la liste de nos structures, le temps de génération du fichier (XLS ou CSV) est long (plus de 20 secondes).
Tâche dans la nuit pour générer le fichier des structures
> Exporter régulièrement toutes les structures dans un fichier

- lemarche/static/itou_marche/components/_modal.scss
- lemarche/static/itou_marche/itou_marche.scss
- lemarche/static/itou_marche/sections/_siae.scss
- lemarche/templates/auth/_login_or_signup_modal.html
- lemarche/templates/auth/signup.html
- lemarche/templates/includes/_user_type_modal.html
- lemarche/templates/pages/valoriser-achats.html
- lemarche/templates/siaes/_card_search_result.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/siaes/search_results.html
- lemarche/www/auth/tests.py
- lemarche/www/auth/views.py
- Afficher une modale pour les utilisateurs anonymes qui souhaitent se servir d'une fonctionnalité "premium"
- Fonctionnalités premium : télécharger la liste ; mettre en favoris ; voir les contacts
- Pousser à la création de compte
- Clarifier la valeur ajoutée du produit
> Ajout d'une modale explicative sur la création de compte

- lemarche/static/js/favorite_item_add.js
- lemarche/templates/siaes/_card_search_result.html
- lemarche/templates/siaes/_favorite_item_add_modal.html
- lemarche/templates/siaes/_favorite_modal.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/views.py
- enlevé une phrase dans la modale
- renommé la modale d'ajout d'une structure
- bougé un script dans un fichier dédié
> Favoris : cleanup des modales

- lemarche/templates/auth/_login_or_signup_modal.html
Modale freemium : 
- titre avant : "Profitez du Marché en totalité"
- titre maintenant : "Profitez gratuitement du Marché"
> Ajouter la mention de gratuité dans le titre de la modale

- lemarche/siaes/admin.py
- lemarche/users/admin.py
- ajout de SiaeUserInline sur la page admin d'un utilisateur
- ajout de liens pour accéder directement aux objets (la structure, les utilisateurs)
> Améliorations du rendu des SiaeUserInline dans l'admin

- lemarche/static/js/territory_multiselect_field.js
- lemarche/templates/layouts/base.html
- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
Pouvoir filtrer les structures par "Territoires spécifique" : QPV & ZRR
> Recherche : intégrer les filtres QPV & ZRR

- CHANGELOG.md
- Mise à jour du changelog pour la fin du sprint
- Utilisation de https://calver.org/ pour simplifier le versioning
> Mise à jour du changelog (sprint 2022.2)

- config/settings/base.py
- lemarche/templates/dashboard/profile_favorite_list_detail.html
- lemarche/templates/pages/home.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/siaes/search_results.html
- lemarche/utils/settings_context_processors.py
Nouveau lien typeform pour les demandes groupées (à partir d'une liste d'achat)
- refactoring du base.py (remonté certains paramètres plus haut)
- basculé les liens typeform dans le base.py
> Nouveau typeform pour les demandes groupées

- lemarche/siaes/admin.py
> Admin : ajout des champs ZRR sur le page structures

- lemarche/static/itou_marche/base/_custom.scss
- lemarche/static/itou_marche/sections/_siae.scss
- lemarche/templates/dashboard/siae_edit_base.html
- lemarche/templates/dashboard/siae_edit_users.html
- lemarche/www/dashboard/tests.py
- lemarche/www/dashboard/urls.py
- lemarche/www/dashboard/views.py
Onglet qui liste le(s) collaborateur(s) de la structure.
- informer les utilisateurs
- préparer à la fonctionnalité de gestion/invitation des collaborateurs
> Ajouter un onglet collaborateurs au formulaire de modification de sa structure

- CHANGELOG.md
Liste des modifications des 2 dernières semaines
> Mise à jour du changelog (2022-3)

- lemarche/siaes/models.py
- lemarche/static/js/user_request.js
- lemarche/templates/dashboard/profile_favorite_list_detail.html
- lemarche/templates/dashboard/siae_edit_base.html
- lemarche/templates/dashboard/siae_edit_users.html
- lemarche/templates/dashboard/siae_user_request_email_body.txt
- lemarche/templates/dashboard/siae_user_request_response_false_email_body.txt
- lemarche/templates/dashboard/siae_user_request_response_true_email_body.txt
- lemarche/templates/siaes/_user_request_cancel_modal.html
- lemarche/templates/siaes/_user_request_confirm_modal.html
- lemarche/www/dashboard/forms.py
- lemarche/www/dashboard/tasks.py
- lemarche/www/dashboard/urls.py
- lemarche/www/dashboard/views.py
Suite de https://github.com/betagouv/itou-marche/pull/223
Voir https://www.notion.so/En-tant-que-Vendeur-je-veux-g-rer-les-collaborateurs-de-ma-structure-d21c4b91c1d048c5abd2a4b0bde0f6e5
- Afficher la liste des demandes de rattachements
- Modale pour confirmer (ou annuler) le rattachement
- mail de relance après 3j
- annuler la requête après 8j
- fignolage css des pages & des emails
> Collaborateurs (3/6) : pouvoir confirmer/annuler une demande de rattachement à sa structure

- lemarche/templates/siaes/_card_home.html
- lemarche/templates/siaes/_card_search_result.html
- ouvrir les fiches sutructures dans un nouvel onglet (depuis la page de recherche)
- quelques mini fix de tabulation
> Le clic sur une fiche ESI ouvre un nouvel onglet

- lemarche/static/itou_marche/sections/_siae.scss
- lemarche/templates/siaes/detail.html
> Simplifier le CSS du bouton "Afficher les coordonnées"

- CHANGELOG.md
Liste des modifications des 2 dernières semaines
> Mise à jour du changelog (2022-5)

- lemarche/templates/tenders/create.html
- lemarche/www/tenders/views.py
- Fix de l'envoi de formulaire de création de besoins suite au déplacement de la modal
- Fix de la sauvegarde des besoins (duplication du save nécessaire)
> Fix de petits bug sur la création de besoins

- lemarche/templates/auth/_login_or_signup_modal.html
- lemarche/templates/pages/home.html
- lemarche/tenders/admin.py
- lemarche/tenders/models.py
- lemarche/tenders/tests.py
- rajoute le modale "freemium" lorsque un utilisateur anonyme clique sur "Publier un besoin d'achat" sur la page d'accueil
- why ? pousser à l'inscription + expliciter un peu plus le bouton
- fix/modif sur `Tender.in_sectors()`
- fix dans Tender admin (le filtre par perimeter faisait ramer la page)
- quelques fix d'indentation
> Dépot de besoin 6/X : afficher la modale freemium pour les utilisateurs non connectés

- lemarche/siaes/models.py
- lemarche/templates/dashboard/siae_edit_info.html
- lemarche/templates/siaes/detail.html
Modifications de la fiche structure : 
- design
- affichage de nouveaux champs
- réorganisation
> Réorganisation de la fiche structure

- lemarche/templates/auth/login.html
- lemarche/templates/auth/signup.html
- lemarche/templates/dashboard/_siae_card_home.html
- lemarche/templates/dashboard/home.html
- lemarche/templates/layouts/_header.html
- lemarche/templates/pages/home.html
- lemarche/templates/siaes/_card_search_result.html
Ajout d'ids sur des `<a>` et `<button>`
Pour tracker l'usage
> Ajout d'IDs sur certains boutons

- lemarche/templates/layouts/_header.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/siaes/search_results.html
- lemarche/templates/tenders/create.html
- bouton "Afficher les coordonnées" (sur la fiche structure) en vert :green_heart: 
- quelques fix sur les templates
- cacher le bouton "Valoriser vos achats" dans le header si l'utilisateur est de type SIAE
> Mettre le bouton "Afficher les coordonnées" en vert

- lemarche/www/auth/tests.py
- lemarche/www/auth/views.py
> Connexion : rediriger les utilisateurs SIAE vers leur tableau de bord

- lemarche/templates/tenders/_list_item_siae.html
- lemarche/templates/tenders/detail.html
> Dépot de besoin : fix de l'affichage du montant

- clevercloud/cron.json
- clevercloud/stats_export_user_download_list_to_file.sh
- clevercloud/stats_export_user_search_list_to_file.sh
- config/settings/base.py
- config/urls.py
- lemarche/common/admin.py
- lemarche/favorites/admin.py
- lemarche/networks/admin.py
- lemarche/pages/admin.py
- lemarche/perimeters/admin.py
- lemarche/sectors/admin.py
- lemarche/siaes/admin.py
- lemarche/siaes/management/commands/export_all_siae_to_file.py
- lemarche/stats/management/commands/export_user_download_list.py
- lemarche/stats/management/commands/export_user_search_list.py
- lemarche/stats/management/commands/get_user_download_list.py
- lemarche/stats/management/commands/get_user_search_list.py
- lemarche/templates/admin/index_with_export.html
- lemarche/tenders/admin.py
- lemarche/users/admin.py
Suite de https://github.com/betagouv/itou-marche/pull/300
Pouvoir récupérer et enrichir les listes de stats : 
- des téléchargements
- des recherches effectuées
> Stats : commandes pour enrichir les extracts de stats

- lemarche/templates/tenders/create.html
Fixer le problème d'icone  des dates dans le formulaire de dépôt de besoin.
> Fixer le problème d'icone  des dates dans le formulaire de dépôt de besoin

- lemarche/templates/pages/partenaires.html
Mise à jour du texte d'Handeco
> Mise à jour du texte d'Handeco

- config/settings/base.py
- lemarche/cms/models.py
- lemarche/static/itou_marche/base/_custom.scss
> Fix du css du cms

- lemarche/siaes/admin.py
- lemarche/templates/tenders/create_notification_email_admin_body.txt
- lemarche/tenders/admin.py
Dans l'admin, pouvoir cliquer et voir la liste des structures contactées, ayant vues, et  intéressées par le dépôt de besoin
> Dépôt de besoin : Admin : avoir la liste des structures intéressées

- lemarche/siaes/management/commands/import_siae_groups.py
Script d'import des groupements
- fix sur le champ id
- documenter un peu comment s'en servir
> Groupements : mini ajustements sur le script d'import

- lemarche/templates/pages/home.html
Modification du titre et des boutons du haut
> Ajustements sur la home page

- lemarche/templates/pages/home.html
- lemarche/tenders/models.py
- lemarche/www/pages/views.py
Suite de https://github.com/betagouv/itou-marche/pull/329
> Ajustements sur la home page (2/2)

- lemarche/templates/auth/_login_or_signup_modal.html
- lemarche/templates/pages/home.html
Suite de https://github.com/betagouv/itou-marche/pull/339
> Ajustements sur la home page (3)

- lemarche/static/itou_marche/base/_custom.scss
- lemarche/static/js/kind_multiselect_field.js
- lemarche/static/js/sector_multiselect_field.js
- lemarche/static/js/territory_multiselect_field.js
- lemarche/templates/tenders/create_base.html
- lemarche/templates/tenders/create_step_confirmation.html
- lemarche/templates/tenders/create_step_contact.html
- lemarche/templates/tenders/create_step_general.html
- lemarche/tenders/models.py
- lemarche/www/tenders/forms.py
- ajout de placeholder
- ajout de help_text
- améliorer la couleur du placeholder du multiselect
- ajout d'un spinner à la dernière étape
- enlevé `submit` sur le bouton 'etape précédente' (provoquait un bug à la dernière étape)
> Dépôt de besoin : ajout des placeholder & spinner

- lemarche/templates/tenders/create_notification_email_admin_body.txt
Eviter les `&#x27;` à la place des apostrophes par exemple
> Répare l'affichage de certains caractères

- lemarche/templates/siaes/search_results.html
Changer le texte + mettre à jour le bouton
> Recherche : mettre à jour le message "sans résultats"

- lemarche/api/perimeters/tests.py
- lemarche/siaes/models.py
- lemarche/static/js/perimeters_autocomplete_fields.js
- lemarche/templates/siaes/search_results.html
- lemarche/templates/tenders/create_step_general.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
- lemarche/www/siaes/views.py
- lemarche/www/tenders/forms.py
- lemarche/www/tenders/views.py
Suite de https://github.com/betagouv/itou-marche/pull/356
- cleanup du html
- afficher le slug du périmètre au lieu de l'id
> Améliorations sur la recherche multi-périmètres

- lemarche/templates/dashboard/home.html
- lemarche/templates/layouts/_header.html
- Ajout de l'option "Mon profil" dans le dropdown du header
- Retirer la section "Mon profil" dans le tableau de bord
> Accéder au formulaire de modification de son profil depuis le header

- lemarche/siaes/models.py
- lemarche/templates/tenders/_detail_contact.html
- lemarche/templates/tenders/_list_item_siae.html
- lemarche/templates/tenders/detail_card.html
- lemarche/tenders/admin.py
- lemarche/tenders/models.py
- lemarche/utils/export.py
- lemarche/www/tenders/tasks.py
- lemarche/www/tenders/views.py
Dans l'email d'opportunité envoyé aux structures, leur rappeler les détails de sa fiche (secteurs & périmètre)
> Dépôt de besoin : enrichir le contenu de l'email envoyé aux structures

- config/settings/dev.py
- lemarche/siaes/constants.py
- lemarche/siaes/models.py
- lemarche/siaes/tests.py
- lemarche/static/itou_marche/sections/_siae.scss
- lemarche/templates/dashboard/_siae_card_home.html
- lemarche/templates/dashboard/_siae_completion_progress_bar.html
- lemarche/templates/dashboard/siae_edit_base.html
- lemarche/templates/includes/_completion_progress_bar.html
- lemarche/utils/data.py
Ajout d'un niveau de complétion des profiles des SIAES.
Encourager les structures à remplir davantage leurs profiles.
En fonction des champs remplis ou non de la structure.
> Ajout d'un niveau de complétion des profiles des SIAES

- lemarche/static/itou_marche/sections/_siae.scss
- lemarche/templates/dashboard/_siae_card_home.html
- lemarche/templates/siaes/_card_search_result.html
- lemarche/templates/siaes/detail.html
- Tableau de bord : afficher le logo à coté du nom de la structure
- Résultats de recherche : augmenter un peu la taille du logo
- Fiche : réduire un peu les padding, augmenter un peu la taille du logo
> Améliorer l'affichage des logo des structures

- lemarche/static/js/network_multiselect_field.js
- lemarche/static/js/presta_type_multiselect_field.js
- lemarche/static/js/sector_multiselect_field.js
- lemarche/templates/tenders/siae_interested_list.html
- lemarche/www/siaes/views.py
Suite de #378
- homogénéiser le rendu des placeholder des filtres de recherche
- transformer le bouton "Télécharger la liste" pour la page "liste des structures intéressées par ce besoin"
> Ajustement de mises en forme

- lemarche/templates/dashboard/_aides_territoires_section.html
- lemarche/templates/dashboard/_api_key_row.html
- lemarche/templates/dashboard/home_buyer.html
- lemarche/templates/dashboard/home_siae.html
- lemarche/www/dashboard/views.py
Avoir des template dédiés pour les Siae & le reste
> Refonte TDB : séparation des templates

- lemarche/templates/dashboard/_ressource_card.html
- lemarche/templates/dashboard/_siae_tab_content.html
- lemarche/www/dashboard/views.py
Ajustement d'éléments du dashboard pour les acheteurs et les structures : 
- Affichage du nombre de collaborateurs pour les SIAES
- Affichage des ressources spécifiques aux acheteurs et structures
> Ajustement d'éléments du dashboard pour les acheteurs et les structures

- lemarche/utils/apis/api_marche_maximilien.py
- lemarche/utils/apis/api_marche_maximilien_example.txt
Exploration de l'API
https://marches.maximilien.fr/rssCS.xml
> API : Maximilien

- lemarche/templates/tenders/create_base.html
- lemarche/templates/tenders/create_step_confirmation.html
- corrige l'inversion des boutons "Suivant" et "Précédent"
- ajoute un icone sur le CTA final
> Dépôt de besoin : fix sur les boutons du formulaire

- lemarche/siaes/management/commands/sync_c1_c4.py
- lemarche/siaes/management/commands/sync_c2_c4.py
- lemarche/siaes/management/commands/update_api_entreprise_fields.py
- lemarche/utils/apis/api_entreprise.py
- lemarche/utils/apis/api_slack.py
Ajout de messages slacks pour les taches asynchrones.
Pour éviter les erreurs silencieuses.
> Ajout de messages slacks pour les taches asynchrones

- lemarche/templates/layouts/base.html
- lemarche/templates/pages/contact.html
- lemarche/templates/pages/groupements.html
- lemarche/templates/pages/home.html
- lemarche/templates/pages/stats.html
- lemarche/templates/pages/valoriser-achats.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/siaes/search_results.html
Modifications des META (title, description) sur certaines pages
Rendre plus explicite les pages les plus fréquentées. Les META apparaissent dans les résultats des moteurs de recherche, mais aussi lorsque le lien est partagé.
> Mise à jour des META sur certaines pages

- lemarche/templates/auth/logged_out.html
- lemarche/templates/auth/login.html
- lemarche/templates/auth/password_reset.html
- lemarche/templates/auth/password_reset_complete.html
- lemarche/templates/auth/password_reset_confirm.html
- lemarche/templates/auth/password_reset_sent.html
- lemarche/templates/auth/signup.html
Mise à jour de l'intégration front des formulaires de login, reset password et signup
Pour répondre a cette demande
https://www.notion.so/Page-de-connexion-C4-6eac1b0916c14a6da781c79d9219568a
En intégrant la nouvelle mise en page recommandée et visible ici
- https://betagouv.github.io/itou-theme/layout-itou-form-simple.html
- https://betagouv.github.io/itou-theme/layout-itou-form.html
> Mise a jour de l'intégration front de plusieurs formulaires

- README.md
Tableau de mapping entre les termes métier et les termes employés dans le code
Pour aider les personnes non-dev à comprendre le code
> Documentation : petit tableau pour expliquer la nomenclature utilisée dans le code

- lemarche/templates/siaes/_card_suggest_tender.html
- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/views.py
Transformation de la recherche en dépôt de besoin _(étape 2)_.
Inciter davantage à la création de besoin.
> Transformer recherche en dépôt de besoin (étape 2)

- lemarche/www/tenders/tasks.py
Pour chaque besoin validé, logger : 
- le nombre de structures contactées
- le nombre de partenaires contactés
> Dépôt de besoin : log additionnels lors des envois d'emails

- lemarche/siaes/management/commands/sync_c1_c4.py
- lemarche/siaes/management/commands/sync_c2_c4.py
- lemarche/siaes/management/commands/update_api_entreprise_fields.py
- lemarche/siaes/management/commands/update_api_qpv_fields.py
- lemarche/siaes/management/commands/update_api_zrr_fields.py
- lemarche/utils/commands.py
- généraliser l'utilisation de `lemarche.utils.commands.BaseCommand`
- mettre tous les `msg_success` en liste
- ajouter une notif Slack aux API QPV & ZRR
> API : cleanup des messages générés et envoyés par nos scripts

- config/settings/base.py
- lemarche/api/siaes/filters.py
- lemarche/api/siaes/tests.py
- lemarche/api/siaes/views.py
- lemarche/siaes/constants.py
- lemarche/siaes/factories.py
- lemarche/siaes/management/commands/import_esat_gesat.py
- lemarche/siaes/management/commands/import_esat_handeco.py
- lemarche/siaes/management/commands/import_sep.py
- lemarche/siaes/models.py
- lemarche/siaes/tests.py
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
Bouger les Siae.KIND_CHOICES dans le fichier `siaes.constants.py`
Pour pouvoir les utiliser comme choices dans un autre modèle (PR suivante)
> Bouger les choix de type de structure dans siaes.constants

- lemarche/tenders/factories.py
- lemarche/www/tenders/tests.py
Tests sur la création de besoins
> Dépôt de besoin : tests additionnels

- lemarche/www/tenders/tasks.py
Changer les titres des mails transactionnels des dépôts de besoins.
Inciter davantage à ouvrir les mails.
> Changer les titres des mails transactionnels des dépôts de besoins

- lemarche/utils/tracker.py
- lemarche/www/auth/views.py
- lemarche/www/dashboard/views.py
- lemarche/www/siaes/views.py
- Tracking de la page de calcul de la calibration sociale
- Changer le fonctionnement du middleware de Tracking pour éviter de dupliquer les trackings
> Evolution de la logique de tracking

- lemarche/templates/pages/impact-calculator.html
- lemarche/utils/tracker.py
- lemarche/www/pages/views.py
- pyproject.toml
Suite de https://github.com/betagouv/itou-marche/pull/496
- HTMX : utiliser la méthode GET, passer le token CSRF dans le header
- Formulaire : hériter de SiaeSearchForm
- l'init du formulaire fonctionne : du coup on peut partager l'URL plus facilement
- éviter de faire le filtre / aggregation si aucune recherche
> Calculateur : utiliser la méthode GET

- lemarche/templates/pages/company-reference-calculator.html
- lemarche/www/pages/forms.py
- lemarche/www/pages/urls.py
- lemarche/www/pages/views.py
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
Première version d'un calculateur pour connaître le nombre de prestataires inclusifs qui ont indiqué l'entreprise recherchée dans leur références clients.
Utilisation d'HTMX, similaire à https://github.com/betagouv/itou-marche/pull/500
> Calculateur pour trouver le nombre de références clients pour son entreprise

- lemarche/siaes/models.py
- lemarche/stats/models.py
- lemarche/templates/dashboard/_siae_tab_content.html
Commencer à afficher quelques stats sur le Tableau de bord "Structure" : 
- ~nombre de vues de la fiche durant les 3 derniers mois~
- nombre de vues de la fiche par un acheteur connecté durant les 3 derniers mois
- nombre de vues de la fiche par un partenaire connecté durant les 3 derniers mois
> TDB Siae : afficher quelques stats

- lemarche/templates/siaes/_download_click_survey_modal.html
- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/forms.py
- nouveau champ `download_source` sur le formulaire `SiaeDownloadForm`
- passer cette info à la modale
> Téléchargement : connaitre la source

- lemarche/templates/pages/company-reference-calculator.html
- lemarche/www/pages/urls.py
- lemarche/www/siaes/forms.py
v2 pour mettre à jour le texte, avant partage
> Calculateur références : maj du texte, ajout de CTA

- lemarche/templates/pages/impact-calculator.html
- lemarche/www/pages/views.py
Permettre à l'utilisateur d'accéder à la liste complètes des structures retournées par le calculateur
> Calculateur calibrage : afficher un lien vers la liste de résultats

- lemarche/templates/tenders/_list_item_buyer.html
- lemarche/templates/tenders/create_step_survey.html
- lemarche/templates/tenders/list.html
- lemarche/www/tenders/urls.py
- lemarche/www/tenders/views.py
Ajout de filtres pour le dépôt de besoins via htmx.
Filtrer les dépôts de besoins pour plus de lisibilité.
- peut être changer la nav tab par un formulaire 🤔
> Ajout de filtres pour le dépôt de besoins

- lemarche/tenders/models.py
- lemarche/www/tenders/forms.py
- lemarche/www/tenders/views.py
Fix du mode brouillon (PR https://github.com/betagouv/itou-marche/pull/533) et tri des besoins par deadline.
> Fix du mode brouillon et tri des besoins par deadline

- lemarche/templates/layouts/_header.html
Dans le header, un dropdown qui regroupe nos services ("Solutions") pour les acheteurs
||Avant|Après|
|---|---|---|
|Anonyme|![Screenshot from 2022-12-06 15-51-14](https://user-images.githubusercontent.com/7147385/205944600-7dffb3c8-ad5c-4a57-98a3-1e099a4269f4.png)|![Screenshot from 2022-12-06 15-44-40](https://user-images.githubusercontent.com/7147385/205944234-d1313a30-5cc0-4fbf-b86e-d815288de5b0.png)|
|Connecté|![Screenshot from 2022-12-06 15-51-03](https://user-images.githubusercontent.com/7147385/205944640-41e64a8e-8eb7-4e49-9a99-9bf58512ef10.png)|![Screenshot from 2022-12-06 15-47-48](https://user-images.githubusercontent.com/7147385/205944267-71019465-87da-496e-a8b2-2a72d879f055.png)|
|Anonyme (mobile)|![Screenshot from 2022-12-06 …
> Header : nouveau dropdown "Solutions"

- config/settings/base.py
Modifié la config pour pointer vers notre nouveau dashboard de stats
> Stats : nouveau dashboard, nouveau lien

- lemarche/www/siaes/forms.py
Suite de #463
|Avant|Après|
|---|---|
|![Screenshot from 2022-11-22 16-29-42](https://user-images.githubusercontent.com/7147385/205925082-a0ed52bc-d67e-4098-8d14-355f87d21072.png)|![Screenshot from 2022-12-06 14-26-41](https://user-images.githubusercontent.com/7147385/205925011-39987314-c8b2-4605-8e5a-789c215c629e.png)|
> Téléchargement : mise à jour du texte de la question

- lemarche/siaes/admin.py
- lemarche/utils/admin/actions.py
- lemarche/utils/admin/export_excel.py
Exporter les stats des SIAEs pour les DR, depuis la vue d'admin des SIAES.
> Exporter les stats des SIAEs pour les DR 

- config/settings/base.py
- config/settings/prod.py
- config/settings/staging.py
- lemarche/www/pages/views.py
Depuis Django 4, un setting a été ajouté pour augmenter la sécurité des sites, peut-être que l'erreur du csrf token viens de là.
+ fix de la méthode crsf token (pas sur du long termes, car ça en prends pas en compte les modifications)
> Fix de csrf erreur

- lemarche/templates/dashboard/_add_tender_card.html
- lemarche/templates/dashboard/_api_key_card.html
- lemarche/templates/dashboard/_ressource_card.html
- lemarche/templates/dashboard/home_buyer.html
Quelques ajustements front / ui sur le dashboard
Pour répondre a ces cartes
- https://www.notion.so/C4-TDB-acheteur-Arrondis-background-et-boutons-ee24eb538a4c498094cd0cf671657d2e
- https://www.notion.so/C4-TDB-acheteur-arrondis-images-2bc7d8cbf5f54ce89694d54acd22c049
Templating/DOM
> Quelques ajustements front et ui sur le dashboard

- lemarche/utils/tracker.py
Lors d'une recherche via le simulateur d'impact, renvoyer le `results_count` dans les stats
Lié à https://github.com/betagouv/itou-marche/pull/519 et https://github.com/betagouv/itou-marche/pull/532
> Stats : ajout du 'results_count' sur le calculateur d'impact

- lemarche/tenders/models.py
- lemarche/www/pages/views.py
Utile pour les changements liés à l'UI.
- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.
> Fix de l'erreur csrf tender location 

- lemarche/www/pages/views.py
- lemarche/www/tenders/forms.py
- lemarche/www/tenders/views.py
Utile pour les changements liés à l'UI.
- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.
> Fix location required quand on coche france entière

- lemarche/templates/tenders/list.html
Supportix: fix des filtres de dépôt de besoins (published)
> Supportix: fix des filtres de dépôt de besoins (published)

- lemarche/templates/dashboard/home_buyer.html
Ajouter la feature “calibrer” dans le TDB acheteur.
Réel intérêt des acheteurs.
> Ajouter la feature “calibrer” dans le TDB acheteur

- lemarche/tenders/admin.py
Suite à https://github.com/betagouv/itou-marche/pull/576
> Dépôt de besoin : Admin : fix de l'affichage de email_link_click_date

- config/settings/base.py
- lemarche/stats/management/commands/export_user_download_list.py
- lemarche/stats/management/commands/export_user_search_list.py
- lemarche/tenders/admin.py
Fix des bugs de dépôts de besoins
- Fix de l'auteur et du status dans le dépôt de besoin côté admin
- Fix de `cmp` parfois inexistant (tracking) 
- Tentative de fix de l'erreur csrf
> Fix des bugs de dépôts de besoins

- config/settings/base.py
- lemarche/utils/sessions.py
Utile pour les changements liés à l'UI.
- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.
> fix de l'erreur csrf

- lemarche/templates/layouts/_footer.html
Correction du wording du prefooter. A faire sur tous les chantiers
> Correction du wording du prefooter

- lemarche/templates/tenders/admin_change_form.html
- lemarche/tenders/admin.py
Permettre aux admins de relancer les dépôts de besoins.
Relancer les dépôts de besoins pas trop consultés.
> Permettre aux admins de relancer les dépôts de besoins

- lemarche/templates/tenders/detail_card.html
- lemarche/www/pages/views.py
- lemarche/www/tenders/urls.py
Fix de l'erreur CSRF dans le mode brouillon.
> Fix de l'erreur CSRF dans le mode brouillon

- lemarche/tenders/admin.py
Filtre admin sur le champ `siae_transactioned`
> Dépôt de besoin : dans l'admin, pouvoir filtré par transactionné

- lemarche/templates/pages/impact-calculator.html
Amélioration de l'ui du formulaire d'impact
Pour répondre a cette demande https://www.notion.so/C4-Am-lioration-front-end-du-formulaire-Calibrer-votre-achat-socialement-responsable-4f6e02f3ab884c31b018adb19ad0fa0d et respecter le thème
Modification du DOM html
Avant
Apres
> Amélioration de l'ui du formulaire d'impact

- lemarche/templates/layouts/_footer.html
- lemarche/templates/pages/company-reference-calculator.html
- lemarche/templates/pages/impact-calculator.html
Amélioration de l'ui du formulaire de company-reference-calculator
Pour répondre a cette demande [https://www.notion.so/C4-Am-lioration-front-end-du-formulaire-Calibrer-votre-achat-socialement-responsable-4f6e02f3ab884c31b018adb19ad0fa0d et respecter le thème](https://www.notion.so/C4-Am-lioration-front-end-du-formulaire-acheteurs-reference-client-3449e6a70c4a4b6b8cda75f57659f278)
Modification du DOM html
Avant
Apres
> Amélioration de l'ui du formulaire acheteurs-reference-client

- lemarche/static/itou_marche/layouts/_pages.scss
- lemarche/templates/tenders/create_base.html
- lemarche/templates/tenders/create_step_confirmation.html
- lemarche/templates/tenders/create_step_contact.html
- lemarche/templates/tenders/create_step_description.html
- lemarche/templates/tenders/create_step_general.html
- lemarche/templates/tenders/create_step_survey.html
- lemarche/www/tenders/forms.py
Modification de l'ui des formulaires de dépôt de besoin
Pour répondre a cette demande https://www.notion.so/C4-Am-lioration-front-end-du-formulaire-publier-un-besoin-3fe4101e3df547ec88cd6f3d0c8e6dc9 et pour coller au thème
Modification du DOM dans les templates 
Attention j'ai du faire des choix pour les alertes sur les champs et en passer certain en "conseil".
Mais ce n'est qu'une proposition, les conseils peuvent facilement redevenir des alertes (mais à placer en dessous des champs et pas sur la droite dans ce cas)
> Modification de l'ui des formulaires de dépôt de besoin

- config/settings/base.py
- lemarche/templates/layouts/_footer.html
- lemarche/templates/pages/accessibilite.html
- lemarche/utils/settings_context_processors.py
- lemarche/www/pages/urls.py
Ajout d'une page accessibilité
Pour pouvoir y mettre la déclaration d'accessibilité
> Ajout d'une page accessibilité

- lemarche/www/pages/views.py
- lemarche/www/tenders/views.py
Ajout des dépôts de besoins dans les transactions hubspot.
> Ajout des dépôts de besoins dans les transactions hubspot

- lemarche/templates/layouts/_header.html
- lemarche/templates/pages/social-impact-for-buyers.html
- lemarche/utils/apis/api_hubspot.py
- lemarche/utils/tracker.py
- lemarche/www/pages/forms.py
- lemarche/www/pages/urls.py
- lemarche/www/pages/views.py
Calculateur d'impact social d'un achat.
Créer une page avec un calculateur sur le modèle de la page “Calibrage”.
En tant qu'Acheteur, je veux connaître l'impact social d'un achat;
Méthode de calcul si montant >3699€ :
Arrondi ([Montant €] / 3700) = X jobs
Méthode de calcul si montant ≤3699€ :
Arrondi ([Montant €] / 26) = X heures
> Calculateur d'impact social d'un achat

- lemarche/tenders/admin.py
Ajout du filtre incrémentale dans l'admin .
> Ajout du filtre incrémentale dans l'admin 

- lemarche/templates/tenders/list.html
- lemarche/www/tenders/views.py
- répare un souci provoqué par la PR #606
- clarification : remplace "publié" par "en cours de validation" pour homogénéiser avec les badge
> Liste des besoins : fix sur les onglets htmx

- lemarche/utils/apis/api_mailjet.py
- lemarche/www/tenders/tasks.py
Modifications sur l'envoi d'e-mail aux structures concernées par un besoin déposé : 
- mise à jour de l'object
- mise à jour de l'expéditeur (e-mail et nom)
> Dépôt de besoin : modifications sur l'envoi d'e-mail aux structures concernées

- lemarche/templates/includes/_tracker_tarteaucitron.html
Envoyer l'info UserID à Matomo
https://ronan-hello.fr/series/matomo/how-to-user-id-matomo
> Stats : utiliser Matomo UserID

- lemarche/perimeters/models.py
- lemarche/templates/dashboard/profile_network_siae_list.html
- lemarche/www/dashboard/urls.py
- lemarche/www/dashboard/views.py
- lemarche/www/siaes/forms.py
Suite de #633
Dans la nouvelle page "Structures de mon réseau", permettre à l'utilisateur de filtrer sur un périmètre donnée (restreint aux régions)
Choix d'un dropdown pour plus de facilité (vs un autocomplete en JS).
> Réseau : pouvoir filtrer par périmètre (région)

- config/settings/base.py
- lemarche/templates/api/home.html
- lemarche/templates/layouts/_footer.html
- lemarche/www/pages/urls.py
Liens dans le footer vers les nouvelles pages : 
- CGU & CGU API
- Confidentialité
Le contenu de ces pages est géré dans l'admin Django (Flatpages)
Modifié aussi la config de CKEditor pour pouvoir rajouter des tables
|Page|Image|
|---|---|
|Footer|![Screenshot from 2023-02-09 17-39-03](https://user-images.githubusercontent.com/7147385/217879651-d3da4dca-3a3f-4584-9868-09eebbe60268.png)|
|Doc de l'API|![Screenshot from 2023-02-09 17-38-55](https://user-images.githubusercontent.com/7147385/217879616-5d55177a-3580-42c8-88ef-c22c3ff2e634.png)|
> Ajout des CGU

- lemarche/templates/tenders/create_step_description.html
- lemarche/www/tenders/forms.py
Calcul d'impact à la création d'un besoin.
Encourager l'acheteur.
plugin js pour éviter l'ajax.
> Calcul d'impact à la création d'un besoin

- CHANGELOG.md
Rattrapage du Changelog depuis Avril 2022
> Mise à jour du Changelog

- lemarche/templates/dashboard/profile_network_siae_tender_list.html
- lemarche/www/dashboard/views.py
Suite de #633 & #663
Rajouter des stats sur les onglets
> Réseaux : afficher les stats à coté des onglets

- lemarche/www/tenders/forms.py
Fix du bug du montant obligatoire à la création du dépôt de besoin.
> Fix du bug du montant obligatoire à la création du dépôt de besoin

- lemarche/fixtures/django/10_tenders.json
- lemarche/fixtures/django/11_tender_sectors.json
- lemarche/siaes/models.py
- lemarche/templates/dashboard/_siae_tab_content.html
- lemarche/templates/tenders/detail.html
- lemarche/www/tenders/views.py
- TDB : fix sur les stats affichées
- Fixtures : améliorer le contenu des besoins
> Quelques fixes & améliorations

- lemarche/templates/layouts/_header.html
- enlever le bouton "Favoris" du header
- le rajouter dans le dropdown "Mon espace"
> Header : bouger le bouton "Favoris" dans le menu "Mon espace"

- lemarche/cms/blocks.py
- lemarche/templates/cms/streams/stats_website.html
Version simplifiée de #691
|||
|---|---|
|Avant|![image](https://user-images.githubusercontent.com/7147385/230414646-d586bc77-aa5d-4780-8999-d08ae568ec3a.png)|
|Après|![image](https://user-images.githubusercontent.com/7147385/230414167-83f043b1-d9e4-44cc-b2a5-c82f55725bfd.png)|
> Home : modifier le message du bandeau "impact"

- lemarche/templates/dashboard/profile_network_siae_tender_list.html
- lemarche/templates/dashboard/profile_network_tender_detail.html
- lemarche/templates/dashboard/profile_network_tender_list.html
- lemarche/templates/dashboard/profile_network_tender_siae_list.html
- lemarche/templates/tenders/_list_item_network.html
- lemarche/templates/tenders/detail.html
- lemarche/www/dashboard/tests.py
- lemarche/www/dashboard/urls.py
- lemarche/www/dashboard/views.py
Suite de #710
Page dédiée avec les détails du besoin + lien vers les adhérents notifiés & intéressés
> Réseaux : page intermédiaire avec le détail du besoin

- lemarche/templates/dashboard/siae_edit_base.html
- lemarche/templates/dashboard/siae_edit_contact.html
- lemarche/templates/dashboard/siae_edit_links.html
Améliorations du formulaire de modification de sa structure : 
- ajout d'onglets pour faciliter la navigation
|Avant|Après|
|---|---|
|![Screenshot from 2023-04-06 15-08-16](https://user-images.githubusercontent.com/7147385/230387952-e3819fa9-0dc8-43dd-80da-db5b4400ed56.png)|![Screenshot from 2023-04-06 15-07-54](https://user-images.githubusercontent.com/7147385/230387919-8d7b66f6-4e27-44f3-b089-e77f162e788c.png)|
> Dashboard : améliore l'UX du formulaire de modification de sa structure

- lemarche/www/tenders/tasks.py
> Dépôt de besoin : légère modification de l'objet de l'email envoyé aux structures

- clevercloud/siaes_send_user_request_reminders.sh
- clevercloud/tenders_send_author_incremental.sh
- lemarche/tenders/management/commands/send_author_incremental_emails.py
Fix de plusieurs erreurs suite à #657 : 
- inversé les deux scripts .sh (sans conséquence)
- typo dans le nom de la tâche
- problème dans la queryset (lt & gte)
> Dépôt de besoin : répare l'envoi d'e-mails aux auteurs des besoins incrémentaux

- lemarche/templates/layouts/_footer.html
- lemarche/templates/layouts/_header.html
|||
|---|---|
|Avant|![image](https://user-images.githubusercontent.com/7147385/231552321-e47c6f71-726c-45b2-b7b1-ea068df0d208.png)|
|Après|![Screenshot from 2023-04-12 18-14-58](https://user-images.githubusercontent.com/7147385/231552220-2b81cb97-11be-418b-8523-b5bb43ed5e32.png)|
> Header : remplacer Newsletter par un lien vers une ressource

- config/settings/base.py
- lemarche/api/tenders/serializers.py
Modifications apportées sur l'API : 
- réorganiser le paragraphe de description
- ajout d'un lien vers /api/redoc
|Avant|Après|
|---|---|
|![Screenshot from 2023-04-19 15-41-36](https://user-images.githubusercontent.com/7147385/233094248-18dd75fc-5452-491e-9665-5d5cc26778c2.png)|![Screenshot from 2023-04-19 15-42-04](https://user-images.githubusercontent.com/7147385/233094288-d48262de-d8f0-407c-8faa-f14128ee06fd.png)|
> API : petite amélioration de la documentation

- lemarche/templates/layouts/_header.html
Dans le header > dropdown Solutions, ajout d'un lien vers le moteur de recherche.
> Header : ajout d'un lien vers la recherche

- lemarche/templates/cms/static/valoriser-achats.html
- lemarche/templates/layouts/_header.html
- lemarche/templates/pages/valoriser-achats.html
Dans la liste des solutions (dropdown dans le header), on souhaite renommer "Valoriser vos achats" en "Auditer vos achats".
On renomme aussi le titre de la page correspondante.
> Header : renommer la solution Valoriser en Auditer

- lemarche/www/auth/tests.py
- lemarche/www/auth/views.py
Similaire à #755
tout est dans le titre :)
> Connexion : rediriger les acheteurs vers le moteur de recherche

- lemarche/siaes/management/commands/send_completion_reminder_emails.py
- lemarche/siaes/management/commands/sync_c1_c4.py
- lemarche/siaes/management/commands/sync_c2_c4.py
- lemarche/siaes/management/commands/update_api_entreprise_fields.py
- lemarche/siaes/management/commands/update_api_qpv_fields.py
- lemarche/siaes/management/commands/update_api_zrr_fields.py
- rajouter un message Slack à la fin de la tâche d'envoi d'e-mail de rappel aux structures dont la fiche n'est pas complétée - #753
- clarifier un peu les autres messages slack
> Tâches automatisées : améliorer les messages Slack

- lemarche/templates/auth/_login_or_signup_siae_tender_modal.html
Mise à jour de la popup d'authentification.
Pour tester s'il y a un meilleur taux d'ouverture.
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/a53520b5-3f57-4664-bdfa-b804d439ed0c)|![image](https://github.com/betagouv/itou-marche/assets/7147385/65bd22a6-64a2-482d-946d-d01c43e9d6e8)|
> Mise à jour de la popup d'authentification

- lemarche/templates/siaes/_card_suggest_tender.html
Reformuler l’encart “Pas de temps à perdre” dans les search result.
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/16ac8f45-9f5b-4649-87ce-917a7e18f0fa)|![image](https://github.com/betagouv/itou-marche/assets/12339682/67721557-829c-4f6f-bb83-0919709e23ec)|
> Recherche : reformuler l’encart "Pas de temps à perdre"

- lemarche/labels/management/commands/import_rsei.py
On souhaite récupérer les données du label RSEi, et labelliser les structures concernées.
https://certification.afnor.org/developpement-durable-rse/demarches-rse-sectorielles/label-rsei
Note : ce n'est pas une API, il faut fournir la localisation du fichier csv en paramètre de la commande
> Labels : récupérer les données de RSEi

- lemarche/labels/management/commands/import_esus.py
- lemarche/labels/management/commands/import_rsei.py
On souhaite récupérer les données des agréments ESUS, et labelliser les structures concernées.
https://www.tresor.economie.gouv.fr/banque-assurance-finance/finance-sociale-et-solidaire/liste-nationale-agrements-esus
Note : ce n'est pas une API, il faut fournir la localisation du fichier csv en paramètre de la commande
> Labels : récupérer les données d'ESUS

- lemarche/labels/management/commands/api_ademe_rge.py
- lemarche/labels/management/commands/import_esus.py
- lemarche/labels/management/commands/import_rsei.py
- lemarche/utils/apis/api_entreprise.py
Suite à la création d'un nouveau modèle `Label` (#746), et la relation M2M avec les `Siae` (#763)
On souhaite récupérer les données RGE via l'API de l'ADEME, et labelliser les structures concernées.
https://api.gouv.fr/documentation/api_professionnels_rge
> Labels : récupérer les données de l'API ADEME RGE

- lemarche/static/js/kind_multiselect_field.js
- lemarche/static/js/search_form.js
- lemarche/templates/siaes/search_results.html
Ajout d'un bouton pour réinitialiser le formulaire.
Pour faciliter la re-saisie d'une recherche.
> Recherche : Ajout d'un bouton pour réinitialiser le formulaire 

- lemarche/templates/siaes/_card_tender.html
Afficher le logo du prestataire dans sa card
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/d4710bdf-eca2-4b78-8227-b39c65c4c4b4)|![image](https://github.com/betagouv/itou-marche/assets/7147385/30feeea2-5c7e-420d-93ea-6adaf85f8792)|
> Dépôt de besoin : ajout du logo du prestataire

- lemarche/siaes/admin.py
- lemarche/siaes/models.py
- lemarche/www/siaes/forms.py
Admin : 
- ordonner les champs QPV & ZRR
- recherche par `brand`
Formulaire : 
- ajout d'un label manquant (#779à
> Structures : quelques petites modifications 

- lemarche/templates/siaes/search_results.html
Améliorer l'UX des users.
Utilisation d'un module htmx.
> Simplification du moteur de recherche

- lemarche/templates/includes/forms/_bootstrap_field_checkbox.html
- lemarche/templates/includes/forms/_bootstrap_field_radio.html
- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/forms.py
> Recherche : filtre sur les prestataires avec (ou sans) référence client

- lemarche/static/js/locations_autocomplete_field.js
- lemarche/static/js/perimeter_autocomplete_field.js
- lemarche/static/js/perimeters_autocomplete_field.js
- lemarche/templates/pages/impact-calculator.html
- lemarche/templates/pages/social-impact-for-buyers.html
- lemarche/templates/siaes/search_results.html
- lemarche/templates/tenders/siae_interested_list.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
- lemarche/www/siaes/views.py
Nouveau champ de recherche avancée pour filtrer les structures par localisation
- différent du champ "périmètre" actuel
- ca a nécessité de dupliquer / séparer l'autocomplete pour éviter les conflits sur la page de recherche
> Recherche : filtre sur la localisation

- lemarche/tenders/admin.py
Tout est dans le titre :)
Déjà possible pour les structures
> Admin : pouvoir filtrer les besoins par slug

- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
> Recherche : filtre sur les prestataires avec (ou sans) groupement

- lemarche/companies/admin.py
- lemarche/companies/models.py
- ordonner par `name`
- filtres par `has_user` et `has_email_domain`
- répare l'ajout d'email_domain supplémentaires
> Entreprise : améliorations dans l'admin

- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/tests.py
- lemarche/www/siaes/views.py
Laisser ouvert la recherche avancée si un champs de la recherche avancée est saisi.
> Laisser ouvert la recherche avancée si un champs est saisi

- lemarche/templates/siaes/search_results.html
- lemarche/www/siaes/views.py
Affichage de la modal pour s'inscrire ou se connecter pour les utilisateurs anonymes qui veulent utiliser la recherche avancé.
Pour les inciter à se connecter ou s'inscrire.
Ecriture d'un module Alpine pour la gestion de la modal.
> Affichage de la modal pour s'inscrire ou se connecter pour les utilisateurs anonymes

- lemarche/static/js/search_form.js
- lemarche/templates/siaes/search_results.html
- lemarche/templates/siaes/widgets/location_widget.html
- lemarche/www/siaes/forms.py
- lemarche/www/siaes/views.py
Suite à #815 il y a de grosses lenteurs sur le moteur de recherche.
Pour résoudre : 
- suppression des form field `choices` si le field est disabled (fix pour les utilisateurs anonymes)
- ??? (fix pour les utilisateurs connectés
j'en ai profité pour cleanup un quelques trucs (nommage, indentation)
> Recherche avancée : réparer les lenteurs

- lemarche/tenders/admin.py
2 nouveaux filtres (multiples) dans l'admin des besoins : 
- par source
- par montant
> Dépôt de besoin : Admin : filtres par source et par montant

- lemarche/notes/admin.py
> Note : afficher et filtrer par content_type dans l'admin

- config/settings/base.py
- lemarche/notes/management/commands/import_notes_from_hubspot.py
- lemarche/utils/apis/api_hubspot.py
- importer les notes sur les Tender (`deals`)
- importer les notes sur les Utilisateurs (`contacts`)
- ~~comment matcher les utilisateurs ? par leur e-mail~~
- comment matcher les besoins ? sur l'e-mail de l'auteur
- ~~avoir mergé les autres PR sur les Notes~~
> Note : importer depuis Hubspot

- lemarche/conversations/admin.py
- lemarche/siaes/admin.py
- lemarche/tenders/admin.py
- lemarche/utils/fields.py
Conversations : 
- ajout d'un fieldset dans l'admin
- renommer la méthode de pretty print pour clarifier
Siae : remonter le champ `group`
Tender : mettre le champ `source` en readonly
> Conversations : améliorer l'affichage dans l'admin

- lemarche/templates/siaes/_card_suggest_tender.html
- lemarche/templates/siaes/_detail_partner_cta.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/siaes/search_results.html
Nouvel encart pour pousser au dépôt de besoin.
Encart quasi identique à celui visible dans la recheche.
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/9d3e2d9c-92eb-4a5c-8662-2b973ed3f652)|![image](https://github.com/betagouv/itou-marche/assets/7147385/6550b8ac-a5d3-4da3-bd89-d9fd4c454482)|
> Dépôt de besoin : CTA sur les fiches structures

- lemarche/templates/layouts/_footer.html
- lemarche/www/pages/urls.py
- Créer la Flatpage dans l'admin (en prod)
- Pointer vers le lien de cette nouvelle page
> Footer : répare le lien vers les mentions légales

- lemarche/siaes/models.py
- lemarche/www/siaes/views.py
Ajout d'un `prefetch_related("groups")` pour enlever 1 requête au chargement de la page
> Fiche structure : petite optimisation de la queryset

- lemarche/templates/siaes/_detail_cta_v2.html
- lemarche/templates/siaes/_share_search_results.html
> Remplacement du terme "mail" par "e-mail"

- config/settings/base.py
- lemarche/templates/includes/_tracker_tarteaucitron.html
- lemarche/utils/settings_context_processors.py
https://tarteaucitron.io/fr/service/googletagmanager/
> Tarteaucitron : ajout de Google Tag Manager

- lemarche/templates/siaes/_useful_infos_siae_v2.html
- lemarche/templates/siaes/detail.html
Tout est dans le titre :)
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/37140ca5-4b1f-452a-9304-18fb758c6c4c)|![image](https://github.com/betagouv/itou-marche/assets/7147385/f1bd88f9-f264-4549-b9e9-55953280921d)|
> Fiche structure : indiquer la forme juridique

- lemarche/templates/auth/_login_or_signup_search_advanced_modal.html
- lemarche/templates/siaes/search_results.html
Sur la recherche, lorsque un utilisateur anonyme souhaite accéder à la recherche avancée, on lui affiche une modale d'explication & inscription (ou connexion) :
- bougé la modale dans un template dédié
- réparé l'url `next`
> [Recherche] Répare les liens de redirection après la modale de recherche avancée

- lemarche/static/itou_marche/sections/_home.scss
- lemarche/templates/cms/streams/section_our_partners.html
Ajout des classes CSS pour un affichage qui s'adapte au mieux.
Avant : 
Après :
> [CMS- Homepage] Correction sur l'affichage des logos partenaires

- config/settings/prod.py
- lemarche/www/tenders/forms.py
> [Dépot de besoin] Correction de la mise en forme la description

- lemarche/templates/siaes/_card_detail.html
- lemarche/templates/siaes/_useful_infos.html
- lemarche/www/siaes/forms.py
Suite de #940
- Afficher le nombre d'établissements (seulement si le nombre est supérieur à 1)
- Lien cliquable, ouvre un nouvel onglet avec une recherche par SIREN
exemple : aci-agent-de-collecte-et-de-valorisation-77
|Avant|Après|
|---|---|
|![Screenshot from 2023-10-10 11-42-02](https://github.com/betagouv/itou-marche/assets/7147385/70e58501-7a78-45fa-8014-c4ecb1d68e92)|![Screenshot from 2023-10-10 12-13-40](https://github.com/betagouv/itou-marche/assets/7147385/d2b434b5-2737-44db-84a8-beed38ae419e)|
> [Structure] Afficher le nombre d'établissement dans la fiche

- config/settings/base.py
- lemarche/templates/includes/_tracker_tarteaucitron.html
- lemarche/templates/siaes/detail.html
- lemarche/utils/settings_context_processors.py
- Suppression du tracking Hotjar
- Correction d'une typo sur Crisp
- Mise à jour du lien cassé "En savoir plus"
Hotjar n'est plus exploité.
> Suppression de Hotjar

- lemarche/templates/siaes/_annuaire_entreprises_button.html
Suite de #704
Sur les fiches structures, ajout d'un `mtm_campaign` sur le bouton qui pointe vers Annuaire Entreprise
> Fiche : ajout MTM sur le bouton Annuaire Entreprise

- lemarche/templates/pages/social-impact-for-buyers.html
Avant : X emplois durant 1 mois
Après : X emplois à temps plein durant 1 mois
> [Calculateur] Impact social : clarifier le wording

- lemarche/templates/dashboard/siae_search_by_siret.html
Indiquer que l'on n'a pas toutes les structures de l'ESS.
|Avant|Après|
|---|---|
|![image](https://github.com/betagouv/itou-marche/assets/7147385/df343b0b-f7aa-456d-ba38-0d44fe444f3b)|![image](https://github.com/betagouv/itou-marche/assets/7147385/258b5718-8af5-4b0c-9edd-45eb147fe206)|
> [Tableau de bord] Se rattacher à une structure : clarifier le wording

- lemarche/templates/layouts/_footer.html
- scripts/update_change_log.sh
On passe du repo `betagouv/itou-marche` à `gip-inclusion/le-marche` :tada: 
Checklist :
> [DevOps] Migration de repo Github

- lemarche/stats/models.py
- lemarche/templates/includes/_tracker_itou.html
- lemarche/utils/tracker.py
Améliorations sur le tracker : 
- remplacer user_type par user_kind (pour homogénéiser, script à lancer ensuite pour cleaner complètement les user_type de la base de stats)
- améliorer la detection des siae dans le contexte (lié à la PR #820, il y avait pas mal de stats sans user_kind)
> [Tracker] Petites améliorations sur siae_kind & user_kind

- lemarche/siaes/admin.py
Admin > Structures : rapprocher les champs "stats besoins" vers la gauche
> [Structures] Admin : réorganiser les colonnes

- lemarche/www/tenders/tests.py
TenderDetailView : jai remis le nez aujourd'hui sur le comportement des stats lorsqu'un utilisateur rattaché à plusieurs structures consulte un besoin. Il y a plusieurs cas de figure : 
- siae_id fourni : on met à jour le "email_link_click_date"
- utilisateur connecté : 
- si il gère 1 ou plusieurs structures concernées (contactées) par ce besoin : mettre à jour le "detail_click_date" de ces structures
- si il gère 1 ou plusieurs structures mais aucune n'est concernées : on rajouter des stats pour **chacune** de ses structures
> [Dépôt de besoin] Stats : ajout de tests supplémentaires pour les utilisateurs avec plusieurs structures

- lemarche/companies/management/commands/set_company_users.py
- lemarche/siaes/management/commands/update_api_qpv_fields.py
- lemarche/tenders/management/commands/update_tender_count_fields.py
J'ai récemment rajouté 2 management commandes qui sont lancées grâce au cron, mais il manquait une notif Slack pour avoir un recap de leurs actions.
> [Tech] Rajoute 2 notifications Slack sur des commandes cron

- lemarche/www/conversations/tasks.py
Améliorer la visibilité des disclaimer en ajoutant des étoiles et en mettant des italiques sur le texte.
> [Inbound Parsing] Améliorer la visibilité des disclaimer

- lemarche/templates/tenders/_detail_admin_extra_info.html
- lemarche/templates/tenders/_detail_cta_not_interested.html
- lemarche/templates/tenders/_detail_not_interested_click_confirm.html
- lemarche/templates/tenders/_detail_not_interested_click_error.html
- lemarche/templates/tenders/detail.html
- lemarche/tenders/models.py
- lemarche/www/tenders/tests.py
- lemarche/www/tenders/urls.py
- lemarche/www/tenders/views.py
Suite de #1037
Implémentation dans l'interface d'un nouveau bouton "Je ne suis pas intéressé"
|Détail d'un besoin||
|---|---|
|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/37cef428-55d0-490f-88f6-e166726d923f)||
> Dépôt de besoin : permettre à une structure d'indiquer qu'elle n'est pas intéressée

- lemarche/fixtures/django/10_tenders.json
- lemarche/templates/tenders/_detail_admin_extra_info.html
- améliore un peu les fixtures (pour les recettes jetables)
- admin : répare un icon
- admin : affiche la stats du nombre de prestataires intéressés par la co-traitance
> Dépôt de besoin : quelques améliorations (fixtures, icon)

- lemarche/api/tenders/tests.py
- lemarche/siaes/tests.py
- lemarche/tenders/tests.py
- lemarche/users/tests.py
- lemarche/www/siaes/tests.py
- lemarche/www/tenders/tests.py
> Tech : cleanup des tests pour utiliser au maximum assertTrue / False / IsNone / IsNotNone

- .github/workflows/pr-auto-author-assign.yml
Thanks to https://github.com/toshimaru/auto-author-assign
> Tech : workflow Github pour auto-assigner l'auteur à sa PR

- scripts/deploy_prod.sh
Ajout d'un `git log` entre `master` et `master_clever` pour voir les commits qui vont passer dans la MEP
à tester :sweat_smile:
> DevOps : Script de déploiement : voir les diffs ajoutées

- lemarche/templates/tenders/survey_transactioned_detail.html
- lemarche/utils/mixins.py
- lemarche/www/tenders/forms.py
- lemarche/www/tenders/tests.py
- lemarche/www/tenders/urls.py
- lemarche/www/tenders/views.py
Suite de #1071
Nouvelle vue avec le formulaire. Mise à jour des tests.
> Dépôt de besoin : sondage aux prestataires : formulaire et vue

- lemarche/tenders/migrations/0076_alter_tender_constraints.py
Lié à #1080 
Correction du conflit de migrations sur les dépôt de besoin
> Correction du conflit de migrations sur les dépôt de besoin

- .github/workflows/release-please.yml
https://github.com/google-github-actions/release-please-action
https://www.conventionalcommits.org/en/v1.0.0/
Générer automatiquement notre `CHANGELOG.md` et nos releases grâce au nommage de nos PR :robot:
> ci: ajout de la Github Action "release-please"

- lemarche/templates/conversations/_form_contact_modal.html
- lemarche/templates/pages/contact.html
- lemarche/www/pages/forms.py
Similaire à #862 
On ajoute un Captcha sur le formulaire de contact.
Pour réduire les spam
> feat(contact): Ajout de MTCaptcha sur le formulaire de contact

- clevercloud/crm_brevo_sync.sh
- clevercloud/cron.json
- config/settings/base.py
- lemarche/crm/management/commands/crm_brevo_sync.py
- lemarche/utils/apis/api_brevo.py
Suite de #1099
Tous les lundi matin, envoyer les nouvelles SIAE + mises à jour au CRM Brevo
J'ai mis ca dans une nouvelle "app" : `crm`
> feat(Brevo): Commande pour synchroniser toutes les semaines les entreprises (SIAE)

- lemarche/networks/management/commands/link_siae_to_network.py
On reçoit parfois des fichiers CSV pour rattacher les structures à leur réseau (mise à jour ~annuelle).
Script pour essayer de documenter / réutiliser cela.
> feat(SIAE): script pour aider le rattachement à leur réseau (grâce à des import csv)

- lemarche/templates/tenders/detail.html
- lemarche/www/tenders/tests.py
Suite à #1114, la modale d'inscription ne s'affichait plus.
- réparé
> feat(Besoins): Détail : répare l'affichage de la modale d'inscription pour les utilisateurs inconnus

- lemarche/www/dashboard_networks/tests.py
Tentative pour réparer des flaky tests
> fix: Répare des tests qui cassent parfois

- lemarche/www/tenders/tasks.py
Il nous manquait un log lors de l'envoi d'un besoin à une structure (et potentiellement à ses utilisateurs)
> refactor(Besoins): au moment de l'envoi à la structure, logger l'action

- lemarche/tenders/admin.py
- lemarche/tenders/tests.py
- lemarche/www/tenders/views.py
Suite de #1144 & #1143
Dans l'admin, on affichait déjà la liste des utilisateurs qui sont **intéressés** par le besoin.
J'ai rajouté la liste des utilisateurs qui ont **vus** le besoin.
> feat(Besoins): Admin: afficher les utilisateurs qui ont vu le besoin

- lemarche/labels/tests.py
- lemarche/siaes/tests.py
- lemarche/www/siaes/tests.py
> fix: Répare encore des tests qui cassent parfois

- lemarche/fixtures/django/20_cms.json
- lemarche/templates/auth/_login_or_signup_modal.html
- lemarche/templates/layouts/_header_nav_primary_items.html
- lemarche/www/pages/tests.py
- le lien "S'inscrire" devient "Référencé ma structure" sur l'accueil des structures
- ajout de l'accueil structure dans les fixtures
- ajout de test
- suppression de la modale "Se connecter" quand on est connecté (révélé par les tests :) )
> feat: Changement du nom du lien d'inscription sur l'accueil des structures

- lemarche/www/tenders/tasks.py
Renommer les titres d'emails pour ne pas avoir l'impression d'envoyer deux fois le même mail.
Des demandes de supports concernant les mails en doublons.
Rendre les titres d'emails plus uniques.
> feat(Dépôt de besoins): renommer les titres d'emails pour ne pas avoir l'impression d'envoyer deux fois le même mail

- lemarche/templates/includes/_tracker_itou.html
- lemarche/templates/siaes/_detail_admin_extra_info.html
- lemarche/templates/siaes/detail.html
- lemarche/templates/tenders/_detail_sidebar.html
- lemarche/www/siaes/views.py
- lemarche/www/tenders/views.py
Page détail d'une structure : quelques améliorations sur l'encart affiché aux admins : 
- afficher le nom complet
- afficher les infos dans tous les cas (même si elles sont manquantes)
- afficher le nombre de collaborateurs
J'en ai profité pour faire quelques mini-refactoring pour simplifier le code :)
> fix(Structures): Détail : améliorer les informations affichées aux admin

- lemarche/templates/siaes/_card_detail.html
- lemarche/templates/siaes/_card_suggest_tender.html
- lemarche/templates/siaes/_si_ideas_search_result.html
- lemarche/templates/siaes/detail.html
Quelques minis changements d'UI pour homogénéiser l'affichage
|page|Avant|Après|
|---|---|---|
|Recherche > idées reçues|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/aed4c887-cd2f-455f-8c91-a547b7e0a78a)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/73d90a22-b375-4bd3-9c0a-3b8f47b4de14)|
|Recherche > encart besoins|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/c121b5a8-09dc-48ee-84a2-b550626398cb)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/656be79c-a874-480d-85aa-c974e4a49db6)|
|Structure > détail|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/bbd38693-52c8-4309-b1c2-adbcf4f702ee)|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/35290914-cd5c-4673-82aa-e9c9849172d5) …
> fix(Structures): quelques améliorations d'affichage sur la page recherche & détails

- clevercloud/companies_update_users_and_count_fields.sh
- clevercloud/conversations_delete_outdated.sh
- clevercloud/crm_brevo_sync_companies.sh
- clevercloud/cron.json
- clevercloud/siaes_export_all_siae_to_file.sh
- clevercloud/siaes_send_completion_reminder_emails.sh
- clevercloud/siaes_send_user_request_reminder_emails.sh
- clevercloud/siaes_sync_c2_c4.sh
- clevercloud/siaes_sync_elasticsearch_index.sh
- clevercloud/siaes_sync_with_emplois_inclusion.sh
- clevercloud/siaes_update_api_entreprise_fields.sh
- clevercloud/siaes_update_api_qpv_fields.sh
- clevercloud/siaes_update_api_zrr_fields.sh
- clevercloud/siaes_update_count_fields.sh
- clevercloud/siaes_update_super_badge_field.sh
- clevercloud/stats_export_user_download_list_to_file.sh
- clevercloud/stats_export_user_search_list_to_file.sh
- clevercloud/tenders_send_author_list_of_super_siaes_emails.sh
- clevercloud/tenders_send_author_transactioned_question_emails.sh
- clevercloud/tenders_send_siae_contacted_reminder_emails.sh
- clevercloud/tenders_send_siae_interested_reminder_emails.sh
- clevercloud/tenders_send_siae_transactioned_question_emails.sh
- clevercloud/tenders_send_validated.sh
- clevercloud/tenders_update_count_fields.sh
- lemarche/siaes/management/commands/put_siaes_in_elasticsearch_index.py
- lemarche/utils/apis/api_elasticsearch.py
Réindexation complète des structures dans l'index Elasticsearch.
Pour avoir des informations sur les structures (description et offres) les plus à jour possible pour la recherche sémantique et le matching IA.
Script lancé à 1:15 UTC tous les lundi
1) Suppression de tous les documents présents dans l'index.
2) Réindexation complète.
Penser à ajouter la variable `CRON_SIAES_SYNC_ELASTICSEARCH_INDEX_ENABLED` pour activer le script.
> feat(Structures): Réindexation automatique des structures dans l'index Elasticsearch

- lemarche/siaes/management/commands/create_siae_activities.py
- lemarche/siaes/tests.py
- lemarche/siaes/utils.py
Suite de #1261 
Management command pour générer automatiquement les `SiaeActivity`
- gérer les structures dont on n'arrive pas à matcher la localisation ?
> refactor(Structures): SiaeActivity : script pour les générer à partir des Siae

- lemarche/static/js/siae_activity_delete.js
- lemarche/templates/dashboard/_siae_activity_card.html
- lemarche/templates/dashboard/_siae_activity_delete_modal.html
- lemarche/templates/dashboard/siae_edit_activities.html
- lemarche/www/dashboard_siaes/urls.py
- lemarche/www/dashboard_siaes/views.py
Pouvoir supprimer une activité
||Image|
|---|---|
|Liste|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/054d0981-09e4-4363-b1f8-2cd82ae6d69d)|
|Modale de confirmation|![image](https://github.com/gip-inclusion/le-marche/assets/7147385/fc84db0f-94b0-48cc-a399-8f02428b25af)|
> feat(Structures): SiaeActivity : pouvoir supprimer une activité

- lemarche/templates/dashboard/_siae_activity_card.html
- lemarche/templates/dashboard/siae_edit_activities_create.html
- lemarche/www/dashboard_siaes/urls.py
- lemarche/www/dashboard_siaes/views.py
Réutiliser le formulaire de création d'une activité, mais cette fois-ci pour la modification
Adapter un peu pour rendre le contenu dynamique (afficher l'activité existante, Ajouter -> Modifier, ...)
> feat(Structures): pouvoir modifier une activité

- lemarche/utils/apis/api_qpv.py
Correction de l'erreur de synchronisation des infos QPV : KeyError: 'code_qp'.
Le champs a été supprimer dans les données retournées au profit du champs "identifiant".
Remplacement du nom du champs.
> fix(API QPV): Adaptation suite à la suppression du champs "code_qv"

- .github/auto_assign.yml
- .github/dependabot.yml
Départ oblige, je me retire des réglages des CI :smiling_face_with_tear:
> ci: Enlever les références à raphodn

- lemarche/static/itou_marche/itou_marche.scss
- lemarche/templates/dashboard/home_buyer.html
- lemarche/templates/dashboard/home_siae.html
- lemarche/templates/dashboard/siae_edit_base.html
- lemarche/templates/dashboard/siae_users.html
- lemarche/templates/favorites/dashboard_favorite_list.html
- lemarche/templates/pages/impact-calculator.html
- lemarche/templates/siaes/_share_search_results.html
- lemarche/templates/siaes/search_results.html
Ajustement de marge & couleur de texte des Hx dans le hero
Le retrait d'un container pour éviter des marges avec Wagtail, ça a supprimer des marges dans beaucoup de pages..
Ajout de classe utilitaire sur les containers.
Désolé pour le reformatage des templates, mais je pense que c'est une bonne chose. j'ai activé le on_save black 😬
> fix: ajout des marges manquante en bas de page

- lemarche/templates/tenders/siae_interested_list.html
- Renommage d'un onglet en double
- correction du aria-control pour avoir le contour du premier onglet
- ajout du JS nécessaire pour les multiselects.
Avant
Après
> fix(Dashboard Acheteurs): correction d'un onglet et des multiselects

- lemarche/utils/apis/api_brevo.py
L'argument `update_enabled` a été mis à False durant les tests et j'ai oublié de le remettre à True
> fix(Brevo): update_enabled arg in 'api_brevo.create_contact'

- .github/auto_assign.yml
Ajout de Guillaume aux reviewers ;)
Parce qu'on est très content de l'accueillir dans l'équipe
Ajout à la liste des auto_assign
> chore(dev): welcome Guillaume !

- .github/workflows/linting_testing.yml
Mise à niveau des actions Github et de la version Python utilisée 
Pour corriger les erreurs de la CI
Passage à la dernière version de chaque action.
> chore(CI): Mse à niveau des versions des actions Github

- lemarche/tenders/admin.py
https://github.com/gip-inclusion/le-marche/pull/1596/files#diff-be0153b872774730059b0b897b9bde80c22f1626c878f0dcabc753b20315d3deL586
Il avait été supprimé dans cette PR: https://github.com/gip-inclusion/le-marche/pull/1596/files#diff-be0153b872774730059b0b897b9bde80c22f1626c878f0dcabc753b20315d3deL586
J'ai zappé ca dans la revue, @SebastienReuiller je ne sais pas si c'est une suppression accidentelle, mais tu pourra valider et merge direct la PR car je ne suis pas là.
> fix: Methode save() supprimée de l'admin des besoins

- lemarche/templates/tenders/_detail_contact_click_confirm_modal.html
- lemarche/tenders/forms.py
Demande d'Abdess:
* Mettre en H1 : L'acheteur vous a posé quelques questions
* En sous-titre : Vos réponses vous permettront d'être mis en relation avec lui.
* "Sélectionnez les structures pour ...." deviendrait : Pour quelle(s) structure(s) souhaitez-vous répondre ?
* Et le texte de la question, partir sur un H2 pour améliorer la hiérarchie de l'information.
> chore: Modification du texte de la modale des questions

- lemarche/tenders/admin.py
Filtre rapide dans l'admin pour selectionner les sources tally / pro
> chore: filtre Tally dans l'admin des besoins

- lemarche/api/inclusive_potential/constants.py
- lemarche/api/inclusive_potential/serializers.py
- lemarche/api/inclusive_potential/tests.py
- lemarche/api/inclusive_potential/views.py
Ajout de la répartition Handicap / Inclusion dans le retour de l'API
Ajout du nombre de structure ayant le "super badge"
Pour permettre aux acheteurs de voir si leur projet d'achat peut intégrer un dispositif inclusif.
Décompte sur le "kind" et le booléen "super badge".
> feat(API): Ajout de la répartition du potentiel inclusif

- lemarche/conversations/admin.py
- lemarche/tenders/admin.py
1 - Correction de la recherche sur les logs d'envoi des templates de mail
2 - Suppression d'une N+1 sur la liste des besoins
3 - Correction du lien sur les besoins déposés sur la page d'admin d'une entreprise :
> fix(Admin): Corrections rapides dans l'admin

- lemarche/templates/tenders/_detail_sidebar.html
- lemarche/www/tenders/tests.py
- lemarche/www/tenders/views.py
En dessous d'un certain seuil le compteur de vue ne s'affiche pas, un simple texte en fonction du type de besoin est affiché.
> feat: Compteur vue sur un besoins plus incitatif

- config/settings/base.py
- lemarche/templates/includes/_tracker_tarteaucitron.html
- lemarche/utils/context_processors.py
Utile pour les changements liés à l'UI.
- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.
> feat: masquer les slugs des urls envoyées à Matomo
